### ISSUE TITLE
libnest3.so not compiling on Mac OSX 10.6.8

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyMultiNest#10]
Hi Johannes,

I'm trying to compile libnest3.so from multinest 2.18 so I can install the multinest bridge, but

make libnest3.so WITHOUT_MPI=1

fails thus:

localhost:MultiNest_v2.18 jtlz2$ make libnest3.so
ld -shared -o  libnest3.so utils.o utils1.o priors.o kmeans_clstr.o xmeans_clstr.o posterior.o nested.o 
ld: unknown option: -shared
make: *** [libnest3.so] Error 1

If I remove -shared I get:

[snip]
      ___nested_MOD_gen_initial_live in nested.o
      ___nested_MOD_nestsample in nested.o
      ___nested_MOD_nestsample in nested.o
      ___nested_MOD_nestsample in nested.o
      ___nested_MOD_nestsample in nested.o
      ___nested_MOD_nestrun in nested.o
      ___nested_MOD_nestrun in nested.o
      ___nested_MOD_nestrun in nested.o
      ___nested_MOD_nestrun in nested.o
      ___nested_MOD_nestrun in nested.o
  "_dsyevr_", referenced from:
      ___utils1_MOD_diagonalize in utils1.o
      ___utils1_MOD_diagonalize in utils1.o
  "_tan", referenced from:
      ___priors_MOD_cauchyprior in priors.o
ld: symbol(s) not found for inferred architecture i386

If I remove -m64 from my FC (see below) I still get:

localhost:MultiNest_v2.18 jtlz2$ make libnest3.so
gfortran -ffree-line-length-none -O3  -c -o utils.o utils.f90 
gfortran -ffree-line-length-none -O3  -c -o utils1.o utils1.f90 
gfortran -ffree-line-length-none -O3  -c -o priors.o priors.f90 
gfortran -ffree-line-length-none -O3  -c -o kmeans_clstr.o kmeans_clstr.f90 
gfortran -ffree-line-length-none -O3  -c -o xmeans_clstr.o xmeans_clstr.f90 
gfortran -ffree-line-length-none -O3  -c -o posterior.o posterior.F90 
gfortran -ffree-line-length-none -O3  -c -o nested.o nested.F90 
ld -shared -o  libnest3.so utils.o utils1.o priors.o kmeans_clstr.o xmeans_clstr.o posterior.o nested.o 
ld: unknown option: -shared
make: *** [libnest3.so] Error 1

My makefile is modified from the supplied version:

< #FC = mpif90
< FC = gfortran -ffree-line-length-none -m64
< #CC = mpicc
< CC = gcc
< #CXX = mpiCC
< CXX = gcc
< FFLAGS += -O3 #-DMPI
< CFLAGS += -O3 #-DMPI
---
> FC = mpif90
> CC = mpicc
> CXX = mpiCC
> FFLAGS += -O3 -DMPI
> CFLAGS += -O3 -DMPI

and multinest itself compiles and the examples (and indeed my own lhoods) have been running fine.

Any ideas? Thanks in advance for a speedy reply.

**Comment by ajamyajax** [comment]
Hi Johannes,

Well, I'm trying to create the Windows DLL and can't seem to get the lapack library to link.  Any ideas would be appreciated.  All source compiled with GNU Fortran (GCC) 5.3.0.

gfortran -shared -o libmultinest.dll utils.o utils1.o priors.o kmeans_clstr.o xmeans_clstr.o posterior.o nested.o -L \lapack\lapack.a  

With the above I get the following reference errors.. (Including those object files just produced a long list of missing lapack references.)

utils1.o:utils1.f90:(.text+0x1a5): undefined reference to 'dpotrf_'
utils1.o:utils1.f90:(.text+0x37b1): undefined reference to 'dsyevr_'
utils1.o:utils1.f90:(.text+0x3974): undefined reference to 'dsyevr_'
xmean_clstr.o:xmeans_clstr.f90:(.text+0x11adc): undefined reference to 'dlasrt_'
nested.o:nested.F90:(.text+0x270c): undefined reference to 'dgeev_'
collect2.exe: error ld returned 1 exit status

Thanks, Mark
