### ISSUE TITLE
Run Pymultinest inside MPI proccess

### ISSUE THREAD

**Issue by mvsantosdev** [JohannesBuchner/PyMultiNest#100]
Dears,

I am trying to run a simple code like this:

from mpi4py import MPI
import pymultinest

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
(...)
for x in list:

	pymultinest.run(...)

executing
>>> mpiexec -n 4 python code.py
or
>>> mpirun -n 4 python code.py

It throws: "Attempting to use an MPI routine before initializing MPICH"

And when I set init_MPI-True in pymultinest.run args:

[cli_0]: Command cmd=put kvsname=kvs_21209_0 key=sharedFilename[0] value=/dev/shm/mpich_shar_tmprY3lCH
 failed, reason='duplicate_keysharedFilename[0]'
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474).....: 
MPID_Init(190)............: channel initialization failed
MPIDI_CH3_Init(89)........: 
MPID_nem_init(272)........: 
MPIDI_CH3I_Seg_commit(337): PMI_KVS_Put returned -1
[mpiexec@marcelo-Inspiron-7460] handle_pmi_cmd (./pm/pmiserv/pmiserv_cb.c:52): Unrecognized PMI command: abort | cleaning up processes
[mpiexec@marcelo-Inspiron-7460] control_cb (./pm/pmiserv/pmiserv_cb.c:289): unable to process PMI command
[mpiexec@marcelo-Inspiron-7460] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@marcelo-Inspiron-7460] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:181): error waiting for event
[mpiexec@marcelo-Inspiron-7460] main (./ui/mpich/mpiexec.c:405): process manager error waiting for completion

**Comment by JohannesBuchner** [comment]
You should not use mpi4py yourself. pymultinest already handles it. You only need `pymultinest.run(...)` in your code, and run with `mpiexec -n 4 python code.py`.

**Comment by JohannesBuchner** [comment]
The error occurs because `from mpi4py import MPI` already initialises MPI, but you are asking multinest to initialise it again.

**Comment by mvsantosdev** [comment]
I would like to run pymultinest many times, for many different cases (datasets), this is why I choose to run inside a for loop. The idea is split the total for loop in blocks, one for each process. So if I choose init_MPI=False it will initialise just one time when I start, right? But it throws "Attempting to use an MPI routine before initializing MPICH".

**Comment by JohannesBuchner** [comment]
I am not sure it will work. You would have to check the multinest source code to see how it initialises and how that compares to what mpi4py does.

Alternative options are:
- make the look outside the script (e.g. with bash or another python script that runs mpiexec with subprocess).
- avoid MPI altogether and use e.g. xargs --maxprocs or make -j to parallelise python scripts with arguments across CPUs.

**Comment by JohannesBuchner** [comment]
If you choose init_MPI=False you have to init yourself once (by importing mpi4py). But I am not 100% it really works.

**Comment by ChristopherAJDuncan** [comment]
Is this intrinsic to MultiNest, or PyMultiNest?

Although this is a useful feature, I would argue that any optimiser/sampler shouldn't force MPI on the user. I write a lot of lnL calculators which are computationally expensive in CPU and RAM, and therefore always construct the MPI myself, built into the lnL itself: this has the advantage that all optimiser should be able to use MPI even if they are not written to. However, this gives problems with PMN as described above, and means that I simply can't use it.

This is a shame, because PMN is genuinely my favoured sampler. It's a great code, and a great algorithm.

Could the removal of enforced MPI be implemented in a future release?
