### ISSUE TITLE
[root]post_equal_weights.dat contains some duplicate points, Is it normal?

### ISSUE THREAD

**Issue by yuanfangtardis** [JohannesBuchner/PyMultiNest#101]
Hi, I have  implemented Multinest in my private code to scan supersymmetry parameter space. Then I run my code using MPI. I found some duplicate points in the file post_equal_weights.dat, i.e.  some lines contain exactly the same point.   Is it normal? I know that [root]post_equal_weights.dat is posterior  equal_weigted samles so a points appearing twice means this point may have twice the probability than other points who appear just once. But I'm not sure that I am coreect. Could you please help me?

**Comment by JohannesBuchner** [comment]
Yes, that is normal and your interpretation is correct.
