### ISSUE TITLE
best fit parameters lying outside 1sigma error bars

### ISSUE THREAD

**Issue by cefisher** [JohannesBuchner/PyMultiNest#104]
Not necessarily an issue with the software, but I'm just wondering what the significance is if the best fit parameters obtained at the end are actually outside the 1sigma error bars? Is this unusual? Does it suggest the process is not converging properly?

**Comment by JohannesBuchner** [comment]
This is not unusual. Just like in MCMC, it means that the prior (which informs about the volume, or the space density) is important. The location of the maximum likelihood parameters don't tell you much otherwise.

**Comment by cefisher** [comment]
Hmm so if I'm using simple uniform priors, does this suggest they are too wide?

**Comment by JohannesBuchner** [comment]
Look at the 2d marginal plots. It just means that your prior has a lot of space elsewhere, which fits almost as well.

For example, if your posterior looks like an "L", with the best fit in one of the arms, the pdf will be dragged by the other arm. 
As another example, if the maximum likelihood is near a parameter limit, the 1sigma approximation is probably not valid.
