### ISSUE TITLE
Solver doesn't support nparams?

### ISSUE THREAD

**Issue by jluastro** [JohannesBuchner/PyMultiNest#108]
I am trying to use the pythonic (OO) implementation of PyMultiNest. I have a class that subclasses Solver. I have a case where n_dims != n_params, so I need to pass both into Prior() and LogLikelihood(). There appears to be some check of the number of parameters in LogLikelihood that doesn't work in this case (in run()) I think. Here is the full code; although it won't run without a bunch of other dependencies (see below). But I think the simple idea of a Prior(self, cube, n_dim, n_params) implementation (same with LogLikelihood) will break. 

`class PSPL_Solver(Solver):
    """
    A PyMultiNest solver to find the optimal PSPL parameters given astrometry
    and photometry data. 

    Inputs
    ------
    data : dictionary
        Contains all the data in different fields. The keys into the dictionary 
        must include the following.
        
        Photometry:
            t_phot (MJD)
            mag
            mag_err
        Astrometry: 
            t_ast (MJD)
            xpos (arcsec along East-West increasing to the East???)
            ypos (arcsec along the North-South increasing to the North)
            xpos_err (arcsec)
            ypos_err (arcsec)
    
    Optional Inputs
    ---------------
    n_live_points : int
        PyMultiNest input param.

    saveto : str
        Directory for the output.

    runcode : str
        Rootname of the output files. 

    """
    def __init__(self, data, wrapped_params = None, 
                     importance_nested_sampling = False,
                     multimodal = True, const_efficiency_mode = False, n_live_points = 300,
                     evidence_tolerance = 0.5, sampling_efficiency = 0.8, 
                     n_iter_before_update = 100, null_log_evidence = -1e90,
                     max_modes = 100, mode_tolerance = -1e90,
                     outputfiles_basename = "chains/1-", seed = -1, verbose = False,
                     resume = False, context = 0, write_output = True, log_zero = -1e100, 
                     max_iter = 0, init_MPI = False, dump_callback = None):
        """
        Accepeted optional inputs are the same as on pymultinest.run.run(). 
        """
        
        self.data = data

        self.n_dims = 12
        self.n_params = 20  # cube will have this many dimensions
        self.n_clustering_params = self.n_dims
        self.multimodal = multimodal
        self.wrapped_params = wrapped_params
        self.importance_nested_sampling = importance_nested_sampling
        self.const_efficiency_mode = const_efficiency_mode
        self.n_live_points = n_live_points
        self.evidence_tolerance = evidence_tolerance
        self.sampling_efficiency = sampling_efficiency
        self.n_iter_before_update = n_iter_before_update
        self.null_log_evidence = null_log_evidence
        self.max_modes = max_modes
        self.mode_tolerance = mode_tolerance
        self.outputfiles_basename = outputfiles_basename
        self.seed = seed
        self.verbose = verbose
        self.resume = resume
        self.context = context
        self.write_output = write_output
        self.log_zero = log_zero
        self.max_iter = max_iter
        self.init_MPI = init_MPI
        self.dump_callback = dump_callback

        self.mL_gen = make_gen(0, 100)
        self.t0_gen = make_t0_gen(self.data['t_phot'], self.data['mag'])
        self.xS0_x_gen = make_gen(self.data['xpos'].min(), self.data['xpos'].max())
        self.xS0_y_gen = make_gen(self.data['ypos'].min(), self.data['ypos'].max())
        self.beta_gen = make_gen(-2, 2)
        self.muL_x_gen = make_gen(-20, 20)
        self.muL_y_gen = make_gen(-20, 20)
        self.muS_x_gen = make_muS_xy_gen(self.data['t_ast'], self.data['xpos'])
        self.muS_y_gen = make_muS_xy_gen(self.data['t_ast'], self.data['ypos'])
        self.dL_gen = make_gen(1000, 7000)
        self.dL_dS_gen = make_gen(0.01, 0.99)
        self.mag_base_gen = make_gen(10.0, 22.0)

        print(type(self.mL_gen))
        
        #self.make_default_priors()

        return

    def solve(self):
        results = pymultinest.solve(self.LogLikelihood, self.Prior, self.n_dims,
                                  n_params = self.n_params,
                                  n_clustering_params = self.n_clustering_params,
                                  multimodal = self.multimodal,
                                  importance_nested_sampling = self.importance_nested_sampling,
                                  wrapped_params = self.wrapped_params,
                                  const_efficiency_mode = self.const_efficiency_mode,
                                  n_live_points = self.n_live_points,
                                  evidence_tolerance = self.evidence_tolerance,
                                  sampling_efficiency = self.sampling_efficiency,
                                  n_iter_before_update = self.n_iter_before_update,
                                  null_log_evidence = self.null_log_evidence,
                                  max_modes = self.max_modes,
                                  mode_tolerance = self.mode_tolerance,
                                  outputfiles_basename = self.outputfiles_basename,
                                  seed = self.seed,
                                  verbose = self.verbose,
                                  resume = self.resume,
                                  context = self.context,
                                  write_output = self.write_output,
                                  log_zero = self.log_zero,
                                  max_iter = self.max_iter,
                                  init_MPI = self.init_MPI,
                                  dump_callback = self.dump_callback)
        
        for k, v in results.items():
            setattr(self, k, v)

        return
    
    def make_default_priors(self):
        """
        Seutp our prior distributions (i.e. random samplers). We will
        draw from these in the Prior() function. We set them up in advance
        because they depend on properties of the data. Also,
        they can be over-written by custom priors as desired. 
        """
        # Model Parameters: mL, t0, xS0, beta, muL, muS, dL, dS, imag_base
        self.mL_gen = make_gen(0, 100)
        self.t0_gen = make_t0_gen(self.data['t_phot'], self.data['mag'])
        self.xS0_x_gen = make_gen(self.data['xpos'].min(), self.data['xpos'].max())
        self.xS0_y_gen = make_gen(self.data['ypos'].min(), self.data['ypos'].max())
        self.beta_gen = make_gen(-2, 2)
        self.muL_x_gen = make_gen(-20, 20)
        self.muL_y_gen = make_gen(-20, 20)
        self.muS_x_gen = make_muS_xy_gen(self.data['t_ast'], self.data['xpos'])
        self.muS_y_gen = make_muS_xy_gen(self.data['t_ast'], self.data['ypos'])
        self.dL_gen = make_gen(1000, 7000)
        self.dL_dS_gen = make_gen(0.01, 0.99)
        self.mag_base_gen = make_gen(10.0, 22.0)

        return
        
    def Prior(self, cube, ndim, nparams):
        print('self.n_params = ', self.n_params)
        print('self.n_dims = ', self.n_dims)
        print(type(self.mL_gen))
        
        cube[0] = self.mL_gen.ppf(cube[0])
        cube[1] = self.t0_gen.ppf(cube[1])
        cube[2] = self.xS0_x_gen.ppf(cube[2])
        cube[3] = self.xS0_y_gen.ppf(cube[3])
        cube[4] = self.beta_gen.ppf(cube[4])
        cube[5] = self.muL_x_gen.ppf(cube[5])
        cube[6] = self.muL_y_gen.ppf(cube[6])
        cube[7] = self.muS_x_gen.ppf(cube[7])
        cube[8] = self.muS_y_gen.ppf(cube[8])
        cube[9] = self.dL_gen.ppf(cube[9])
        cube[10] = self.dL_dS_gen.ppf(cube[10])
        cube[11] = self.mag_base_gen.ppf(cube[11])
        
        return cube
	
    def LogLikelihood(self, cube, ndim):
        print('lnL: self.n_params = ', self.n_params)
        print('lnL: self.n_dims = ', self.n_dims)
        print('lnL: ', type(self.mL_gen))
        print('lnL: cube.shape = ', cube.shape)
        
        mL = cube[0]
        t0 = cube[1]
        xS0 = np.array([cube[2], cube[3]])
        beta = cube[4]
        muL = np.array([cube[5], cube[6]])
        muS = np.array([cube[7], cube[8]])
        dL = cube[9]
        dLdS = cube[10]
        mag_base = cube[11]

        # Extra parameters
        dS = (1.0 * dL) / dLdS
        cube[12] = dS
        
        pspl = model.PSPL(mL, t0, xS0, beta, muL, muS, dL, dS, mag_base)

        cube[13] = pspl.tE
        cube[14] = pspl.thetaE_amp
        cube[15] = pspl.piE[0]
        cube[16] = pspl.piE[1]
        cube[17] = pspl.u0_amp
        cube[18] = pspl.muRel[0]
        cube[19] = pspl.muRel[1]

        lnL_phot = pspl.likely_photometry(self.data['t_phot'], self.data['mag'], self.data['mag_err'])
        lnL_ast = pspl.likely_astrometry(self.data['t_ast'], self.data['xpos'], self.data['ypos'],
                                             self.data['xpos_err'], self.data['ypos_err'])

        lnL = lnL_phot.mean() + lnL_ast.mean()

        fmt = 'mL={0:4.1f} t0={1:7.1f} xS0=[{2:8.4f}, {3:8.4f}] beta={4:5.2f} '
        fmt += 'muL=[{5:6.2f}, {6:6.2f}] muS=[{7:6.2f}, {8:6.2f}] dL={9:5.0f} dS={10:5.0f} '
        fmt += 'imag={11:4.1f} lnL={12:12.2e}'
        
        # print fmt.format(mL, t0, xS0[0], xS0[1], beta, muL[0], muL[1], muS[0], muS[1], dL, dS, imag_base, lnL)

        return lnL
`

The error message I get is:
` *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  300
 dimensionality =   12
 *****************************************************
ERROR in prior: Prior() missing 2 required positional arguments: 'ndim' and 'nparams'
`

**Comment by jluastro** [comment]
Note, if you are interested in why I chose this implementation: 

I was trying to write a Solver object that could have the priors changed before running the full solver. Hence, I don't call Solver.__init__() and instead implement a solve() function inside my object. I don't think this should be relevant to the issue above; but let me know if you would like more details.

**Comment by andrewfowlie** [comment]
I think the signature of your Prior and LogLikelihood is incorrect. When using solve, they shouldn’t have the ndims or nparams arguments

https://github.com/JohannesBuchner/PyMultiNest/blob/5d8c1036062d23ed22d8c00d544b8103ec478baa/pymultinest/solve.py#L18-L30

it still supports nparams but as an attribute of the class, not an argument to the callback functions

**Comment by JohannesBuchner** [comment]
Yes, what @andrewfowlie said, just remove the "ndim, nparams" and "ndim" parameters.

**Comment by jluastro** [comment]
I have tried running without those parameters in the Prior and LogLikelihood. The n_dim and n_params parameters are set on the object. But then the cube object is only instantiated to have a size of n_dim. I get an error as soon as I try to access cube[12] (the first non-fit-parameter).

**Comment by JohannesBuchner** [comment]
Ah ... right. Yes, I never worked much with n_params!=n_dim. You should be able to do it with the classic interface (pymultinest.run).
solve has a convenience function that unpacks the c array into a numpy array. I think that one should then be changed to use n_params instead of n_dim.

**Comment by JohannesBuchner** [comment]
I think this should be fixed based on merged PR #150
