### ISSUE TITLE
Multinest install problem

### ISSUE THREAD

**Issue by zxzhai** [JohannesBuchner/PyMultiNest#109]
I am trying to build the library libmultinest.so on a server following:

git clone https://github.com/JohannesBuchner/MultiNest
cd MultiNest/build
cmake ..
make

cmake .. works fine for me. But when I run make, it gives me the error:

/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [../lib/libmultinest.so.3.10] Error 1
make[1]: *** [src/CMakeFiles/multinest_shared.dir/all] Error 2
make: *** [all] Error 2

I have libblas.a and liblapack.a installed. Is there something I can do to fix this problem? Thanks!

**Comment by JohannesBuchner** [comment]
What is the OS, and compiler version? You need dynamic libraries (.so, built with -fPIC) to build multinest in a form that pymultinest can use (libmultinest.so).

**Comment by zxzhai** [comment]
It turns out to be the problem from dynamic libraries. I reinstalled lapack and blas, and the problem is now solved. The OS is Red Hat with gcc version of 4.8.5.
Thanks!
