### ISSUE TITLE
MPI and PyMultiNest

### ISSUE THREAD

**Issue by kssiobr** [JohannesBuchner/PyMultiNest#110]
Dear Johannes Buchner,

I saw some issues about running PyMultiNest with MPI, but none of them seem to fit perfectly with my problem. 

When I try to run 'mpiexec -n 2 python main.py', I think that it is trying to build two independent chains:
"
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    3
 *****************************************************
 Starting MultiNest
 dimensionality =    3
 *****************************************************
 Starting MultiNest
 generating live points
 generating live points
(..) "

I remember when using MultiNest, the output said that only one chain was being initialized. 
And at some point the process stop with the message:

Acceptance Rate:                        0.636492
Replacements:                               1350
Total Samples:                              2121
Nested Sampling ln(Z):                -34.732766
Importance Nested Sampling ln(Z):     -10.733349 +/-  0.176871
Acceptance Rate:                        0.636492
Replacements:                               1350
Total Samples:                              2121
Nested Sampling ln(Z):                -34.732766
Importance Nested Sampling ln(Z):     -10.733349 +/-  0.176871
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 1 with PID 0 on node MacBook-Pro-2 exited on signal 11 (Segmentation fault: 11).
--------------------------------------------------------------------------

I included as an example the Acceptance Rate, Replacements, Total Samples info so we can see that does not seem to have communication between the two chains.

And the number of chains initialized is the same of the input for mpi. 

I tried 'mpiexec -n 1 python main.py' and it runs perfectly.

Could you help me, please?

Best regards,

Cassio Pigozzo

**Comment by JohannesBuchner** [comment]
Did you install mpi4py?

**Comment by kssiobr** [comment]
Yes. On both my MacBook and on a cluster. Same issue.

**Comment by JohannesBuchner** [comment]
Seeing the two multinest headers indicates that the non-MPI multinest library is loaded (the _mpi should be loaded, but the normal one is). Did you build both with cmake and are they available in the same folder? I think you have to put a few prints into pymultinest to figure out why it is loading what it is loading. strace might also help.

**Comment by JohannesBuchner** [comment]
The following should be a more minimal test case:
```
python -c 'from pymultinest.run import libname; print(libname)'
mpiexec -np 2 python -c 'from pymultinest.run import libname; print(libname)'
```

**Comment by kssiobr** [comment]
Both return 'libmultinest.dylib'

**Comment by kssiobr** [comment]
At least in my personal computer, at usr/local/lib there are:

libmultinest.3.10.dylib
libmultinest.a
libmultinest.dylib
libmultinest_mpi.3.10.dylib
libmultinest_mpi.a
libmultinest_mpi.dylib

**Comment by JohannesBuchner** [comment]
This part is not working for you:
```
libname = 'libmultinest'
try: # detect if run through mpiexec/mpirun
	from mpi4py import MPI
	if MPI.COMM_WORLD.Get_size() > 1: # need parallel capabilities
		libname = 'libmultinest_mpi'
except ImportError:
pass
```

You probably have an import error. Try:

```
python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'
mpiexec -np 2 python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'
```

**Comment by kssiobr** [comment]
Yes. It is always returning 1.

-bash-4.2$ python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'
1
-bash-4.2$ mpiexec -np 2 python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'
1
1

**Comment by JohannesBuchner** [comment]
Maybe switch MPI implementation.

**Comment by JohannesBuchner** [comment]
https://stackoverflow.com/questions/29264640/mpiexec-and-python-mpi4py-gives-rank-0-and-size-1

**Comment by kssiobr** [comment]
Thanks a lot! I switched to another mpi that is installed on the cluster and it worked.

-bash-4.2$ mpiexec.hydra -n 8 python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'
8
8
8
8
8
8
8
8

----

Now I'm finally running pymultinest in 32 cpus, and it is working fine.
Thanks again!

Best regards,

Cassio Pigozzo
