### ISSUE TITLE
PyPolyChord development

### ISSUE THREAD

**Issue by raphaelshirley** [JohannesBuchner/PyMultiNest#111]
Dear @JohannesBuchner,

I have been writing some code depending on MultiNest to compare models of images. I am very quickly running into speed issues so would like to test PyPolyChord to see how it is improves speeds in high dimensional problems. 

Do you plan to develop the PyPolychord wrapper? If no do you have an hints about how I might develop it to mirror the functionality of MultiNest?

Many thanks,

Raphael Shirley.

**Comment by JohannesBuchner** [comment]
Doesn't polychord already come with a python wrapper?

**Comment by raphaelshirley** [comment]
Possibly, if so sorry about that. I just saw a package here so presumed not. Thanks.
