### ISSUE TITLE
Multinest starting multiple times in single run

### ISSUE THREAD

**Issue by teja781** [JohannesBuchner/PyMultiNest#112]
Hello,

I have installed multinest_v3.10 and pymultinest_v2.6 on my ubuntu machine running 18.04. I have a python code with my prior and log-likelihood defined and at the end pymultinest.run(...). 
I used the command 
`mpirun -np 2 python my_python_code.py`
but it seems like the code is running twice instead of on two processors as is evident from the output which looks like this.

 

> *****************************************************
>  MultiNest v3.10
>  Copyright Farhan Feroz & Mike Hobson
>  Release Jul 2015
> 
>  no. of live points = 5000
>  dimensionality =    5
>  *****************************************************
>  Starting MultiNest
>  generating live points
>  *****************************************************
>  MultiNest v3.10
>  Copyright Farhan Feroz & Mike Hobson
>  Release Jul 2015
> 
>  no. of live points = 5000
>  dimensionality =    5
>  *****************************************************
>  Starting MultiNest
>  generating live points
>  live points generated, starting sampling
> Acceptance Rate:                        1.000000
> Replacements:                               5050
> Total Samples:                              5050
> Nested Sampling ln(Z):            **************
>  live points generated, starting sampling
> Acceptance Rate:                        1.000000
> Replacements:                               5050
> Total Samples:                              5050
> Nested Sampling ln(Z):            **************

Any one else facing this behavior or have any pointers to fix it? Appreciate any help I can get!!

Thanks

**Comment by kmaylor** [comment]
I've run into this issue as well. On one machine which had multiple versions of mpi installed I was able to get it to run using
mpiexec.mpich -np 2 python pythoncode.py

**Comment by JohannesBuchner** [comment]
Make sure you installed mpi4py.

**Comment by nmovshov** [comment]
I ran into the same issue after **uninstalling** `mpi4py`. With `mpi4py` installed I can't run `pymultinest` at all. If `init_MPI=False` (the default) I get the usual
`Attempting to use an MPI routine before initializing MPICH`
and with `init_MPI=True` I get cryptic errors from mpich itself.

I am doing all this in a clean conda environment. Starting with python 3.6 I call
`conda install -c conda-forge pymultinest`
and it gets all the dependencies _except_ `mpi4py` for some reason.

**Comment by nmovshov** [comment]
@kmaylor Good idea using a different version of mpiexec, sadly I still can't find a good match. Different cryptic errors depending on which mpi command is used.

Total wild guess but is it possible that conda is installing incompatible versions of mpi4py and mpich by default? For example, the current version of mpich, from either the system or from `conda install mpich` is 3.2. But if you need mpi4py then conda insists on also installing mpich2 HYDRA build 1.4.1p1. 

Obviously I'm grasping at straws here :/ If anyone has other ideas I'd be grateful.

**Comment by JohannesBuchner** [comment]
A really clean conda definitely works, as demonstrated by the travis build tests: https://travis-ci.org/JohannesBuchner/PyMultiNest/branches
Configuration and installation commands here: https://github.com/JohannesBuchner/PyMultiNest/blob/master/.travis.yml 
Without mpi4py it will not load the right library (multinest_mpi.so).

**Comment by nmovshov** [comment]
@JohannesBuchner thanks I will try these links!

**Comment by nmovshov** [comment]
Solved. Looking at the travis build script gave me the crucial hint. For future searches by Conda users here are the two important points:

1. Install mpi4py with
`pip install mpi4py`
and **not** with
`conda install mpi4py`
Not only do they install different versions of mpi4py, but the conda command also installs dependencies which override, in the conda environment, your `mpicc` and `mpiexec` versions/implementations. In theory that's a very good idea but in practice the implicitly installed versions don't work with MultiNest.

2. Do not install PyMultNest with
`conda install -c conda-forge pymutlinest`
Instead get it from this repo and run `python setup.py install` in the conda environment.

**Comment by JohannesBuchner** [comment]
Thanks!
