### ISSUE TITLE
Installing PyMultinest without mpi?

### ISSUE THREAD

**Issue by t-ferreira** [JohannesBuchner/PyMultiNest#113]
I have been trying to install and run PyMultinest on NERSC with no luck.

The installation works, but when I try to import pymultinest, I get the following error messages:

Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......:  PMI2 init failed: 1 
Aborted (core dumped)

These error messages appear when I try to install using pip and also conda install -c conda-forge pymultinest. When I use the latter for the installation, I notice that it also installs these two packages:
    mpi:                           1.0-mpich                           conda-forge
    mpich:                       3.2.1-h26a2512_4               conda-forge

NERSC uses mpi4py and I think that perhaps this is what is creating the error messages. Is there a way to force PyMultinest to use mpi4py? Or, perhaps, can I install pymultinest without mpi?

**Comment by JohannesBuchner** [comment]
If you uninstall mpi4py, pymultinest will not use it. 

Are you running python with mpiexec?

If you simply run 
$ mpiexec -np 3 python -c 'from mpi4py import MPI'
you should probably get the same error, without pymultinest.

**Comment by JohannesBuchner** [comment]
I am closing this, but please reopen if you still have this issue.

**Comment by am610** [comment]
so the solution is not straightforward, 
I will just copy the codes I applied, 

I created a conda python 2 environemnt

then loaded the required modules (this is vital to avoid NERSC conflicts)

then did a fresh installation of all the softwares (class, multinest, Pymultinest, Monte Python) 

Export the paths
should work now 

```
module unload gcc
module unload PrgEnv-gnu 
module load PrgEnv-gnu
module load cmake
module unload craype-hugepages2M

conda create -n py2 python=2.7 -y
source activate py2 

conda install numpy scipy cython matplotlib -y 

#class
cd $SCRATCH
git clone https://github.com/lesgourg/class_public
cd class_public
CC=$(which cc) make -j 8
cd python
CC=$(which cc) python setup.py build 

#multinest
cd $SCRATCH
git clone https://github.com/JohannesBuchner/MultiNest.git
cd MultiNest/build/
cmake .. -DCMAKE_Fortran_COMPILER=$(which ftn)
make
export LD_LIBRARY_PATH=$SCRATCH/MultiNest/lib/:$LD_LIBRARY_PATH 

#pymultinest
cd $SCRATCH
git clone http://github.com/JohannesBuchner/PyMultiNest
cd PyMultiNest
python setup.py install 

#nersc-specific mpi4py
MPICC="cc -shared" pip install --no-binary=mpi4py mpi4py

#montepython
cd $SCRATCH
git clone https://github.com/brinckmann/montepython_public
cd montepython_public
export PATH=$SCRATCH/montepython_public/montepython:$PATH 
```

Now this will not work on a login node,  so to test (as a job) 

`salloc -N 1 -t 30 -C haswell -q interactive 
srun python -c "import pymultinest"
`

this works for me.
