### ISSUE TITLE
ERROR:   Could not load MultiNest library "libmultinest.so" (it's in my LD_LIBRARY_PATH!)

### ISSUE THREAD

**Issue by ycp21** [JohannesBuchner/PyMultiNest#114]
Hi Johannes,

I'm trying to install PyMultiNest on a Red Hat EL7 system.  I have installed MultiNest and can run the examples, and have put the path to the library in my LD_LIBRARY_PATH.  Ie:

[reinyv@rhel-52d39r2 PyMultiNest]$ echo $LD_LIBRARY_PATH
/home/reinyv/software/MultiNest/lib/
[reinyv@rhel-52d39r2 PyMultiNest]$ ls /home/reinyv/software/MultiNest/lib/libmultinest.so*
/home/reinyv/software/MultiNest/lib/libmultinest.so
/home/reinyv/software/MultiNest/lib/libmultinest.so.3.10

And yet...

[reinyv@rhel-52d39r2 PyMultiNest]$ python -c 'import pymultinest'

ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

Do you have any idea what might be going wrong here?

Thanks a lot,
Yvette

**Comment by JohannesBuchner** [comment]
Did you use export?

> export LD_LIBRARY_PATH=/home/reinyv/software/MultiNest/lib/

**Comment by ycp21** [comment]
Hi Johannes, thanks for getting back to me!  Yes:

[reinyv@rhel-52d39r2 chains]$ export LD_LIBRARY_PATH=/home/reinyv/software/MultiNest/lib/
[reinyv@rhel-52d39r2 chains]$ ls /home/reinyv/software/MultiNest/lib/libmultinest.so
/home/reinyv/software/MultiNest/lib/libmultinest.so
[reinyv@rhel-52d39r2 chains]$ python -c 'import pymultinest'
ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

**Comment by ycp21** [comment]
Ok, I think I have sort of worked this out.  My python version was defaulting to a version that came with my CASA installation (https://casa.nrao.edu/) rather than the actual system version, and for some reason that CASA python version seems to refuse to accept the LD_LIBRARY_PATH variable.  If I force using the system python version it then works.  This is clearly nothing to do with PyMultiNest itself but maybe this will be useful to any other radio astronomers using it!

**Comment by JohannesBuchner** [comment]
OK, glad it is sorted.

**Comment by Senku02** [comment]
Hi,

I had a similar issue. I am working on Ubuntu 20.04 LTS. PyMultiNest is up and running, libmultinest.so has also been built - this was confirmed after running the demo programs which worked perfectly fine. However, I ran some imports on Jupyter, which I will mention below:

from petitRADTRANS import Radtrans
import numpy as np
%matplotlib inline

import matplotlib.pyplot as plt

import os
from IPython.display import display
import ipywidgets as widgets

from petitRADTRANS import Radtrans
from petitRADTRANS.retrieval import Retrieval,RetrievalConfig



The error I received was the same as the one OP came across:

ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

I am attaching the complete error along with this post as well. It'd be amazing if you could let me know what's going on here.

Thanks a lot!
Giri

The error:

[error.odt](https://github.com/JohannesBuchner/PyMultiNest/files/9020017/error.odt)

**Comment by ymkuan** [comment]
> Hi,
> 
> I am facing a similar issue. I am working on Ubuntu 20.04 LTS. PyMultiNest is up and running, libmultinest.so has also been built - this was confirmed after running the demo programs which worked perfectly fine. However, I ran some imports on Jupyter, which I will mention below:
> 
> from petitRADTRANS import Radtrans import numpy as np %matplotlib inline
> 
> import matplotlib.pyplot as plt
> 
> import os from IPython.display import display import ipywidgets as widgets
> 
> from petitRADTRANS import Radtrans from petitRADTRANS.retrieval import Retrieval,RetrievalConfig
> 
> The error I received was the same as the one OP came across:
> 
> ERROR: Could not load MultiNest library "libmultinest.so" ERROR: You have to build it first, ERROR: and point the LD_LIBRARY_PATH environment variable to it! ERROR: manual: http://johannesbuchner.github.com/PyMultiNest/install.html
> 
> ERROR: Could not load MultiNest library: libmultinest.so ERROR: You have to build MultiNest, ERROR: and point the LD_LIBRARY_PATH environment variable to it! ERROR: manual: http://johannesbuchner.github.com/PyMultiNest/install.html
> 
> problem: libmultinest.so: cannot open shared object file: No such file or directory
> 
> I am attaching the complete error along with this post as well. It'd be amazing if you could let me know what's going on here.
> 
> Thanks a lot! Giri
> 
> The error:
> 
> [error.odt](https://github.com/JohannesBuchner/PyMultiNest/files/9020017/error.odt)

Now I have the same problem as you, and the error is exactly the same.

 Meanwhile, I have also checked your attachment, and our error description is the same. So, did you solve the problem?  

Thanks!!!!!

**Comment by JohannesBuchner** [comment]
LD_LIBRARY_PATH needs to point to the path holding the library.

Then check that [ctypes](https://docs.python.org/3/library/ctypes.html) succeeds loading the library:

```
from ctypes import cdll
cdll.LoadLibrary('libmultinest')
```

**Comment by Sanketk2** [comment]
> LD_LIBRARY_PATH needs to point to the path holding the library.
> 
> Then check that [ctypes](https://docs.python.org/3/library/ctypes.html) succeeds loading the library:
> 
> ```
> from ctypes import cdll
> cdll.LoadLibrary('libmultinest.so')
> ```

I am having the same issue and cdll.LoadLibrary('libmultinest.so') gives:

"OSError: libmultinest.so: cannot open shared object file: No such file or directory"

I've followed the steps on the installation page and have done the exporting

"'export LD_LIBRARY_PATH=$HOME/sanke/MG5_aMC_v2_9_12/MultiNest/lib:$HOME/sanke/MG5_aMC_v2_9_12/cuba/:$LD_LIBRARY_PATH' >> ~/.bashrc"

I am using Ubuntu 22.04.1 LTS and Python 2.7

When I do "import pymultinest" I get: 

"ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory"

I've done multiple different tries, please help!

**Comment by giridharan-sankar** [comment]
I do not remember the exact steps I did, but I directed LD_LIBRARY_PATH as a permanent environment variable in my Linux system, which somehow made it work. [This might help](https://phoenixnap.com/kb/linux-set-environment-variable).

**Comment by Sanketk2** [comment]
> I do not remember the exact steps I did, but I directed LD_LIBRARY_PATH as a permanent environment variable in my Linux system, which somehow made it work. [This might help](https://phoenixnap.com/kb/linux-set-environment-variable).

Thanks, but I think that's what I have with my command "export .." with a  >> ~/.bashrc in the end

**Comment by Sanketk2** [comment]
@JohannesBuchner is there a way around this? Please let me know

**Comment by JohannesBuchner** [comment]
Please show your variable content  (echo $LD_LIBRARY_PATH )
You did restart your shell after adding to .bashrc?

**Comment by JohannesBuchner** [comment]
This cannot work as written:
"'export LD_LIBRARY_PATH=$HOME/sanke/MG5_aMC_v2_9_12/MultiNest/lib:$HOME/sanke/MG5_aMC_v2_9_12/cuba/:$LD_LIBRARY_PATH' >> ~/.bashrc"

**Comment by Sanketk2** [comment]
> Please show your variable content (echo $LD_LIBRARY_PATH ) You did restart your shell after adding to .bashrc?

I get -> /home/sanke/MG5_aMC_v2_9_12/MultiNest/lib/

**Comment by Sanketk2** [comment]
> This cannot work as written: "'export LD_LIBRARY_PATH=$HOME/sanke/MG5_aMC_v2_9_12/MultiNest/lib:$HOME/sanke/MG5_aMC_v2_9_12/cuba/:$LD_LIBRARY_PATH' >> ~/.bashrc"

I see, what would be the right way to do it? 

Thanks

**Comment by JohannesBuchner** [comment]
I think you need a echo in front (or simply open ~/.bashrc in an editor). Then reload the shell.
