### ISSUE TITLE
Output files basename too long

### ISSUE THREAD

**Issue by GregoryAshton** [JohannesBuchner/PyMultiNest#115]
If the `outputfiles_basename` is too long, the saved output (from multinest) is misnamed causing errors at the analysis stage (which are not obvious where they are arising from).

To be specific, if `outputfiles_basename` has a length of 78 or more, then the string `outputfiles_basename + "post_equal_weights.dat" has a length greater than 100. When, in multinest (https://github.com/JohannesBuchner/MultiNest/blob/master/src/posterior.F90#L42) this is stored as the variable `postfile4`, it is truncated to 100 characters. The result is that the post equal weights are stored in a file
`MY_VERY_VERY_VERY......VERY_LONG_BASENAME/post_equ`

As a result when trying to run the analysis and pointing the code to a file "post_equal_weights.dat", it fails since the filename is malformed.

While 100 may seem long, when working on a computing cluster where absolute path names are often required, one quickly runs into this issue.

Would it be possible to increase the maximum to 1000? I note that this is really a change in multinest, but since there is no issue tracker there and we solely use the `pymultinest` interface it made sense to raise the issue here.

Alternatively, if an error where raised if the input `outputfiles_basename` is too long, that would also be enough to stop people getting confused as to what happened.

PS: Thanks for the awesome module though!

**Comment by JohannesBuchner** [comment]
As you say, this is a MultiNest problem, not pymultinest.

IIRC, MultiNest recently did increase the length in their last release. I have not adopted their release, because it would break backwards compatibility with older MultiNest version (pymultinest would not be able to work with both new and old MultiNest versions). Maybe you could test that though, perhaps ctypes makes it accidentally backwards compatible.

I could imagine raising a warning in pymultinest.

Common workarounds include entering the directory (cd or os.chdir), or creating a symlink.

**Comment by GregoryAshton** [comment]
Okay thanks Johannes, I'll look into it.

**Comment by Jammy2211** [comment]
Hi Gregory,

We encounter this problem a few months ago, and went down the symlink route to address the issue. Our github repository is below - you want to checkout the autolens/autofit module.
https://github.com/Jammy2211/PyAutoLens

You should be able to adapt our non_linear module to get MultiNest running without character limits - feel free to contact me (and my co developer) on help on how to do this if its still a major issue for you :) - it certainly was for us!

@JohannesBuchner you are correct the new version of MultiNest addresses this issue (the character limit is raised from 100 to 1000). As you say, updating PyMultiNest is probably too risky given BC, but a raise Error would be greatly appreciated, as it took us a while to realise why our output disappeared when our directory names got too long! (In fact, we actually put this raise Error in our code ourselves until we sorted a symlink :P)

**Comment by JohannesBuchner** [comment]
closing this because #107 is similar and will discuss there.
