### ISSUE TITLE
Unable to build cuba shared library on Mac OSX

### ISSUE THREAD

**Issue by mariabenitocst** [JohannesBuchner/PyMultiNest#117]
Following the steps to build the cuba shared library, I got an error after typing "./makesharedlib.sh".
The problem comes from the file  __.SYMDEF SORTED which is not found, although this file is within the cuba folder. 
Any idea of how can I solve this problem?
Thanks!

**Comment by JohannesBuchner** [comment]
Did you use the cuba from my repo?

**Comment by mariabenitocst** [comment]
Yes. 
I have tried to manually specify in the makesharedlib.sh file the line where __.SYMDEF SORTED is called. I have done this in the following way:
gcc -shared -Wall "__.SYMDEF SORTED" [...]

Now, the error is 
ld: warning: ignoring file __.SYMDEF SORTED, file was built for unsupported file format ( 0x80 0x01 0x00 0x00 0xDC 0x00 0x00 0x00 0x38 0x35 0x0C 0x00 0xEA 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): __.SYMDEF SORTED

:(

**Comment by JohannesBuchner** [comment]
Of course, ".SYMDEF SORTED" is not a file.

What does `$ ar xv libcuba.a |sed 's/x - //g` give?

**Comment by mariabenitocst** [comment]
It gives me the following output:
__.SYMDEF SORTED
Vegas.o
Vegas_.o
llVegas.o
llVegas_.o
Suave.o
Suave_.o
llSuave.o
llSuave_.o
Divonne.o
Divonne_.o
llDivonne.o
llDivonne_.o
Cuhre.o
Cuhre_.o
llCuhre.o
llCuhre_.o
Fork.o
Fork_.o
Global.o
Global_.o
Data.o
[19:00:

**Comment by JohannesBuchner** [comment]
This is an issue for https://github.com/JohannesBuchner/cuba, not pymultinest. Please open an issue there. A pull request could simple grep out "` __.SYMDEF SORTED__`", i.e. change::

`FILES=$(ar xv libcuba.a |sed 's/x - //g')`

to 

`FILES=$(ar xv libcuba.a |sed 's/x - //g'|grep -v ' __\.SYMDEF SORTED__')`
