### ISSUE TITLE
Nested Sampling ln(Z)

### ISSUE THREAD

**Issue by s144117** [JohannesBuchner/PyMultiNest#118]
Hi
I have installed pyMultiNest v2.6 on a Ubuntu machine and ran the example provided in v1.0 documentation without a problem. Specifically referring to "Gaussian Emission Lines".

Later I changed the code, by which I mean implemented my own model, prior and likelihood function. I kept it very simple by using the old Gaussian log-likelihood function, a uniform prior and three model parameters.
Below is an output example. max_iter = 200 to reduce amount of output.
I do not understand  what "**************" is, after "ln(Z):".
I presume that something is wrong and not just that the number is to long to be written.
Nevertheless, the code runs to completion.
When trying to acces the posterior information an error occurs.

Since the only difference between the toy example "Gaussian Emmision Lines" is the Nested Sampling Ln(Z): ************** I believe that is where the error originates.
Have you encountered this before and can explain my mistake to me?

Thanks in advance
Michael

*****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    3
*****************************************************
 Starting MultiNest
 generating live points
 live points generated, starting sampling
Acceptance Rate:                        0.982533
Replacements:                                450
Total Samples:                               458
Nested Sampling ln(Z):            **************
Importance Nested Sampling ln(Z): ************** +/-  0.998908
Acceptance Rate:                        0.961538
Replacements:                                500
Total Samples:                               520
Nested Sampling ln(Z):            **************
Importance Nested Sampling ln(Z): ************** +/-  0.999038
Acceptance Rate:                        0.936968
Replacements:                                550
Total Samples:                               587
Nested Sampling ln(Z):            **************
Importance Nested Sampling ln(Z): ************** +/-  0.999148
Acceptance Rate:                        0.904977
Replacements:                                600
Total Samples:                               663
Nested Sampling ln(Z):            **************
Importance Nested Sampling ln(Z): ************** +/-  0.999246
 ln(ev)=  -97001280740355568.      +/-                       NaN
 Total Likelihood Evaluations:          663
 Sampling finished. Exiting MultiNest

  analysing data from outAlfven/.txt
Traceback (most recent call last):
  File "/home/micmad/Documents/synthesis/uniformPriorGauss/uniform.py", line 188, in <module>
    a_lnZ = a.get_stats()['global evidence']
  File "/pack/python_3.5.2/lib/python3.5/site-packages/pymultinest/analyse.py", line 127, in get_stats
    for i in range(2, posterior.shape[1]):
IndexError: tuple index out of range

**Comment by s144117** [comment]
--> Update

I did find that the data file in outAlfven/.txt only has one line:
0.100000000000000000E+01    0.388312715797505040E+17   -0.350089622388591379E+05  -0.406537154415572586E+05   -0.345883499491576549E+04

At this point I am not sure what these values are. I guess 1st is a counter and 3rd-5th is model parameters since the size fits. As for the second value I am not sure.

When running the "Gaussian Emssion Line" example the file contains ~6300 lines which is of the same order at the total replacements.

Nested Sampling ln(Z): **************
Importance Nested Sampling ln(Z): ************** +/- 0.999246
ln(ev)= -97001280740355568. +/- NaN

must in some way be responsible for the lack of data lines

**Comment by JohannesBuchner** [comment]
Double-check that you implemented your likelihood function correctly. Probably all values returned have a odd value. A print in the likelihood function will help you.

**Comment by s144117** [comment]
Thank you for the answer.
You are absolutely correct. I have spent most of the time today troubleshooting.
It turned out that a numpy function went amok when its input had shape (x, 1) instead of (x,).

It is now operating much faster and after enough iterations Nested Sampling ln(Z) does begin to show a value.

I due have another problem, my model parameters exhibit an error identical to itself. But this might also be something to do with my specific problem.

  parameters:
    Gauss_1        51832 +- 51832
    Gauss_2        -3139 +- 3139
    Gauss_3        -680 +- 680
