### ISSUE TITLE
Iteratively reducing the amount of active points

### ISSUE THREAD

**Issue by s144117** [JohannesBuchner/PyMultiNest#122]
Hi

I have successful implemented my own problem in a low dimension (8D) version.
Afterwards I increased the dimensions (15D) and found that the acceptance rate had reduce to 5% over a period of 7 hours.
I concluded that it might be due to a low amount of initial live points (2000).  Since the dimensionality had increased so much they were now to widely spread.
I tried one more time, increasing the live points to 50000. The process was much slower,  as expected.
Recalling a MultiNest article from 2009 by Feroz, Hobson and Bridges I remembered there was a way to reduce the number of active points.
`N_i=N_(i-1)-N_min*((dZ_(i-1)-dZ_i)/(dZ_i-tol))`
I have looked in the run.py file, but see no option to define N_min. How would one go about doing this?

Thanks in advance
Michael

**Comment by JohannesBuchner** [comment]
I don't think this feature is implemented in multinest. 

More live points means more iterations, as less volume is sliced away with each live point removal.

5% is a pretty good acceptance rate for a 15d problem.

**Comment by s144117** [comment]
I haven't thought about the amount of live points increasing iterations. Then reducing the amount of live points is desired. But am I wrong in think i need to increase the amount with increasing dimensionality? As my domain of high probability becomes respectively smaller compared to the entire prior space, "Curse of Dimensionality" and all that.
How do you decide what is a good acceptance rate for a given x dimensional problem?
