### ISSUE TITLE
Acceptance rate

### ISSUE THREAD

**Issue by s144117** [JohannesBuchner/PyMultiNest#123]
Hi

I was running the Gaussian spectral line example. The results are good, but I am wondering why the acceptance rate continues to drop. It ends up with 60% which is good, but never goes up. 
I expect it to initially drop and but when isolating the individual modes the iso-likelihood approximations should be quite good resulting in a increase in acceptance rate.

When increasing to higher dimensions (15-30) the acceptance rate ends up being around 3% resulting a huge amount of likelihood evaluations. Keep in mind this is a unimodal example with uniform prior and Gaussian likelihood.

Thanks in advance
Michael

**Comment by JohannesBuchner** [comment]
Multinest calculates the acceptance rate as number of iterations (accepted points) / number of likelihood evaluations. It is not a moving average or something like that. 

To understand why the acceptance rate is low requires to understand the nature of high-dimensional spaces. Spoken poorly, when the volume is small, there is more space to fall off in the wrong direction.
