### ISSUE TITLE
Inefficient MPI

### ISSUE THREAD

**Issue by cmcgrud1** [JohannesBuchner/PyMultiNest#126]
Dear Dr. Buchner, 
I am trying to test PyMultiNest with MPI on my mac using the pymultinest_test.py code with 4 variables (x,y,z,w instead of just x and y). I changed line 22 of pymultinest_test.py to **parameters = ["x", "y", "z", "w"]**
and changed 
**if __name__ == '__main__':
	test()**
to 
**if __name__ == '__main__':
	startT = time.time()
	test()
	print ('run time', time.time() - startT)**

so I could compare the runtime with and without parallelization. When I run pymultinest_test.py without mpi as _python pymultinest_test.py_ I get 

 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    4
 *****************************************************
 ln(ev)=   230.42758549096862      +/-  0.16448496216635844     
 Total Likelihood Evaluations:       107912
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 230.4 +- 0.2

parameter values:
              x : 15.930 +- 7.087
              y : 16.461 +- 6.595
              z : 15.116 +- 6.765
              w : 15.650 +- 8.198
run time 21.8117887974

However, when I run it with mpi as _mpiexec -n 2 python pymultinest_test.py_ I get 
 
MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    4
 *****************************************************
 ln(ev)=   230.38349427375880      +/-  0.16448417068760010     
 Total Likelihood Evaluations:       119633
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt
  analysing data from chains/3-.txt

evidence: 230.4 +- 0.2

parameter values:
              x : 16.255 +- 7.555
              y : 14.997 +- 7.847
              z : 17.809 +- 6.998
              w : 16.319 +- 8.444
run time 24.6305458546

evidence: 230.4 +- 0.2

parameter values:
              x : 16.255 +- 7.555
              y : 14.997 +- 7.847
              z : 17.809 +- 6.998
              w : 16.319 +- 8.444
run time 24.6354830265

So from this I see that 1) mpi is slower than without parallelization 2) the results with mpi is different from the results without mpi, and 3) the results with mpi are printed multiple times. I wouldn't expect any of these things to happen. I'd expect the regular method and the multicore method to produce the same results but the multicore method to be faster because it is splitting the computation time amongst 2 cores. Additionally, seeing the mpi run printing the results multiple times makes me think that something is going wrong in my mpi. Instead of using multiple cores to run different calculations at the same time, it seems it is just using multiple cores to run the whole thing twice, separately. 
I also did similar test done in the closed issue #110:
_python -c 'from pymultinest.run import libname; print(libname)'
mpiexec -np 2 python -c 'from pymultinest.run import libname; print(libname)'_
and get 'libmultinest.dylib' for the first and 'libmultinest_mpi.dylib' for the second. Also when I type _mpiexec -np 2 python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())'_ I get 
2
2
Thus, I don't think there is a problem initializing multicore (activating mpi), but rather how the cores are utilized. Do you have any insight on this? 
I'd appreciate anything you have to say on this. 
Thank you, 
-Chima

**Comment by JohannesBuchner** [comment]
I think mpi4py is not installed, you are not running multinest with MPI enabled.

**Comment by nmovshov** [comment]
@cmcgrud1 are you using a conda python distribution? If so try the suggestions at the end of this [thread](https://github.com/JohannesBuchner/PyMultiNest/issues/112#issuecomment-452116017).

When working correctly, at least with simple test problems and up to 12 cores, I find that run time scales very efficiently with available cpus. Basically doubling the number of cores approximately halves the run time.

**Comment by cmcgrud1** [comment]
@JohannesBuchner thank you for responding so quickly. So I think I had mpi4py installed via pip as @nmovshov suggested. I checked this by doing _conda uninstall mpi4py_ and got _PackagesNotFoundError: The following packages are missing from the target environment:
   mpi4py_, implying mpi4py wasn't conda installed. Then I did _pip install mpi4py_ and was given _Requirement already satisfied: mpi4py in /home/mcgruderc/anaconda2/lib/python2.7/site-packages (3.0.0)_  meaning it was installled using pip. To further insure mpi4py is properly installed I did _import mpi4py_ in ipython with no problem. Also PyMultiNest was installed from the repo as @nmovshov suggested. But I still getting the same results, 1) that mpi isn't faster than without mpi, 2)the results with mpi are different from that without parallelization, and 3) mpi prints the results multiple times. Additionally, I tried this all on a linux machine with python version 2.7.13 and got the same 3 problems I got on my mac.

**Comment by nmovshov** [comment]
@cmcgrud1 Next thing I would try is to run in a clean conda environment so you know there are no conflicts.
```
conda create pymn
conda activate pymn
conda install numpy scipy matplotlib
pip install mpi4py
```
Now, build the multinest libraries. If you already built them, delete the multinest dir download again and run cmake and make again! Make sure you are running cmake and make _in the activated conda environment pymn_. This will hopefully cause the mpicc command to use the version under conda, which is the version that mpi4py will be using later.

If you still get the same behavior then next thing to try is a different test program.

good luck

**Comment by nmovshov** [comment]
I forgot above to also stress to build `pymultinest` from the git repo, also while in the activated new conda environment.

**Comment by JohannesBuchner** [comment]
Hmm, actually, since you get the line "MultiNest v3.10" only once, and also from your mpi4py tests it seems to be working ok. 

There is some overhead of course with launching and syncing the programs, and the analysis part (after pymultinest.run) is run on each MPI process, which may be a waste too, especially on the same FS. You can put a `if MPI.COMM_WORLD.Get_rank() != 0: sys.exit()` in there. The way distributed random numbers work can make MPI/non-MPI outcomes slightly different, even if you set the same seed.

**Comment by JohannesBuchner** [comment]
My suggestion is unlikely to help, but was intended for the user script (just after call to solve).

In any case, I don't think this is a pymultinest bug. You can try reporting upstream why multinest behaves how it does. It may also have to do with python startup time before MPI starts. You can also try making a C program instead.
