### ISSUE TITLE
dlopen(libmultinest.dylib, 6): image not found

### ISSUE THREAD

**Issue by reneheller** [JohannesBuchner/PyMultiNest#127]
In order to run PyMultiNest I need to install MultiNest first. So I'm following the instructions to install MultiNest as per

`git clone https://github.com/JohannesBuchner/MultiNest`
`cd MultiNest/build`
`cmake ..`
`make`

but

`MultiNest/build`
https://github.com/JohannesBuchner/MultiNest/tree/master/build

is empty. So I can't install MultiNest and PyMultiNest. Any help would be appreciated.

**Comment by JohannesBuchner** [comment]
Follow the instructions.

**Comment by JohannesBuchner** [comment]
If you get any error messages, please open a new issue.
