### ISSUE TITLE
CLANG can't find __.SYMDEF SORTED

### ISSUE THREAD

**Issue by matteobiagetti** [JohannesBuchner/PyMultiNest#128]
I've been trying to install the PyCuba, following your instructions here https://johannesbuchner.github.io/PyMultiNest/install. I'm stuck once I get to running the makesharedlibrary.sh script. The error I get reads

clang: error: no such file or directory: '__.SYMDEF'
clang: error: no such file or directory: 'SORTED'

I'm running on a MacAir OSX 10.14.3. I successfully managed to run the installation on a Linux machine, so I'm assuming this is a Mac-related problem. I know that Mac has issues with shared libraries, but I wasn't expecting to run into problems at this stage. Do you know what is this about?

Thanks for your help!

**Comment by JohannesBuchner** [comment]
I haven't used clang. Try using gcc? 

I hope you can report back when you solved this.

**Comment by matteobiagetti** [comment]
Thanks for your quick response.

The mac OSX links gcc to clang automatically, that is why it was using by default clang (see e.g. here https://stackoverflow.com/questions/19535422/os-x-10-9-gcc-links-to-clang). 

However, even when I make sure that gcc is used (installed through homebrew as suggested by the link above), I get the same error, but with gcc:

gcc-8: error: __.SYMDEF: No such file or directory
gcc-8: error: SORTED: No such file or directory

Therefore I guess the problem wasn't clang after all. Not sure what is going on here, any suggestion is appreciated.

**Comment by gioacchinowang** [comment]
check this:
https://www.gnu.org/software/make/manual/html_node/Archive-Symbols.html

just a guess, something related to 'ranlib' ?

**Comment by matteobiagetti** [comment]
> check this: https://www.gnu.org/software/make/manual/html_node/Archive-Symbols.html just a guess, something related to 'ranlib' ?

Thanks for the suggestion! I digged into this and found the fix here https://stackoverflow.com/questions/19398742/os-x-linker-unable-to-find-symbols-from-a-c-file-which-only-contains-variables

The fix is simple: I added -c to the command in the makefile where ranlib runs:

$(LIB): $(LIB)(Vegas.o)     $(LIB)(Vegas_.o)     \
	$(LIB)(llVegas.o)   $(LIB)(llVegas_.o)   \
	$(LIB)(Suave.o)     $(LIB)(Suave_.o)     \
	$(LIB)(llSuave.o)   $(LIB)(llSuave_.o)   \
	$(LIB)(Divonne.o)   $(LIB)(Divonne_.o)   \
	$(LIB)(llDivonne.o) $(LIB)(llDivonne_.o) \
	$(LIB)(Cuhre.o)     $(LIB)(Cuhre_.o)     \
	$(LIB)(llCuhre.o)   $(LIB)(llCuhre_.o)   \
	$(LIB)(Fork.o)      $(LIB)(Fork_.o)      \
	$(LIB)(Global.o)    $(LIB)(Global_.o)    \
	$(LIB)(Data.o)
	-$(RANLIB) -c $(LIB)

Now, why did it really work, it is beyond me. Now it runs fine with this warning

ld: warning: ignoring file __.SYMDEF, file was built for unsupported file format ( 0x20 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x20 0x05 0x00 0x00 0x07 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): __.SYMDEF

In place of the error message. So it might not be the perfect fix.
Nevertheless, the library was generated and I copied it ( libcuba.so ) into the anaconda3 folder and successfully run the pycuba_demo.py.

**Comment by JohannesBuchner** [comment]
Hmm, I am not sure if I can add -c to the script, because it is an invalid option in Linux.

I hope it is ok to close this and hope users find the solution in this issue. If someone has a better fix, please let me know.

**Comment by Lucia-Fonseca** [comment]
Big thank you!

> > check this: https://www.gnu.org/software/make/manual/html_node/Archive-Symbols.html just a guess, something related to 'ranlib' ?
> 
> Thanks for the suggestion! I digged into this and found the fix here https://stackoverflow.com/questions/19398742/os-x-linker-unable-to-find-symbols-from-a-c-file-which-only-contains-variables
> 
> The fix is simple: I added -c to the command in the makefile where ranlib runs:
> 
> $(LIB): $(LIB)(Vegas.o) $(LIB)(Vegas_.o) 
> $(LIB)(llVegas.o) $(LIB)(llVegas_.o) 
> $(LIB)(Suave.o) $(LIB)(Suave_.o) 
> $(LIB)(llSuave.o) $(LIB)(llSuave_.o) 
> $(LIB)(Divonne.o) $(LIB)(Divonne_.o) 
> $(LIB)(llDivonne.o) $(LIB)(llDivonne_.o) 
> $(LIB)(Cuhre.o) $(LIB)(Cuhre_.o) 
> $(LIB)(llCuhre.o) $(LIB)(llCuhre_.o) 
> $(LIB)(Fork.o) $(LIB)(Fork_.o) 
> $(LIB)(Global.o) $(LIB)(Global_.o) 
> $(LIB)(Data.o)
> -$(RANLIB) -c $(LIB)
> 
> Now, why did it really work, it is beyond me. Now it runs fine with this warning
> 
> ld: warning: ignoring file __.SYMDEF, file was built for unsupported file format ( 0x20 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x20 0x05 0x00 0x00 0x07 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): __.SYMDEF
> 
> In place of the error message. So it might not be the perfect fix.
> Nevertheless, the library was generated and I copied it ( libcuba.so ) into the anaconda3 folder and successfully run the pycuba_demo.py.

**Comment by LaundryPizza03** [comment]
On my macOS system, the above fix created a new issue:
```
making libcuba.so
gcc -shared -Wall __.SYMDEF Vegas.o Vegas_.o llVegas.o llVegas_.o Suave.o Suave_.o llSuave.o llSuave_.o Divonne.o Divonne_.o llDivonne.o llDivonne_.o Cuhre.o Cuhre_.o llCuhre.o llCuhre_.o Fork.o Fork_.o Global.o Global_.o Data.o -lm -o libcuba.so
ld: unknown file type in '__.SYMDEF'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
