### ISSUE TITLE
The kernel appears to have died.

### ISSUE THREAD

**Issue by GuillermoGRG** [JohannesBuchner/PyMultiNest#129]
Hello. 
I am trying to do the Example 1: "One-dimensional multi-modal problem" on Jupyter notebook and when I get to this part

`pymultinest.run(loglike, prior, n_params, outputfiles_basename='out/',resume = False, verbose = True)`

the kernel restarts. I've installed everything with Anaconda and now I don't know what to do. Thanks!

**Comment by JohannesBuchner** [comment]
Is there any error message or output?

**Comment by GuillermoGRG** [comment]
Jupyter notebook does not show any error message, so I decided to use the terminal and this was the output 

> Starting MultiNest
At line 233 of file /home/conda/feedstock_root/build_artifacts/multinest_1532619403329/work/src/nested.F90 (unit = 55)
Fortran runtime error: Cannot open file 'out/ev.dat': No such file or directory

**Comment by JohannesBuchner** [comment]
does the folder out/ exist?

**Comment by GuillermoGRG** [comment]
Yes! The problem was route. It is perfectly working now. Thank you for your help.

**Comment by JohannesBuchner** [comment]
Not sure what "route" means, but glad it is solved.

**Comment by ftoyarzun** [comment]
I'm having the same error! What did you do?

**Comment by JohannesBuchner** [comment]
You need to look at the stdout (not in the notebook). Unfortunately the fortran code does not do well with printing in such a way that python can forward it, and the developers of MultiNest chose to terminate the process upon error. In the case of calling from python via PyMultiNest, that means, the python kernel dies.

If you want nested sampling with a pretty interface for jupyter notebooks, try ultranest.

**Comment by ViralTheorem** [comment]
Hello! Having the same error as above running it in terminal - in my case the ev.dat file is isochrones_mist_400_ev.dat and the file does exist in the relevant directory. It says as mentioned above that at line 233: no resume file found ... fortran runtime error ... no such file or directory __-I didn't understand how @GuillermoGRG fixed the problem is there any chance you could explain how to resolve it. Many thanks

**Comment by ViralTheorem** [comment]
Have now resolved it

**Comment by jaburico** [comment]
Hello, I had the same problem. How can you resolved it?

**Comment by JohannesBuchner** [comment]
@jaburico, see https://github.com/JohannesBuchner/PyMultiNest/issues/129#issuecomment-713077389

**Comment by jaburico** [comment]
Hey, I solved my problem... I only needed to create a folder called "out" in the same location where my code is running... After this, all worked properly... Thanks
