### ISSUE TITLE
Maximum no of MPI size

### ISSUE THREAD

**Issue by antolonappan** [JohannesBuchner/PyMultiNest#130]
Hi Buchner,

I was wondering if there is an optimal no of maximum MPI size I can use with multinest.
For example, If I am having 4-dimensional parameter space and I am using 400 live_points; whether 100 mpi_size is fine?

If there exists such an optimal size how we can select regarding live points or parameter space.

Thanks and Regards,
Anto.

**Comment by JohannesBuchner** [comment]
Do you mean the number of processes set with mpiexec -np?

**Comment by antolonappan** [comment]
yes

**Comment by JohannesBuchner** [comment]
Set it to the number of cores available. If you have 8 cpu cores, set it to 8. The way Multinest parallelises the likelihood evaluation makes this pretty independent of the live points or dimensionality of the problem.

**Comment by antolonappan** [comment]
Thanks for the reply. Currently I am running a 9 dimensional model with 400 live_points. For that I am using 200 cores. I was doubtful whether  the mpi communication consumes some time, if I am using more cores.

**Comment by JohannesBuchner** [comment]
It probably depends on the efficiencies you are seeing. If they are very low (<0.1%), then you may be fine with many cores. I think you have to play around with the parameters. I would be interested to hear about your experience.

**Comment by antolonappan** [comment]
Initially, I was running with 200 cores, Now I moved it to 320. For 8 dimensional problem with 400 live points computation time changed from 15 min to 11 min.

**Comment by T0T4R4** [comment]
Can we run pymultinest under Jupyter so that it uses all our cores ? Or is it locked to a single core because of Jupyter ?

**Comment by antolonappan** [comment]
Assuming you have installed 'ipyparallel' in conda environment.
From the Jupyter notebook home page, you can start an IPython Cluster.
After it started successfully, you can open a notebook and use cell magic "%%px" in the cell which you want to execute parallelly
