### ISSUE TITLE
Error 126 on pymultinest

### ISSUE THREAD

**Issue by esadri21** [JohannesBuchner/PyMultiNest#131]
I would like to use Pymultinest on windows but after installing by pip and then importing I came across this error:
problem: [WinError 126] The specified module could not be found

any help?

**Comment by JohannesBuchner** [comment]
Have you already installed multinest? I am not sure multinest even supports windows. Install Linux.

**Comment by esadri21** [comment]
Well, in the Multineste documentation it is stated that it is easy [https://johannesbuchner.github.io/PyMultiNest/install.html#installing-the-python-module](url)
using 

> pip install pymultinest

**Comment by JohannesBuchner** [comment]
This is the pymultinest documentation stating that installing pymultinest is easy. But you also need to install multinest, the Fortran library, see section 2.

**Comment by esadri21** [comment]
Ah, I thought when a instruction talking about PIP install... this is a task for windows even next steps. thank you
