### ISSUE TITLE
gfortran library linkage issue (I hope it's minor)

### ISSUE THREAD

**Issue by JVSeidel** [JohannesBuchner/PyMultiNest#132]
Dear Johannes,

I really hope this is a minor issue but I have been trying to solve this for days without avail. I'd appreciate any help.

I have previously installed PyMultiNest successfully on my Mac, but with the upgrade to Mojave I had to reinstall some packages (this seems to be a known issue with Mojave and anaconda).

I had to reinstall gcc using homebrew, I had to reinstall numpy, scipy etc using pip and I had to reinstall python3 with anaconda (because I had to reinstall anaconda). 

My MultiNest and PyMultiNest packages remained as before. However when trying to execute my reliable, old code, I got this:

problem: dlopen(libmultinest.dylib, 6): Library not loaded: /usr/local/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/julias/MultiNest/lib/libmultinest.dylib
  Reason: image not found

I use the following setup:
which gcc
/usr/bin/gcc
which gfortran
/anaconda3/bin/gfortran

I'm at a total loss what to do. I tried to uninstall and reinstall gcc and gfortran separately through different means (homebrew vs anaconda etc) various times, but nothing seems to move me past this error message. I'm in desperate need to get this working again for my PhD, any lead is much appreciated.

Many thanks for your help!

-Julia

**Comment by JohannesBuchner** [comment]
Did you rebuild multinest with cmake after making the changes?

**Comment by JohannesBuchner** [comment]
Clearing the build cache might help there too, by emptying the multinest build directory.

**Comment by JVSeidel** [comment]
Dear Johannes,

thanks a bunch, that was exactly what I needed. 

For anyone running PyMultiNest and upgrading to Mojave:

The error occuring is a "Segmentationfault: 11", due to a linking problem after the Mac upgrade with gfortran. 

Solution:
Uninstall anaconda, uninstall python, uninstall MultiNest
Then, reinstall anaconda, reinstall python, reinstall gcc, reinstall cmake
When reinstalling MultiNest, the path to gfortran has to be set by hand in the make file.

Then everything starts working again.

Really appreciate the nudge in the right direction!

-Julia

**Comment by JohannesBuchner** [comment]
Good! :-)
