### ISSUE TITLE
How to set path and build a MultiNest on googe colaboratory

### ISSUE THREAD

**Issue by YongMac** [JohannesBuchner/PyMultiNest#133]
I am trying to import MultinNest and Cuba package in google colaboratory.

The installation instruction of these package in Linux is:

```
git clone https://github.com/JohannesBuchner/MultiNest
cd MultiNest/build
cmake ..
make
```

But it cannot be accepted in google colaboratory.

I would like to do import pymultinest but we should install MultiNest first to be able to use it. so we should use git clone and then build it. I am not familiar with building the packages etc.

I use git clone and after that I use import MultiNest and I have no error but once I write import pymultinest:

```
ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html
```

I have tried different ways but I could not manage to do it.

**Comment by JohannesBuchner** [comment]
Maybe you can install the conda version @giacomov made a while back

https://github.com/conda-forge/pymultinest-feedstock

**Comment by YongMac** [comment]
Thank you. Well, does this way install the MultiNest and Cuba package along with Pymultinest?

**Comment by JohannesBuchner** [comment]
Multinest only.

**Comment by YongMac** [comment]
ok. I will try it then

**Comment by JohannesBuchner** [comment]
see also #206

**Comment by MohammadRih** [comment]
Hi,
I'm trying to do it as well but it won't work and I still have a problem loading the shared library "libmultinest.so"
I tried conda method but in my case, conda didn't work in colab.
Do you have any suggestions for me, please?

**Comment by giacomov** [comment]
Please follow these instructions to get to a working conda/mamba in Colab

**Comment by JohannesBuchner** [comment]
You can also try UltraNest instead,  https://johannesbuchner.github.io/UltraNest/

**Comment by MohammadRih** [comment]
> You can also try UltraNest instead, https://johannesbuchner.github.io/UltraNest/

Thanks for these information but in my situation, I use bagpipes code that work with just pymultinest and I don't know that if l install ultramultinest this code can work with it or not.
What's your opinion about it?!

**Comment by MohammadRih** [comment]
> Please follow these instructions to get to a working conda/mamba in Colab: https://stackoverflow.com/a/75239829/19942876

It works perfectly for me and I thank you.
