### ISSUE TITLE
Evidence is a function of prior

### ISSUE THREAD

**Issue by williamjouse** [JohannesBuchner/PyMultiNest#134]
how can I get the values of evidence as a function of the prior? Is it possible to get?

**Comment by JohannesBuchner** [comment]
Please explain a bit more what you mean. The evidence is an integral over the parameter space.

**Comment by williamjouse** [comment]
In some works (https://arxiv.org/abs/1805.09900, https://arxiv.org/abs/1811.01821) they get a relation between the bayes factor and the prior width. They do not use Multinest. Is this possible with Multinest?

**Comment by JohannesBuchner** [comment]
Some suggestions I can think of: you could either

1. rerun with different prior ranges.
2. if you are trimming or expanding the volume far away from the dominating peak, you can find an analytic formula Z'=Z / V * V' where V' is the new volume.
3. You could do a wide Multinest run and then use the posterior weights to resample (importance sampling), i.e., give points outside the new volume weight 0 and sum up the new Z.
