### ISSUE TITLE
Could not

### ISSUE THREAD

**Issue by ehs21** [JohannesBuchner/PyMultiNest#135]
Hi

I have exactly done what the construction was saying.
I installed "pip install PyMultinest" It was ok.
then I did https://johannesbuchner.github.io/PyMultiNest/install
git clone https://github.com/JohannesBuchner/MultiNest cd MultiNest/build cmake .. make

it was Ok too. But once I impoerted pymultinest, I ran to problem. Why this should be so hard to install just one library?

`python3 -c 'import pymultinest'

ERROR: Could not load MultiNest library "libmultinest.so"
ERROR: You have to build it first,
ERROR: and point the LD_LIBRARY_PATH environment variable to it!
ERROR: manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR: Could not load MultiNest library: libmultinest.so
ERROR: You have to build MultiNest,
ERROR: and point the LD_LIBRARY_PATH environment variable to it!
ERROR: manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory`
Please Help. I am confused.

**Comment by JohannesBuchner** [comment]
Hi @ehs21, 

you have to set the environment variable LD_LIBRARY_PATH to the path containing the multinest library.
For example:

```
export LD_LIBRARY_PATH=/home/user/Downloads/MultiNest/lib/
python3 -c 'import pymultinest'
```

It is hard because multinest is written in fortran by someone else. I only made the pymultinest front-end.

**Comment by ehs21** [comment]
Thank you, It was a problem with mu Ubuntu. It is corrected now.

I hope I can ask my questions here to learn the multinest. If I can please tell me.
Could I ask my questions step by step If I could not understand them?


 I would like to ask my first question.
I am doing the first example [http://johannesbuchner.github.io/pymultinest-tutorial/example1.html#your-task](url) it needs "ev.dat" file. I could not find in the code, where the code calls for "ev.dat" file. I just copied and pasted the "ev.dat" file from first "demo example" into "out" folder and the example1 code ran correctly, but which part of code is calling the "ev.dat"?

another question is plotting the outputs

> python multinest_marginals.py chains/3-

what is it? how to export a file with multinest_marginals.py name?
in both demo and example1 is talking about it. But I did not understand the instruction.

Thank you

**Comment by JohannesBuchner** [comment]
multinest creates this and other files with the prefix specified through the outputfiles_basename parameter

**Comment by JohannesBuchner** [comment]
Did you run the python code? If you get an error message, copy it here.

**Comment by heerakb91** [comment]
Hi,

I am getting the exact same error when I try to run my code that imports PyMultinest and runs it.

$ mpiexec -n 2 python3 abc.py 

ERROR:   Could not load MultiNest library "libmultinest_mpi.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest_mpi.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest_mpi.so: cannot open shared object file: No such file or directory

ERROR:   Could not load MultiNest library "libmultinest_mpi.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest_mpi.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest_mpi.so: cannot open shared object file: No such file or directory
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52110,1],0]
  Exit code:    1

The MultiNest library is on my LD_LIBRARY PATH, I have it included in .bashrc and .profile as well.

$ echo $LD_LIBRARY_PATH
/home/heerak/MultiNest/lib

$ ls /home/heerak/MultiNest/lib
libmultinest.a  libmultinest.so  libmultinest.so.3.10

I am even more confused by the fact that, 

$ python3 -c 'import pymultinest' 

does not throw up any error.

Could you please help?

I believe I built and installed mpi4py correctly.

$ which mpiexec
/usr/bin/mpiexec
$ which mpicc
/usr/bin/mpicc

**Comment by JohannesBuchner** [comment]
Multinest did not build libmultinest_mpi.so. Probably it did not detect the mpi compiler?

**Comment by heerakb91** [comment]
Okay it could be because I built Multinest BEFORE I installed MPI. The issue was solved once I removed Multinest and then built it again, now with MPI already installed. My code is running fine. Thanks.
