### ISSUE TITLE
Is it normal for pymultinest to spawn 35 subprocesses irrespective of the number of processes run?

### ISSUE THREAD

**Issue by 3rico** [JohannesBuchner/PyMultiNest#137]
When i run pymultinest with n processors where n can be any number depending on the computer, it eventually slows down to almost a stand still. I checked the processes running using htop and noticed child processes spawn by one of the pymultinest processes. 

The number of child processes spawn was exactly 35 irrespective of the number of processors specified, and it is at this time that pymultienst slowed down. 

Is this normal?

**Comment by JohannesBuchner** [comment]
Perhaps you are using another library that uses OpenMP parallelisation internally and tries to use all processors. Try controlling it with the environment variable OMP_NUM_THREADS=1.

**Comment by JohannesBuchner** [comment]
To answer directly to your question: no.
