### ISSUE TITLE
Not working normally with MPI on CentOS 7

### ISSUE THREAD

**Issue by heerakb91** [JohannesBuchner/PyMultiNest#138]
I am trying to run a Pymultinest implementation that is parallelized in n cores on a CentOS 7 server.
Everything was running fine except there was an emergency shutdown and the server had to be rebooted. Post this incident, running the code with
$mpiexec -n n python abc.py 
does not parallelize anything. It is not throwing any error messages either. It just runs the identical Multinest algo on n different nodes independent of each other and giving me n sets of output data.
I had checked that my code was getting parallelized quite rigorously before and have checked with equal rigor that it is not parallelizing now. Any ideas where the issue is originating? I havent got a clue since there are absolutely no errors being shown. Since there are no MPI-related errors thrown and its running copies of the same code on n nodes I assume that there's nothing wrong with the MPI installation or implementation. It seems that somehow pyMultinest can't figure out what to do with it. I could remove Multinest and build it again but I am interested to know why this happened, or else it might happen again.

**Comment by JohannesBuchner** [comment]
Probably mpi4py is not correctly installed.

Make sure `mpiexec -np 4 python -c 'import mpi4py'` works.

**Comment by heerakb91** [comment]
Yes. 
mpiexec -np 4 python -c 'import mpi4py' 
works fine. No errors.

**Comment by JohannesBuchner** [comment]
Maybe try making a script containing the first 10 lines of https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/run.py . Make sure libname should become 'libmultinest_mpi'. 

You can also try switching the MPI implementation.

**Comment by heerakb91** [comment]
Okay I ran the first ten lines 
```
from __future__ import absolute_import, unicode_literals, print_function
from ctypes import cdll
import sys, os

libname = 'libmultinest'
try: # detect if run through mpiexec/mpirun
	from mpi4py import MPI
	if MPI.COMM_WORLD.Get_size() > 1: # need parallel capabilities
		libname = 'libmultinest_mpi'
except ImportError as e:
	if 'PMIX_RANK' in os.environ:
		print("Not using MPI because import mpi4py failed: '%s'. To debug, run python -c 'import mpi4py'.", e)
```

by 

$mpiexec -np 4 python test.py

it prints nothing. No errors or messages.

I also ran a few tests of my own. I ran a simple Hello World routine,

```
from mpi4py import MPI

comm=MPI.COMM_WORLD
rank=comm.Get_rank()

if rank==0:
	print ('Hello World from process', rank)
elif rank==1:
	print ('Hello World from process', rank)
elif rank==2:
	print ('Hello World from process', rank)
elif rank==3:
	print ('Hello World from process', rank)
```

the output when i run this on 4 nodes is:
Hello World from process 0
Hello World from process 0
Hello World from process 0
Hello World from process 0

Clearly something's wrong here. Just to test the basic MPI I also ran a test code in C from [https://github.com/wesleykendall/mpitutorial/blob/gh-pages/tutorials/mpi-hello-world/code/mpi_hello_world.c]

using 

$mpicc mpi_test.c -o mpitest
$mpiexec -np 4 ./mpitest

which gives the output,

Hello world from processor localhost.localdomain, rank 1 out of 4 processors
Hello world from processor localhost.localdomain, rank 0 out of 4 processors
Hello world from processor localhost.localdomain, rank 2 out of 4 processors
Hello world from processor localhost.localdomain, rank 3 out of 4 processors

So here it's working fine. Perhaps something wrong with mpi4py?

**Comment by JohannesBuchner** [comment]
I think so. Double-check how mpi4py was installed & what MPI you use. You can also check in with the person who runs that cluster. I had success sometimes switching the MPI implementation (for example, openmpi vs mpich).

**Comment by heerakb91** [comment]
Well mpich doesnt work on centOS or any RHEL in fact because of a bug, as informed here,
[](https://bitbucket.org/mpi4py/mpi4py/src/4ecc63a71d63/DESCRIPTION.rst?at=master)
we need to change the PYTHONPATH to go around it. So openmpi is a safe bet.

I checked with the person who runs the cluster and he also informed me about the same thing. He too suggested going about trying to remove and the reinstall mpi4py from scratch. I will try to do that and see if things fall back into place. Perhaps that'll help in getting to the bottom of the issue.
