### ISSUE TITLE
pycuba userdata problems

### ISSUE THREAD

**Issue by steven-murray** [JohannesBuchner/PyMultiNest#14]
Hi there,

I'm really only interested in pycuba from this package (in fact I just isolated it and wrote a simple setup script for just pycuba). On a side note -- do you mind if I tinker with it and create a fork with the isolated pycuba? I think this would be useful to people (well at least me), even if they don't care so much about the rest of the MCMC stuff.

Anyway, to the problem... I haven't dealt with ctypes before. I see how to use the calls to Cuhre etc. (which are exemplified in your demo). When I run demo() it works fine, when i strip it down just to use the basic Cuhre one it works fine. But when I try to use the "userdata" variable I get errors. I'm not really sure how to define the userdata. I've tried just using
```python
Cuhre(Integrand,ndim=3,userdata = 0.5)
```
 in the call to Cuhre, and in the Integrand, having
```python
...
 b = userdata
...
```
but it complains with 
```
ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: Don't know how to convert parameter 4
```
I was wondering if I had to make userdata a ctype variable before chucking it into the call to Cuhre()? And what type must I make it?

Cheers,
Steven

**Comment by JohannesBuchner** [comment]
If you or someone else seriously needs this functionality in python, please re-open.

**Comment by farnikn** [comment]
Hi Johannes, 

I'm dealing with the same problem by putting my extra variables into a global variable, but I was wondering if there is any update for this issue and passing the userdata as a ctype variable?

Best,
Farnik

**Comment by JohannesBuchner** [comment]
I don't really see the need to mangle it into C and then back out. You don't even need a global variable either, you can use a class with a method that accesses the classes attributes, or you could create a function that returns a function.

**Comment by steven-murray** [comment]
I agree with the approach @JohannesBuchner suggests -- wrapped functions or classes would be much easier.

**Comment by farnikn** [comment]
Yeah I got it, thanks a lot!
