### ISSUE TITLE
restart earlier?

### ISSUE THREAD

**Issue by qyx268** [JohannesBuchner/PyMultiNest#140]
There was an error during the run time when the disk was full. Therefore, files that should be outputted and would be needed for calculating the likelihood were not created properly, leading the program to crash and eventually MultiNest to crash as well.

I'd like to restart the sampler but this error has lead to some points being written into the output files with a log-evidence being some random number (e.g. 0.60821407-291). It also leads to wrong statistics in the stats and summary files (and potentially the IS files). Could you please help me figure out a way to restart MultiNest from an earlier time or tell me how to delete the parameter sets that have been affected by this error? I could delete those points with random log-evidence, but I'm not sure how to do it with the IS files. Thanks!

**Comment by JohannesBuchner** [comment]
Resuming from a broken multinest state is difficult, I think you need to adjust the resume.dat file carefully as well. Regarding IS, you can try turning off IS (importance_sampling=False). IS tends to under-estimate the uncertainties and the speed-up is usually small.

**Comment by qyx268** [comment]
Thanks for the follow-up. I'm going to set IS to false then. May I ask what you meant by adjust resume.dat carefully? I have the following as an example.

 F
        6030        8898           1        1600
   -0.115342802692509476E+02   -0.897317674491690020E+01
 T
   0
 T F     0        1600
    0.631732074795355314E-01   -0.115342802692509476E+02   -0.897317674491690020E+01

**Comment by JohannesBuchner** [comment]
I don't know how the format works. Keep a backup and try. If you have questions, ask the multinest developers.
