### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Hamza757** [JohannesBuchner/PyMultiNest#141]

**Comment by Hamza757** [comment]
Hi Johannes,
I tried to compile multinest by following the instruction in README file. But when I wrote cmake ( hamza@hamza-Lenovo-E50-80:~/MultiNest/build$ cmake ..), I got the following message: 

CMake Error at /home/hamza/anaconda2/lib/python2.7/site-packages/cmake/data/share/cmake-3.14/Modules/FindLAPACK.cmake:417 (message):
  A required library with LAPACK API not found.  Please specify library
  location.
Call Stack (most recent call first):
  src/CMakeLists.txt:31 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/hamza/MultiNest/build/CMakeFiles/CMakeOutput.log".
See also "/home/hamza/MultiNest/build/CMakeFiles/CMakeError.log".
 
Can you help me to solve this problem?

Thanks a lot,
Hamza

**Comment by JohannesBuchner** [comment]
You need to install lapack and blas (and potentially also the devel packages)

**Comment by JohannesBuchner** [comment]
https://johannesbuchner.github.io/PyMultiNest/install.html#prerequisites-for-building-the-libraries

**Comment by Hamza757** [comment]
Hi,
Thank you for help but I think i can't get lapack and devel packages using the command sudo apt-get install......., whent i tried to install it I got:
Package libatlas-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libatlas-base-dev:i386 libatlas-base-dev

E: Package 'libatlas-dev' has no installation candidate

**Comment by JohannesBuchner** [comment]
Try those replacements instead then.

**Comment by Hamza757** [comment]
Hi,
Thank you for respond. It does not work but I fixed by  following the steps in the link: https://www.assistedcoding.eu/2017/11/04/how-to-install-lapacke-ubuntu/
