### ISSUE TITLE
MPI issues with HPC use.

### ISSUE THREAD

**Issue by binnietom** [JohannesBuchner/PyMultiNest#143]
Hello, 

I've been getting the following error when trying to use mpi with pymultinest (with init_MPI=True).  The HPC people I've spoken to think its something to do with version of pymultinest compatibility with MPI but have not solved it yet. Please let me know if you have any ideas!  Thanks, Tom

[cli_0]: Command cmd=put kvsname=kvs_27157_0 key=sharedFilename[0] value=/dev/shm/mpich_shar_tmprE2c2q
 failed, reason='duplicate_keysharedFilename[0]'
Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(474).....: 
MPID_Init(190)............: channel initialization failed
MPIDI_CH3_Init(89)........: 
MPID_nem_init(272)........: 
MPIDI_CH3I_Seg_commit(337): PMI_KVS_Put returned -1
[mpiexec@r5i0n1] handle_pmi_cmd (./pm/pmiserv/pmiserv_cb.c:52): Unrecognized PMI command: abort | cleaning up processes
[mpiexec@r5i0n1] control_cb (./pm/pmiserv/pmiserv_cb.c:289): unable to process PMI command
[mpiexec@r5i0n1] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@r5i0n1] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:181): error waiting for event
[mpiexec@r5i0n1] main (./ui/mpich/mpiexec.c:405): process manager error waiting for completion

**Comment by JohannesBuchner** [comment]
You should not need to alter the pymultinest call. All you need to do is install mpi4py and run the program with mpiexec. 

Possibly related: https://github.com/JohannesBuchner/PyMultiNest/issues/105 https://github.com/JohannesBuchner/PyMultiNest/issues/100

**Comment by JohannesBuchner** [comment]
Please reopen if the issue still exists.

**Comment by binnietom** [comment]
> 

My apologies, I thought I had closed this. If I remember correctly I think it was a pip vs conda problem to do with the installation locations. Your previous comment was ideal. Thanks for chasing it up after so long!
