### ISSUE TITLE
MLE corresponds to a minima of the posterior?

### ISSUE THREAD

**Issue by heerakb91** [JohannesBuchner/PyMultiNest#144]
I am providing Pymultinest with a function to calculate LogLikelihood. I am running my code to estimate a single parameter. Priors are flat:
`def myprior(cube, ndim, nparams):
	cube[0]=cube[0]*0.01`
I wish to visualise the behaviour of the posterior probability.
Post run I am using the data in [root].txt to visualise the posteriors. Since I am estimating a single parameter, it is a 3-column datafile. I am plotting x:column 3 vs y:column 1, lets call it figure 1. This is consistently giving me a sharp dip at the centre of the posterior peak. When I check the corresponding [root]stats.dat file, the MAP corresponds to the maxima of figure 1 however the MLE corresponds to the minima of the sharp dip in figure 1.
Data in [root]stats.dat file :
```
Nested Sampling Global Log-Evidence           :   -0.447015887542048418E+02  +/-    0.310279498920825528E-01

Dim No.       Mean        Sigma
   1    0.403873711445441934E-04    0.174408435500198872E-04

Maximum Likelihood Parameters
Dim No.        Parameter
   1    0.447941944600608046E-04

MAP Parameters
Dim No.        Parameter
   1    0.259933471679687502E-04
```
What am I doing wrong?

**Comment by JohannesBuchner** [comment]
The documentation of the columns is in https://github.com/JohannesBuchner/multinest/

Specifically:
```
[root].txt
Compatable with getdist with 2+nPar columns. Columns have sample probability, -2*loglikehood, parameter values. 
Sample probability is the sample prior mass multiplied by its likelihood & normalized by the evidence.
```
You may find it easier to make a histogram of the first column of [root]post_equal_weights.dat , which corresponds to the posterior.

**Comment by JohannesBuchner** [comment]
Could you please include the figures here?

**Comment by heerakb91** [comment]
![plot-lkl](https://user-images.githubusercontent.com/52691968/64425340-0b69d580-d0c9-11e9-80f8-549977afe239.png)

![plot-post](https://user-images.githubusercontent.com/52691968/64425354-158bd400-d0c9-11e9-9a38-6a3d54b79b69.png)

In the first figure I am plotting 2nd column of [root].txt in the y-axis. In the second figure it is the 1st column. The 2nd column should give me -2*loglikelihood, the first column should give me the posterior probability for the particular parameter point given in 3rd column. Yet, the minima of second column (should correspond to max likelihood), corresponds to a minima and not the maxima of the first column.

The first column of the [root]post_equal_weights.dat gives the parameter points, according to the column documentation, and the second column of this file gives the corresponding loglikelihood for that parameter point. That is what I understood at least! 

You are saying that the histogram of the first column of the [root]post_equal_weights.dat gives me the posterior probability distribution?

**Comment by JohannesBuchner** [comment]
Yes.

**Comment by heerakb91** [comment]
Thank you for that information! But could you then let me know what does the data in [root].txt first column represent? Is it NOT the posterior probabilities for the corresponding sample points?

**Comment by JohannesBuchner** [comment]
If I remember correctly right now, I think those are the posterior weights of the points, but for a accurate plot you would need to make a weighted histogram (the density of points in some x range plays a role). You can also use the file to ask what fraction of the probabilities are within some range.
