### ISSUE TITLE
Accuracy of posteriors

### ISSUE THREAD

**Issue by srashtig** [JohannesBuchner/PyMultiNest#147]
I have 5 parameters, such that four of them are very sensitive to posterior of the fifth one.
Therefore, I need a better posterior accuracy on the fifth one. Right now what I am getting is though very near(9.99) to the injected value(10.0) but still the posterior histogram is not even covering the injected one, it is very narrow. 

Can changing pymultinest sampling parameters like, ztol etc. help me in getting there? If yes, what all parameters should I change.

**Comment by JohannesBuchner** [comment]
Try increasing the number of live points to 2000. Also be aware that credible intervals are not confidence intervals, and whether the posterior covers the input depends on the priors.

**Comment by srashtig** [comment]
Hi, I tried with, 400, 1000 and 2000 livepoints, the result doesn't seem to vary much after 1000 live points. For the fifth parameter, injected value is 10, and I am getting the best fit posterior as:
400 : 9.989
1000: 9.9957
2000: 9.9958
But still my problem of incorrect posteriors of other parameters persist with this much of error.

**Comment by JohannesBuchner** [comment]
Could you attach show corner plots of your posterior? (the multinest_marginals*.py scripts in PyMultiNest can help)

**Comment by JohannesBuchner** [comment]
You can also try evaluating the likelihood at the multinest MAP and at the input values. Maybe that will help you debug why the input values are not preferred by your likelihood.

**Comment by srashtig** [comment]
Here are the corner plots. Currently there is no noise in the injected signal, it is from the same model as the one used for evaluating likelihood.
The injection parameters are denoted by black  dashed line, and the best fit by blue in posterior plots.

injection parameters: array([23.82123207,  0.24793388, 10.        , 60.        ,  0.25      ])
[pymult_model_1.zip](https://github.com/JohannesBuchner/PyMultiNest/files/3751358/pymult_model_1.zip)

yes I also think that I should do likelihood computations around the injected values, that will tell me if there is any double peak in the system.

**Comment by srashtig** [comment]
Also, can you please tell me on how should I set evidence_tolerance, on changing it to 0.1 from 0.5, result seems to vary pretty much.

**Comment by JohannesBuchner** [comment]
Try getting the likelihood at the injected parameters:
` likelihood(np.array([23.82123207, 0.24793388, 10. , 60. , 0.25 ])) `
And compare it to the likelihood at the best fit:
` likelihood(np.array([22.3, 0.19, 9.993 , 28 , -0.49 ])) `
You would have to look at your data to see why the latter has a higher likelihood.

evidence_tolerance determines how long the integration should continue. 0.5 is usually enough; whether 0.1 can be reached also depends on the number of live points.

**Comment by srashtig** [comment]
this is what i get:
loglike(inj_params,5,5)
-2473.845418295771
loglike(best_fit,5,5)
-1936.6098172222808

**Comment by srashtig** [comment]
loglikelihood of far away points are of the order -1000
this tells that it should go to inj_param values, right?

**Comment by JohannesBuchner** [comment]
The loglikelihood value of the best_fit is higher, so preferred.

**Comment by srashtig** [comment]
Hi, the problems seems to be resolved now, the issue was that according to theory I should not have fix the other 6th parameter, varying the 5th one. Thank you so much for your help.

Also please confirm me on this, if I want more evidence accuracy, I should decrease the evidence_tolerance value, to say 0.1, but because of that posteriors accuracy will be effected and therefore I will need to increase the no. of live points too, right?

**Comment by JohannesBuchner** [comment]
decreasing evidence_tolerance will not worsen the posteriors accuracy, but merely integrate longer, and you cannot arbitrarily decrease evidence_tolerance, because the limited number of live points put a floor to it. So increasing the number of live points will help there.

If you want to do Bayesian model comparison with Bayes factors, you typically don't need to know Z to a factor better than 3, but going for 0.1 is doable.
