### ISSUE TITLE
gfortran version issue after Catalina update

### ISSUE THREAD

**Issue by carolinestraatman** [JohannesBuchner/PyMultiNest#151]
After updating my Mac to Catalina, I get an error running PyMultiNest: 
problem: dlopen(libmultinest.dylib, 6): Library not loaded: /opt/local/lib/libgcc/libgfortran.4.dylib
  Referenced from: /Users/caro/software/MultiNest/lib/libmultinest.3.10.dylib

Indeed the file /opt/local/lib/libgcc/libgfortran.4.dylib does not exist anymore. There seems to be a parallel issue with installing gcc8 through macports (gcc8 is currently not supported on Darwin). My unfortunately limited knowledge of these things gave me the idea of (re-)installing gcc4, but that leads to a gcc8 dependency and so I get stuck.

Have you/ anybody else had a similar issue?

Caroline

**Comment by JohannesBuchner** [comment]
Did you recompile MultiNest? Make sure you delete everything in the build/ folder before running cmake.

**Comment by carolinestraatman** [comment]
I wanted to re-install it, but there is no compiler: /opt/local/bin/gfortran is not a full path to an existing compiler tool.

Does recompiling multinest return to me the file I need to run multinest: /opt/local/lib/libgcc/libgfortran.4.dylib?

I installed gcc9 with macports, but there is no gfortran compiler anywhere on my computer. I can download an earlier standalone version from here (https://github.com/fxcoudert/gfortran-for-macOS/releases), but I don't think I'm supposed to, in any case should it be a version 4.X.X?

**Comment by JohannesBuchner** [comment]
You need to compile multinest so that it links against libraries you actually have. 

Have a look here:
https://stackoverflow.com/questions/51822999/installing-gfortran-via-macports-on-mac-os-high-sierra

**Comment by carolinestraatman** [comment]
So in the end I did get the standalone Mojave version of gfortran (even though it's not for Catalina). With that I managed to recompile, but pymultinest still gives the same error. If I look in /opt/local/lib/libgcc/...

libasan.5.dylib       libgcc_ext.10.5.dylib libgomp.1.dylib       libquadmath.0.dylib   libubsan.1.dylib
libatomic.1.dylib     libgcc_s.1.dylib      libitm.1.dylib        libssp.0.dylib
libgcc_ext.10.4.dylib libgfortran.5.dylib   libobjc-gnu.4.dylib   libstdc++.6.dylib

... are the files I have, but not libgfortran.4.dylib. Perhaps should I change a line in libmultinest.3.10.dylib?

**Comment by JohannesBuchner** [comment]
Delete libmultinest.dylib libmultinest.3.10.dylib and rebuild them. Make sure you are operating on the file being loaded by pymultinest (included in LD_LIBRARY_PATH or DYLIB_LIBRARY_PATH). A compiler will not produce a dylib library with a reference to a non-existing other library.

**Comment by carolinestraatman** [comment]
Thanks, Johannes, it's back!
I deleted the whole Multinest and downloaded and built it from scratch. I may have also forgotten the make after cmake earlier. Thanks for your help!
