### ISSUE TITLE
Mode death/loss and final reported results

### ISSUE THREAD

**Issue by caseylam** [JohannesBuchner/PyMultiNest#152]
I am trying to estimate parameters in a highly degenerate space. Sometimes when I run identical fitters in exactly the same way, I get different results (different maximum likelihood values for the parameters within the specified uncertainty ranges, and different global log evidences). I think the problem is due to modes "dying" or not being completely found, and this problem is somewhat ameliorated when I use more live points. I have also been making trace plots with dynesty (https://dynesty.readthedocs.io/en/latest/) to determine whether modes are disappearing. However, I cannot consistently determine when this is happening, other than running the identical fitter multiple times and seeing if the results differ. Is there a better way to identify this issue and figure out when the results are stable against mode death? (Or whether this is a different issue altogether?)

An example is attached as a PDF. The runs are all identical. In the trace plots, the red line indicates the maximum likelihood solution, while the dotted lines and numbers give the median and +/- 2 sigma values.
[multinest_github.pdf](https://github.com/JohannesBuchner/PyMultiNest/files/3870904/multinest_github.pdf)

**Comment by JohannesBuchner** [comment]
In general, if you have large scatter in the logZ outputs across multiple runs, this is a sign that multinest's assumptions (of ellipsoidal approximations) are breaking down. We analysed such a case in Appendix A.9. of https://arxiv.org/abs/1806.04683 . Also see this toy problem: https://arxiv.org/abs/1304.7808 
Basically, the ellipsoids can cut off too much of the parameter space and accidentally shrink the volume too much.

Multinest is splitting off runs when it discovers distinct modes, so it behaves differently than dynesty in that regard, although the ellipsoidal sampling is the same (modulo clustering parameter differences).

Your marginal posteriors don't look too horrible -- although I don't see the three modes here? A corner plot may be interesting. 

You can also give ultranest a shot. It uses a variation of RadFriends, which is designed to be more robust. https://johannesbuchner.github.io/UltraNest/ Plus, it has a hedgehog as a logo ;)

**Comment by caseylam** [comment]
Thanks for the links. Regarding Appendix A.9, there doesn't seem to be a way to know whether you'll have large scattering in logZ beforehand, the only way to find out is to just perform multiple runs. Is that correct?

I attached the PDF with corner plots. I also do not see three modes. I'm not sure why between these runs, the two smaller logZ modes match, while the largest logZ modes don't. Naively I would've though the larger logZ mode is easiest to find. Is the reason for this because of what you described, the ellipsoids shrinking the volume too much?

[multinest_github_corner.pdf](https://github.com/JohannesBuchner/PyMultiNest/files/3875795/multinest_github_corner.pdf)

**Comment by JohannesBuchner** [comment]
Correct.

I think so. The problem in the Beaujean & Caldwell paper is that the ellipsoids are split between modes, but each mode shrinks too fast because the distribution is heavy-tailed and not ellipsoidal.
