### ISSUE TITLE
Wrong order of output redirected to a file

### ISSUE THREAD

**Issue by rpoleski** [JohannesBuchner/PyMultiNest#153]
I'm having trouble with output produced by multinest when output is directed to a file. The order of output is messed up. Minimum example (slightly modified pymultinest_demo_minimal.py):

```
import pymultinest
import math, os
try: os.mkdir('chains')
except OSError: pass

def myprior(cube, ndim, nparams):
    for i in range(ndim):
        cube[i] = cube[i] * 10 * math.pi

def myloglike(cube, ndim, nparams):
    chi = 1.
    for i in range(ndim):
        chi *= math.cos(cube[i] / 2.)
    return math.pow(2. + chi, 5)

parameters = ["x", "y"]
n_params = len(parameters)
pymultinest.run(myloglike, myprior, n_params,
    resume=False, verbose =False)

print("XXX")
```

No redirecting of output produces expected result (i.e., "XXX" is at the end):

```
python x.py 
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   235.55853851166418      +/-  0.12632100556698039     
 Total Likelihood Evaluations:         5621
 Sampling finished. Exiting MultiNest
XXX
```

Redirecting to a file and printing it contest gives:

```
python x.py > x.out
cat x.out 
XXX
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 ln(ev)=   235.97349514483031      +/-  0.12299433984700701     
 Total Likelihood Evaluations:         5680
 Sampling finished. Exiting MultiNest
```

And "XXX" is at the top. I'm guessing that there is some problem with buffering, but I don't know how to correct it. If possible, I would like `pymultinest.run()` to not print any output at all. Any idea how to cope with this issue?

**Comment by JohannesBuchner** [comment]
Yes, fortran somehow has its own stdout buffering. I don't know how to flush that.

I think you cannot easily surpress MultiNest's output further, except perhaps by either making a separate process or by redirecting stdout. 

You could also try UltraNest if you have few parameters.

**Comment by rpoleski** [comment]
Ok, I did more digging and found the solutions that really works:

[https://stackoverflow.com/a/17954769](https://stackoverflow.com/a/17954769) - answers [this question](https://stackoverflow.com/questions/5081657/how-do-i-prevent-a-c-shared-library-to-print-on-stdout-in-python/17954769#17954769)
[https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/) (section "Redirecting with file descriptor duplication")
