### ISSUE TITLE
Merging multiple multinest runs

### ISSUE THREAD

**Issue by caseylam** [JohannesBuchner/PyMultiNest#154]
I have several identical PyMultiNest runs and was hoping to combine them together. Is there a way to merge multiple MultiNest runs? e.g. something like in Dynesty, as described [here](https://dynesty.readthedocs.io/en/latest/errors.html#unraveling-merging-runs) or [here](https://dynesty.readthedocs.io/en/latest/quickstart.html#combining-runs). I tried using Dynesty's implementation with my MultiNest results, but the information required is not output by Multinest, I believe (please correct me if I'm mistaken). Is there a simple way to do this in (Py)MultiNest, or is there implementation somewhere else? Thank you.

**Comment by JohannesBuchner** [comment]
You could concatenate the posteriors samples, and average the logZ estimates.

**Comment by caseylam** [comment]
The issue is some of the runs have very different logZ, like in #[152](https://github.com/JohannesBuchner/PyMultiNest/issues/152), in which case I'm not sure I can simply concatenate all the runs without any adjustment.

**Comment by JohannesBuchner** [comment]
If that is true, you should not trust the results from multi-ellipsoidal nested sampling. 

Even if the runs were correct, if the logZ are very different, the one with the highest logZ will likely dominate the result.

Have you tried UltraNest?
