### ISSUE TITLE
Marginalising over some free parameters

### ISSUE THREAD

**Issue by heerakb91** [JohannesBuchner/PyMultiNest#155]
Hi Johannes,

I have a likelihood function that takes 5 free parameters. I would like to get posteriors for each parameter while marginalising over the rest 4. Is this possible within PyMultinest or must I modify my likelihood function for each run?

**Comment by JohannesBuchner** [comment]
Let PyMultinest run on all parameters. Make a histogram of the posterior points only for the parameters of interest. That marginalises the other parameters away.

**Comment by heerakb91** [comment]
Thank you!
