### ISSUE TITLE
number of samples

### ISSUE THREAD

**Issue by nfbouche** [JohannesBuchner/PyMultiNest#156]
when running pymultinest with max_iter set to !=0, e.g 500, (or 1000 or ...) it returns only one sample:

{
In [25]: a=pm.Analyzer(12,outputfiles_basename='pymulti/out')                                                                                                
  analysing data from pymulti/out.txt

In [26]: a.get_data().shape                                                                                                                                  
Out[26]: (1, 14)
}

**Comment by JohannesBuchner** [comment]
I am not sure if the number of live points counts towards max_iter. In any case, if you do this, the highest likelihood sample probably has all the weight -- you will not get a reasonably sampled posterior.

**Comment by nfbouche** [comment]
my particular data and model make the Multinest approach very slow. 
My objectif was to stop after a fixed number of iterations, look at the posterior, and continue if necessary? 
Otherwise, how to optimize convergence?

**Comment by JohannesBuchner** [comment]
You can reduce the number of live points (e.g. to 200), and increase the number of CPUs used (with MPI). If you want to sacrifice correctness, you can use the constant efficiency mode.

**Comment by nfbouche** [comment]
I see. Thanks!
