### ISSUE TITLE
(Py)MultiNest results machine dependent: changed with gfortran 7

### ISSUE THREAD

**Issue by fzeiser** [JohannesBuchner/PyMultiNest#159]
I just wanted to document that the results of running (Py)MultiNest depend on the compiler version used to compile MultiNest. This might not come as a huge surprise, but it did take me some time to find out why my results where inconsistent on two different machines.

**Steps to reproduce:**
- Install `gfortran` versions:
  - GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  - GNU Fortran (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
  - GNU Fortran (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
  - GNU Fortran (Ubuntu 4.8.5-4ubuntu8) 4.8.5
- Compile MultiNest with one of these compilers (at a time), eg. using update alternatives. Check which compiler was used/found by cmake in the first line: `-- The Fortran compiler identification is GNU 7.5.0`
- Run `pymultinest_demo.py` with following modifications to the `solve` function:
  - `seed=123` to seed the calculation
  - `resume=False` to do the calculation again; or delete the `chains` folder in between the runs.

The results for all calculations prior to `gfortran-7` were:
```
Nested Sampling ln(Z):                235.532137
Importance Nested Sampling ln(Z):     235.839008 +/-  0.043903
 ln(ev)=   235.88169733395719      +/-  0.12317238895743753     
 Total Likelihood Evaluations:         5567
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 235.9 +- 0.1
```

vs. the result with `gfortran-7` is
```
Nested Sampling ln(Z):                235.695631
Importance Nested Sampling ln(Z):     235.778396 +/-  0.048475
 ln(ev)=   236.05299437911228      +/-  0.12250958344752762     
 Total Likelihood Evaluations:         5662
 Sampling finished. Exiting MultiNest
  analysing data from chains/3-.txt

evidence: 236.1 +- 0.1
```
 It's not a huge change, but in the example I calculated it was definitively visible. In addition, if one plots a random selection of, say 3, samples, of course these three samples will be totally different for these cases.

My take on this: I pinned the gfortran version in the Dockerfile I use for the calculations.

**Comment by JohannesBuchner** [comment]
Thanks for documenting this. I am not sure what is causing this, possibly a change in the prng behaviour. In any case, I think this is a Multinest issue, not a PyMultiNest one.
