### ISSUE TITLE
Distinguishing data and equal weighted posterior

### ISSUE THREAD

**Issue by ghkareem** [JohannesBuchner/PyMultiNest#162]
Hi, I am trying to figure out what is the difference between the Analyzer.get_data() array and Analyzer.get_equal_weighted_posterior() array. It appears that the get_equal_weighted_posterior has one less column than get_data; surely it should be retrieving 2 less columns (i.e. remove the evidence and error, leaving the number of parameters in the problem)? How does one interpret this? Thanks

**Comment by JohannesBuchner** [comment]
The equal_weighted_posterior also has the likelihood as the last column.

**Comment by ghkareem** [comment]
Great, thanks for confirming that, Johannes -  I figured it out ~10mins after posting hence closed this post 👍
