### ISSUE TITLE
Auxilliary functions to sample

### ISSUE THREAD

**Issue by awsteiner** [JohannesBuchner/PyMultiNest#165]
Is there a way to specified additional functions which need to be sampled along with the likelihood? For example, when using a likelihood function f(p1,p2,...), is there a way to specify another function (or functions), g(p1,p2,...), which will be sampled according to the probability described by f? Is there a way to compute, say, <g> = integral (f*g) / integral(f) along with the posteriors for the parameters p_i? We've looked at the docs and the issues and haven't found a way to do this. Thank you.

**Comment by JohannesBuchner** [comment]
I think the easiest is to do it by looping through the posterior samples and evaluating the function at those points.

**Comment by JohannesBuchner** [comment]
done for example here: https://johannesbuchner.github.io/UltraNest/example-sine-line.html#Plot-the-fit

**Comment by awsteiner** [comment]
Thank you for your quick response. This works. My only remaining objection is that will effectively double our required run time, because these auxillary functions are evaluated in order to compute the likelihood anyway. I didn't know about ultranest so we'll check that out as well. And no, I can't spell auxiliary.

**Comment by JohannesBuchner** [comment]
I am not sure about your problem, but I don't think it will double the run time, because you will not need to evaluate all rejected points. If you use only the equally weighted samples, it is typically a very small fraction of the dead points.

**Comment by awsteiner** [comment]
Oh yes of course that's correct. Thank you for your help.

**Comment by rpoleski** [comment]
I think what @awsteiner asks for is a build-in feature. I've used it in Fortran implementation, but never in pyMultiNest. I've just looked at [the documentation](https://johannesbuchner.github.io/PyMultiNest/pymultinest_run.html): it is possible to set `n_dims` and `n_params` to different values and you can add these additional parameters (like g(p1, p2, ...)) either in loglikelihood or prior (I don't remember in which one). The Fortran implementation was using `n_params` in all output including calculating posterior statistics for these additional parameters.
