### ISSUE TITLE
error with Cmake script

### ISSUE THREAD

**Issue by svaverbe** [JohannesBuchner/PyMultiNest#168]
Hi,

Using the latest version of Cmake(3.18.2.post1), I get the following error while running Cmake in \build; 

-- A library with LAPACK API found.
-- Detected gfortran, adding -ffree-line-length-none compiler flag.
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
-- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS)
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND)
-- MPI not found, only non-MPI MultiNest libraries will be built.
CMake Error at src/example_eggbox_C/CMakeLists.txt:7 (FIND_LIBRARY):
  Could not find m using the following names:

-- Configuring incomplete, errors occurred!
See also "/mnt/d/WD/MGAB/mgab-v1134/Multinest/bUILD/CMakeFiles/CMakeOutput.log".
See also "/mnt/d/WD/MGAB/mgab-v1134/Multinest/bUILD/CMakeFiles/CMakeError.log".

This bug is similar to an issue already reported here, but Cmake does not give any clue what is really missing.  I have installed all necessary numerical libraries as far as I can see, 

Siegfried Vanaverbeke

**Comment by JohannesBuchner** [comment]
This is a MultiNest issue, not a PyMultiNest issue. 

Be sure to empty the build folder first.

Have a look at the error logs.

I think it is looking for libm, which is the C math library. Odd that it does not find it.

**Comment by svaverbe** [comment]
After cleaning the build directory and starting again, everything seems to be fine now.

Siegfried
