### ISSUE TITLE
Obtain modal posteriors?

### ISSUE THREAD

**Issue by AlecThomson** [JohannesBuchner/PyMultiNest#169]
Hi there,

I've been using multinest for a model-fitting problem with:
```
multimodal = True
```
To obtain seperate out different modes in the posteriors, and correctly cluster the parameter values. We've also been using the posteriors directly to get asymmetric errors in our best-fit parameters using:
```
aObj = pmn.Analyzer(n_params=nDim, outputfiles_basename=nestOut)
aObj.get_equal_weighted_posterior()
```
In many cases, however, this is being thrown off by nearby modes in the posteriors. Is it possible to return the posteriors for a single mode only?

Thanks!

P.S. for reference, our complete model-fitting script is [here](https://github.com/CIRADA-Tools/RM-Tools/blob/master/RMtools_1D/do_QUfit_1D_mnest.py)

**Comment by JohannesBuchner** [comment]
If you turn off importance nested sampling, the mean and std of each mode is reported by multinest, and can be read with the analyser.

**Comment by JohannesBuchner** [comment]
(from ....stats.dat)

**Comment by AlecThomson** [comment]
Thanks! So we've been using those. It'd be really useful to get the distributions as well. Both to get possibly asymmetric errors, e.g. where std doesn't apply, and also for corner plot visualisation. Is that possible at all?

**Comment by JohannesBuchner** [comment]
I usually get the posterior points, and split them manually by mode (e.g., col1<0.5), and then you can get any statistics and higher modes based on the selected points.

**Comment by AlecThomson** [comment]
Ah, ok. I think that's what I've been trying (and failing) to apply. I don't completely follow how you do the splitting. What do you mean by col1? Are you able to share a snippet? Thanks for your help with this

**Comment by JohannesBuchner** [comment]
Your posterior is a 2d array, with the columns identifying the parameters, and each row a "solution". You look at the corner plot, identify where each mode lies, then develop some criteria to isolate them. Use numpy masks to select the points for one mode.

**Comment by rpoleski** [comment]
I think @AlecThomson wants to get the information that is in  `ROOTpost_separate.dat` file. Different modes are separated by 2 blank lines. Separating "by hand" can be very inefficient if modes are overlapping in different parts of the corner plot.

**Comment by AlecThomson** [comment]
Thanks @rpoleski, that looks exactly like what I'm after! I'm guessing the order is the same as reported in the stat file?

**Comment by JohannesBuchner** [comment]
It's documented in the README https://github.com/JohannesBuchner/MultiNest/

[root]post_separate.dat
This file is only created if mmodal is set to T. Posterior samples for modes with local log-evidence value
greater than Ztol, separated by 2 blank lines. Format is the same as [root].txt file.

I am closing this issue now. Please reopen if you want Analyzer to be able to read the file.
