### ISSUE TITLE
Fortran Runtime Error?

### ISSUE THREAD

**Issue by ghkareem** [JohannesBuchner/PyMultiNest#171]
Hi,

I'm trying to run pymultinest, but seem to be getting a fortran runtime error.

It is managing to start (here is the tail of the output):
```
 *****************************************************
 Starting MultiNest
 generating live points
```

but it returns the following error
```
At line 469 of file /MultiNest/src/nested.F90 (unit = 57, file = '�Ws�*')
Fortran runtime error: File already opened in another unit
```

What causes this error, and how can I go about fixing it? Thanks!

**Comment by JohannesBuchner** [comment]
Try deleting all output files and try again. It can happen that a file is opened twice. Are there strange symbols in the filename?

**Comment by ghkareem** [comment]
So after `generating live points`, it dies before it generates any output files it seems.

As for output directory, I'm guessing that's it since I see it contains A-Z, 0-9, '/'  '-' and '.' 

Could the '.' be the issue? Thanks again

**Comment by ghkareem** [comment]
OK I seem to have done something to change the error. Now it says after `generating live points` that
```
Fortran runtime error: '/mnt/glidein/execute.2f02b124-23b6-11eb-bafc-7cd30ac729a2/dir_523/chain'  is a directory.
```

What causes the `is a directory` error? Thanks

**Comment by JohannesBuchner** [comment]
Probably your filename is too long for the fortran code. Choose a shorter output prefix.

**Comment by ghkareem** [comment]
I was worried that was the case - OK, will do. Thanks again!

**Comment by JohannesBuchner** [comment]
potentially related to #167

**Comment by ghkareem** [comment]
OK, I shortened the prefix to simply './chain', but now it's returned to the `File already opened in another unit`. But only one process is being executed, so I'm somewhat confused why it might be opening the same file multiple times? Sorry for my confusion!

**Comment by JohannesBuchner** [comment]
Try observing what processes are running. Maybe you started one which is paused?

**Comment by ghkareem** [comment]
I found the issue, I was trying to execute multinest via a bash wrapper script on top of a python script, and rather than executing multinest once, it was trying to repeat execute. I put a sleep command in the bash script and it seemed to do the trick, thanks for your help!
