### ISSUE TITLE
Exception on loglike in pymultinest

### ISSUE THREAD

**Issue by ghkareem** [JohannesBuchner/PyMultiNest#172]
Hello,
I am getting an error message as follows:

Exception  in <function loglike at 0x7fe769beb5f0> ignored
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 340, in 'converting callback result'
TypeError: a float is required

I check my prior and likelihood functions are not returning NaNs, and indeed they seem to be fine. What causes this error message? Thanks

**Comment by JohannesBuchner** [comment]
What is your likelihood function returning? Can you print it?

**Comment by ghkareem** [comment]
The likelihood is a little long, but here is an example output:

In [1]: multinest_likelihood(np.zeros(14,),14,14,args,-2.5,FITTER)
we evaluate the likelihood to be
-120.227057726
Out[1]: -120.22705772582233

In [2]: type(multinest_likelihood(np.zeros(14,),14,14,args,-2.5,FITTER))
we evaluate the likelihood to be
-120.227057726
Out[2]: float

**Comment by JohannesBuchner** [comment]
"Exception in <function loglike at 0x7fe769beb5f0> ignored" does not sound good. Why does the function have so many arguments?

**Comment by ghkareem** [comment]
Ah, sorry, so the first argument is the array of input parameters, then ndims,nparams, user input args from argparse, and an external fitter (FITTER) for a subarray of an independent likelihood. Can pymultinest.run only handle likelihood with fewer parameters? Sorry for my confusion!

**Comment by JohannesBuchner** [comment]
If you use pymultinest.run (for example: https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_demo_minimal.py), the signature is:

`myloglike(params, ndim, nparams)` and params is a C array

If you use solve (for example: https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_demo.py), the signature is:

`myloglike(params)` and params is a numpy array

You can pass additional arguments with a wrapper:

```
def wrapped_likelihood(params): 
     return multinest_likelihood(params,14,14,args,-2.5,FITTER)
```

**Comment by JohannesBuchner** [comment]
`solve` will also give more meaningful errors if you are doing something wrong.

**Comment by ghkareem** [comment]
That's great, I'll give it a go - thanks again!

**Comment by ghkareem** [comment]
OK I tried solve, it came back with the following message:
ERROR in prior: 'NoneType' object has no attribute '__getitem__'

Does this mean that the prior cube is trying to load something that has a '__getitem__' method?

**Comment by JohannesBuchner** [comment]
Your prior transform function has an issue. Can you post it here?

**Comment by JohannesBuchner** [comment]
You can debug it with this code:

```
u = np.random.uniform(size=14)
p = my_prior_transform(u)
L = my_log_likelihood(p)
```

**Comment by ghkareem** [comment]
Yeah I wrote these as the transforms, but then I switched over to scipy's ppf's and it seems to return NaNs whenever the parameters are outside the range of the unit cube 
```


def flat_prior_transform(x, low,up):

    x = (up-low)*x + low

    return float(x)







def gaussian_prior_transform(x, mu, sigma):
    """
    Inverse of the cumulative distribution functions
    """
    sigma = 0.085
    mu = 0.308
    x = mu + np.sqrt(2)*sigma* scipy.special.erfinv(2*x-1)

    return float(x)






def limited_gaussian_prior_transform(x, mu, sigma, low=-np.inf, up=np.inf):

    x = mu + np.sqrt(2) * sigma * scipy.special.erfinv(
        scipy.special.erf((low - mu)/(sigma*np.sqrt(2)) )
    + x * (
        scipy.special.erf((up - mu)/(sigma*np.sqrt(2))) - scipy.special.erf((low - mu)/(sigma*np.sqrt(2)))
        )
    )


    return float(x)









def get_prior_transform(prior,x):
    if prior.get_priorType() == 'flat':
        return flat_prior_transform(x,
                                    prior.get_range()[0],
                                    prior.get_range()[1])

    elif prior.get_priorType() == 'gaussian':
        return gaussian_prior_transform(x,
                                        prior.get_value(),
                                        prior.get_std())

    elif prior.get_priorType() == 'limited_gaussian':
        return limited_gaussian_prior_transform(x,
                                                prior.get_value(),
                                                prior.get_std(),
                                                prior.get_range()[0],
                                                prior.get_range()[1])
    else:
        print('{0} is not a recognised priorType. try again')
        raise TypeError('Stopping')

```
I think that might be causing the error - will investigate it more

**Comment by JohannesBuchner** [comment]
Again, you have too many parameters to your functions, and 

```
u = np.random.uniform(size=14)
p = my_prior_transform(u)
L = my_log_likelihood(p)
```
will fail.

You may have success by building single-parameter function

`prepared_flat_prior_transform = lambda x: flat_prior_transform(x, prior.get_range()[0], prior.get_range()[1])`
