### ISSUE TITLE
Unable to install PyMultinest

### ISSUE THREAD

**Issue by SwastikC** [JohannesBuchner/PyMultiNest#176]
Hi. I tried to install PyMultinest and followed the steps but I am unable to do it.. I am also attaching the screenshots. Can you please help me with that.. I am attaching the screenshot..
![sc1](https://user-images.githubusercontent.com/68861854/105714998-0ff39000-5f43-11eb-8749-730709b92096.png)
![ss2](https://user-images.githubusercontent.com/68861854/105715002-1124bd00-5f43-11eb-8704-edb426d030ea.png)

**Comment by JohannesBuchner** [comment]
Do you need PyMultiNest or also cuba?

if you need cuba, follow the instructions at https://github.com/JohannesBuchner/cuba/ to make libcuba.so

For multinest, make sure you empty the build/ folder after changing any packages, before rerunning cmake. You also need to run make after cmake to create libmultinest.so (see installation instructions of PyMultiNest).

**Comment by SwastikC** [comment]
Thank you.. the problem seem to have sorted :)
