### ISSUE TITLE
Could not load MultiNest library "libmultinest.so"

### ISSUE THREAD

**Issue by redeaglekr** [JohannesBuchner/PyMultiNest#177]
Hi,

I know this is a bit old problem. But I couldn't find a solution. 
I installed pymultinest and pycuba  as per the instructions given in the page, http://johannesbuchner.github.io/PyMultiNest/install.html
After the installation I exported the LD_LIBRARY_PATH variable using:
export LD_LIBRARY_PATH=$HOME/MultiNest/lib:$HOME/cuba/:$LD_LIBRARY_PATH

After this I ran my code: which returned me ;
ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

I also tried to run the code:
$ python $OLDPWD/pymultinest_demo.py 
whose output is:
python3: can't open file '/pymultinest_demo.py': [Errno 2] No such file or directory

I ran the codes :
$ python -c 'import pymultinest'
$ python -c 'import pycuba' 
which are giving me no error messages.

Am I missing something?

**Comment by JohannesBuchner** [comment]
You need to give the path to the pymultinest_demo.py file, not $OLDPWD unless that is the same directory you just cd'd out of.

Check that libmultinest.so is in the folder specified by LD_LIBRARY_PATH

**Comment by redeaglekr** [comment]
Yes. pymultinest_demo.py works when ran from its directory. 
The libmultinest.so file is in the directory /home/user/MultiNest/lib and shows no error when run from terminal.
But when run from Python IDLE 3.8.5, still it shows the file missing error.

**Comment by JohannesBuchner** [comment]
you need to set the env vars so they are seen in the IDLE python

**Comment by JohannesBuchner** [comment]
try asking in a pycharm community forum

**Comment by chelinwang** [comment]
> 

Thank you, problem resolved
