### ISSUE TITLE
error while installing MultiNest on macOS mojave

### ISSUE THREAD

**Issue by amkalsi** [JohannesBuchner/PyMultiNest#180]
Dear johannes,

I am trying to install PyMultiNest package on my laptop and is getting following error while doing "make" in build directory of MultiNest

Please have a look and let me know what I am missing

Amandeeps-MacBook-Pro:build amkalsi$  make 
[  1%] Building Fortran object src/CMakeFiles/multinest_static.dir/utils.f90.o
[  2%] Building Fortran object src/CMakeFiles/multinest_static.dir/utils1.f90.o
[  4%] Building Fortran object src/CMakeFiles/multinest_static.dir/kmeans_clstr.f90.o
[  5%] Building Fortran object src/CMakeFiles/multinest_static.dir/xmeans_clstr.f90.o
[  7%] Building Fortran object src/CMakeFiles/multinest_static.dir/posterior.F90.o
[  8%] Building Fortran object src/CMakeFiles/multinest_static.dir/priors.f90.o
[ 10%] Building Fortran object src/CMakeFiles/multinest_static.dir/nested.F90.o
[ 11%] Building Fortran object src/CMakeFiles/multinest_static.dir/cwrapper.f90.o
[ 12%] Linking Fortran static library ../../lib/libmultinest.a
[ 12%] Built target multinest_static
[ 14%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/utils.f90.o
[ 15%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/utils1.f90.o
[ 17%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/kmeans_clstr.f90.o
[ 18%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/xmeans_clstr.f90.o
[ 20%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/posterior.F90.o
[ 21%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/priors.f90.o
[ 22%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/nested.F90.o
/Users/amkalsi/MultiNest/src/nested.F90:1072:16:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2
 1072 |  call MPI_BCAST(ic_npt(1:ic_n),ic_n,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1079:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 1079 |       call MPI_BCAST(ic_done(0:ic_n),ic_n+1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1586:17:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2 
......
 1586 |   call MPI_BCAST(eswitch,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1587:17:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2 
......
 1587 |   call MPI_BCAST(flag2,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1588:17:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2 
......
 1588 |   call MPI_BCAST(modeFound,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1589:17:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2 
......
 1589 |   call MPI_BCAST(lowlike,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1593:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1593 |    call MPI_BCAST(ic_npt(1:ic_n),ic_n,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1594:22:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2      
......
 1594 |        call MPI_BCAST(ic_done(0:ic_n),ic_n+1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                      1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1599:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1599 |    call MPI_BCAST(ic_sc(1:ic_n),ic_n,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1600:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1600 |    call MPI_BCAST(sc_mean(1:sc_n,1:ndims),sc_n*ndims,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1601:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1601 |    call MPI_BCAST(sc_tmat(1:sc_n,1:ndims,1:ndims),sc_n*ndims*ndims,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1602:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1602 |    call MPI_BCAST(sc_kfac(1:sc_n),sc_n,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1603:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1603 |    call MPI_BCAST(sc_eff(1:sc_n),sc_n,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1604:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1604 |    call MPI_BCAST(sc_vol(1:sc_n),sc_n,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1605:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1605 |    call MPI_BCAST(ic_climits(1:ic_n,1:ndims,1:2),ic_n*ndims*2,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1606:18:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2  
......
 1606 |    call MPI_BCAST(ic_volFac(1:ic_n),ic_n,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1807:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 1807 |       call MPI_BCAST(remFlag,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1829:23:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2 
 1828 |         if(lnew>logZero) then
 1829 |          call MPI_SEND(pnew,ndims,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1830:23:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2 
......
 1830 |          call MPI_SEND(phyPnew,totPar,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1898:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 1898 |       call MPI_BCAST(acpt,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1899:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 1899 |       call MPI_BCAST(bogus,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1951:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 1951 |       call MPI_BCAST(remFlag,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:1992:31:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2         
......
 1992 |         if( IS ) call MPI_SEND(n,1,MPI_INTEGER,0,my_rank,MPI_COMM_WORLD,errcode)
      |                               1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
/Users/amkalsi/MultiNest/src/nested.F90:1995:23:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2 
......
 1995 |          call MPI_SEND(i-nd_i,1,MPI_INTEGER,0,my_rank,MPI_COMM_WORLD,errcode)
      |                       1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
/Users/amkalsi/MultiNest/src/nested.F90:1996:23:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2 
......
 1996 |          call MPI_SEND(pnew,ndims,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:1997:23:

 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2 
......
 1997 |          call MPI_SEND(phyPnew,totPar,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:2002:24:

 1834 |          call MPI_RECV(lnewa(nd,i2+1),1,MPI_DOUBLE_PRECISION,i2,i2,MPI_COMM_WORLD,mpi_status,errcode)
      |                       2 
......
 2002 |           call MPI_RECV(n,1,MPI_INTEGER,i2,i2,MPI_COMM_WORLD,mpi_status,errcode)
      |                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
/Users/amkalsi/MultiNest/src/nested.F90:2007:24:

 1834 |          call MPI_RECV(lnewa(nd,i2+1),1,MPI_DOUBLE_PRECISION,i2,i2,MPI_COMM_WORLD,mpi_status,errcode)
      |                       2 
......
 2007 |           call MPI_RECV(sEll(nd,i2+1),1,MPI_INTEGER,i2,i2,MPI_COMM_WORLD,mpi_status,errcode)
      |                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(8)).
/Users/amkalsi/MultiNest/src/nested.F90:2110:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 2110 |       call MPI_BCAST(acpt,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2111:21:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2     
......
 2111 |       call MPI_BCAST(bogus,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2276:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2276 |      call MPI_BCAST(sc_kfac(i),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2277:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2277 |      call MPI_BCAST(sc_eff(i),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2278:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2278 |      call MPI_BCAST(sc_vol(i),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2279:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2279 |      call MPI_BCAST(sc_kfac(q),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2280:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2280 |      call MPI_BCAST(sc_eff(q),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:2281:20:

 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2    
......
 2281 |      call MPI_BCAST(sc_vol(q),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,errcode)
      |                    1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:554:18:

  554 |     call MPI_SEND(lnewP(1:i),i,MPI_DOUBLE_PRECISION,0,id,MPI_COMM_WORLD,errcode)
      |                  1
......
 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/Users/amkalsi/MultiNest/src/nested.F90:555:18:

  555 |     call MPI_SEND(pnewP(1:ndims,1:i),ndims*i,MPI_DOUBLE_PRECISION,0,id,MPI_COMM_WORLD,errcode)
      |                  1
......
 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
/Users/amkalsi/MultiNest/src/nested.F90:556:18:

  556 |     call MPI_SEND(phyPnewP(1:totPar,1:i),totPar*i,MPI_DOUBLE_PRECISION,0,id,MPI_COMM_WORLD,errcode)
      |                  1
......
 1827 |         call MPI_SEND(lnew,1,MPI_DOUBLE_PRECISION,0,my_rank,MPI_COMM_WORLD,errcode)
      |                      2
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
/Users/amkalsi/MultiNest/src/nested.F90:595:17:

  595 |   call MPI_BCAST(bogus,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                 1
......
 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2 
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
/Users/amkalsi/MultiNest/src/nested.F90:345:16:

  345 |  call MPI_BCAST(genLive,1,MPI_LOGICAL,0,MPI_COMM_WORLD,errcode)
      |                1
......
 1071 |  call MPI_BCAST(ic_n,1,MPI_INTEGER,0,MPI_COMM_WORLD,errcode)
      |                2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
make[3]: *** [src/CMakeFiles/multinest_mpi_shared.dir/nested.F90.o] Error 1
make[2]: *** [src/CMakeFiles/multinest_mpi_shared.dir/nested.F90.o.provides] Error 2
make[1]: *** [src/CMakeFiles/multinest_mpi_shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by JohannesBuchner** [comment]
Can you try applying the changes proposed here: https://github.com/JohannesBuchner/MultiNest/pull/3/files

**Comment by amkalsi** [comment]
Thanks Johannes, it is working now. However, moving forward to cuba installation, I got following error on the command (./makesharedlib.sh)


** ERROR***
rm -f Data.o
ranlib libcuba.a
unpacking libcuba.a
making libcuba.so
gcc -shared -Wall __.SYMDEF SORTED Vegas.o Vegas_.o llVegas.o llVegas_.o Suave.o Suave_.o llSuave.o llSuave_.o Divonne.o Divonne_.o llDivonne.o llDivonne_.o Cuhre.o Cuhre_.o llCuhre.o llCuhre_.o Fork.o Fork_.o Global.o Global_.o Data.o -lm -o libcuba.so
clang: error: no such file or directory: '__.SYMDEF'
clang: error: no such file or directory: 'SORTED'
rm: __.SYMDEF: No such file or directory
rm: SORTED: No such file or directory

**Comment by JohannesBuchner** [comment]
Do you really want cuba? If not, skip this.

I think currently only gcc is supported, but feel free to open a bug in the cuba repo.

**Comment by amkalsi** [comment]
I was under impression that  PyMultiNest requires both Cuba and MultiNest libraries. I am following these instructions [https://johannesbuchner.github.io/PyMultiNest/install]. Apologies for my ignorance. 
So, after skipping the installation of Cuba, I got the following error while running pymultinest_demo.py. I installed all the mentioned packages. Not sure what I am missing here. Please have a look

Amandeeps-MacBook-Pro:PyMultiNest amkalsi$ python pymultinest_demo.py
Traceback (most recent call last):
  File "/Users/amkalsi/PyMultiNest/pymultinest_demo.py", line 26, in <module>
    result = solve(LogLikelihood=myloglike, Prior=myprior, 
  File "/Users/amkalsi/PyMultiNest/pymultinest/solve.py", line 71, in solve
    run(**kwargs)
  File "/Users/amkalsi/PyMultiNest/pymultinest/run.py", line 282, in run
    lib.run(*args_converted)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found

**Comment by JohannesBuchner** [comment]
Follow the links here: https://stackoverflow.com/questions/61939257/attributeerror-dlsymrtld-default-run-symbol-not-found-meaning

**Comment by amkalsi** [comment]
Hi Johannes, 

Thanks !! Adding  os.environ['DYLD_LIBRARY_PATH'] = '/path/to/MultiNest/lib' to run.py fixes the problem. I am able to run 
 pymultinest_demo.py file now.

Regards,
Amandeep
