### ISSUE TITLE
Montepython error probably due to PyMultiNest

### ISSUE THREAD

**Issue by odinvik** [JohannesBuchner/PyMultiNest#181]
Dear sir,
I am trying to install montepython in Arch. I am getting this error (screenshot below). I am not that familiar with linux. It is probably due to PyMultiNest on part. Please Help.
![Screenshot from 2021-04-01 23-51-29](https://user-images.githubusercontent.com/67832703/113337534-8185fb00-9345-11eb-94dd-5ec8bc83ccea.png)

**Comment by JohannesBuchner** [comment]
Please open a bug with pymultinest. Also carefully read the error message in the middle, "-conf" is not a thing.
