### ISSUE TITLE
acceptance rate always equal to 1

### ISSUE THREAD

**Issue by Xinyi2021** [JohannesBuchner/PyMultiNest#182]
I was trying to do model selection, but all the models render the same ln(ev)=  -1.3548691790883638E-014. All the models run with an acceptance rate =1, no matter how I tune tol, efr, or nlive. I make a comparison with Mathematica, which gives a chi-squared min at a few hundred (~300) for some of the models. But with MultiNest MAP parameters, the best I can get corresponds to a chi-squared ~10^7. 

The likelihood function is Gaussian, I suspect that because the models are all bad - chi-squared too large -> likelihood too small. Even in this case, I expect MultiNest can show some differences among the models. Is it possible to tune MultiNest to give results comparable to Mathematica? Does the acceptance rate mean something wrong?

Thanks in advance!
Xinyi

**Comment by JohannesBuchner** [comment]
How many likelihood evaluations or iterations are made?

**Comment by JohannesBuchner** [comment]
If it is very few, then it is possible that your prior generates points that are all exactly equally bad, and multinest stops immediately.

**Comment by Xinyi2021** [comment]
I have tried nlive=30000, and it is the number of evaluations. I cannot get a larger number as there will be segment faults. I also tried to confine the parameters near the best fit points given by Mathematica, still acceptance rate 1.

**Comment by JohannesBuchner** [comment]
You probably have a bug in your prior transform or likelihood function.

**Comment by JohannesBuchner** [comment]
Can you show your transform functions and how you call pymultinest?

**Comment by Xinyi2021** [comment]
I use uniform priors like: physical para = 0.002 * Cube[0] + 0.435, in the form (high -low) * Cube + low.
I use the C++ interface of MultiNest (the CMake one). The likelihood function is tested for a single set of inputs and it works fine.

**Comment by Xinyi2021** [comment]
the likelihood function is

  `double chi1 = pow( (s12sq-0.304)/0.013, 2.0 );
    double lnew1 = exp(-0.5*chi1)/ (sqrt(2*M_PI) * 0.013);
    double chi2 = pow( (s13sq-0.02221)/0.00065, 2.0 );
    double lnew2 = exp(-0.5*chi2)/ sqrt(2*M_PI) /0.00065;
    double chi3 = pow( (s23sq-0.570)/0.021, 2.0 );
    double lnew3 = exp(-0.5*chi3)/ (sqrt(2*M_PI) * 0.021);
    double chi4 = pow( ((pow(m2,2) - pow(m1,2))/(pow(m3,2) - pow(m1,2))-0.0295)/0.0009, 2.0 );
    double lnew4 = exp(-0.5*chi4)/ (sqrt(2*M_PI) * 0.0009);
    double chi5 = pow((ml1-2.794745e-6)/1.6e-11, 2.0);
    double lnew5 = exp(-0.5*chi5)/ (sqrt(2*M_PI) * 1.6e-11);
    double chi6 = pow((ml2-5.899863e-4)/1.9e-9, 2.0);
    double lnew6 = exp(-0.5*chi6)/ (sqrt(2*M_PI) * 1.9e-9);
    double chi7 = pow((ml3-1.002950e-2)/9.1e-7, 2.0);
    double lnew7 = exp(-0.5*chi7)/ (sqrt(2*M_PI) * 9.1e-7);
    lnew = lnew1 * lnew2 * lnew3 * lnew4 * lnew5 * lnew6 * lnew7;`

**Comment by Xinyi2021** [comment]
The likelihood function is

 ```
double chi1 = pow( (s12sq-0.304)/0.013, 2.0 );
    double lnew1 = exp(-0.5*chi1)/ (sqrt(2*M_PI) * 0.013);
    double chi2 = pow( (s13sq-0.02221)/0.00065, 2.0 );
    double lnew2 = exp(-0.5*chi2)/ sqrt(2*M_PI) /0.00065;
    double chi3 = pow( (s23sq-0.570)/0.021, 2.0 );
    double lnew3 = exp(-0.5*chi3)/ (sqrt(2*M_PI) * 0.021);
    double chi4 = pow( ((pow(m2,2) - pow(m1,2))/(pow(m3,2) - pow(m1,2))-0.0295)/0.0009, 2.0 );
    double lnew4 = exp(-0.5*chi4)/ (sqrt(2*M_PI) * 0.0009);
    double chi5 = pow((ml1-2.794745e-6)/1.6e-11, 2.0);
    double lnew5 = exp(-0.5*chi5)/ (sqrt(2*M_PI) * 1.6e-11);
    double chi6 = pow((ml2-5.899863e-4)/1.9e-9, 2.0);
    double lnew6 = exp(-0.5*chi6)/ (sqrt(2*M_PI) * 1.9e-9);
    double chi7 = pow((ml3-1.002950e-2)/9.1e-7, 2.0);
    double lnew7 = exp(-0.5*chi7)/ (sqrt(2*M_PI) * 9.1e-7);
    lnew = lnew1 * lnew2 * lnew3 * lnew4 * lnew5 * lnew6 * lnew7;
```

**Comment by Xinyi2021** [comment]
The output is
```
MultiNest v3.12
 Copyright Farhan Feroz & Mike Hobson
 Release Nov 2019

 no. of live points = ****
 dimensionality =    9
 *****************************************************
 Starting MultiNest
 generating live points
 live points generated, starting sampling
Acceptance Rate:                        1.000000
Replacements:                              30000
Total Samples:                             30000
Nested Sampling ln(Z):            **************
Importance Nested Sampling ln(Z):      -0.000000
 ln(ev)=  -1.3548691790883638E-014 +/-   6.7202906164549256E-010
 Total Likelihood Evaluations:        30000
 Sampling finished. Exiting MultiNest
```

**Comment by JohannesBuchner** [comment]
Why open a issue in PyMultiNest if your code does not use PyMultiNest?

**Comment by Xinyi2021** [comment]
I'm sorry if it's the wrong place to ask. I thought the problem is intrinsic in MultiNest and you are the best expert who is responsive...

**Comment by JohannesBuchner** [comment]
> the likelihood function is
> 
> ```
>     double chi1 = pow( (s12sq-0.304)/0.013, 2.0 );
>     double lnew1 = exp(-0.5*chi1)/ (sqrt(2*M_PI) * 0.013);
>     double chi2 = pow( (s13sq-0.02221)/0.00065, 2.0 );
>     double lnew2 = exp(-0.5*chi2)/ sqrt(2*M_PI) /0.00065;
>     double chi3 = pow( (s23sq-0.570)/0.021, 2.0 );
>     double lnew3 = exp(-0.5*chi3)/ (sqrt(2*M_PI) * 0.021);
>     double chi4 = pow( ((pow(m2,2) - pow(m1,2))/(pow(m3,2) - pow(m1,2))-0.0295)/0.0009, 2.0 );
>     double lnew4 = exp(-0.5*chi4)/ (sqrt(2*M_PI) * 0.0009);
>     double chi5 = pow((ml1-2.794745e-6)/1.6e-11, 2.0);
>     double lnew5 = exp(-0.5*chi5)/ (sqrt(2*M_PI) * 1.6e-11);
>     double chi6 = pow((ml2-5.899863e-4)/1.9e-9, 2.0);
>     double lnew6 = exp(-0.5*chi6)/ (sqrt(2*M_PI) * 1.9e-9);
>     double chi7 = pow((ml3-1.002950e-2)/9.1e-7, 2.0);
>     double lnew7 = exp(-0.5*chi7)/ (sqrt(2*M_PI) * 9.1e-7);
>     lnew = lnew1 * lnew2 * lnew3 * lnew4 * lnew5 * lnew6 * lnew7;
> ```

It is supposed to compute a loglikelihood.
So you should remove the exp() and sum the lnews.

**Comment by Xinyi2021** [comment]
Thank you very much! That solves the issue indeed!
