### ISSUE TITLE
MLE vs MAP

### ISSUE THREAD

**Issue by aport2021** [JohannesBuchner/PyMultiNest#184]
Hi,
I was wondering what would MLE = MAP means (given in the 'stats.dat' file). From my understanding, MLE indicates the parameter value corresponding to the maximum likelihood value in the likelihood function samples and MAP in the posterior samples. The difference between the 2 is therefore due to the choice of priors. 
In 'example 2' from the tutorial, priors uniform in log and MLE strictly equals MAP, I have tried to impose a narrow Gaussian prior on one of the three parameters (width) forcing a different solution and I still get MLE = MAP. In 'example 1' we do get different values, is that due to the multi-modal nature of the likelihood?
I guess my question is what would make them equal or not? How well it converged? Priors? multimodal likelihood?
Thanks!

**Comment by JohannesBuchner** [comment]
Honestly, I don't know how MultiNest computes the MAP. You'd have to look at the fortran code.

**Comment by aport2021** [comment]
I had a look, and it seems like the MLE is the maximum argument of the 'points' (pt(...)) and the MAP is the maximum argument of the probability weights (pwt(...)), which is what is to be expected.
![image](https://user-images.githubusercontent.com/83207552/116206236-edf7ec80-a781-11eb-8153-2aacb1eb627a.png)
I am unsure why they would be exactly equal, but i guess it just means that the priors did not get in the way regarding the sampling around the maximum likelihood and it's actual value.
I think this thread can be closed, thanks!
