### ISSUE TITLE
ERROR:   Could not load MultiNest library: libmultinest.so

### ISSUE THREAD

**Issue by QGravityGRGW** [JohannesBuchner/PyMultiNest#185]
Hi Johannes,
I'm trying to install PyMultiNest on Ubuntu 18.04.5 LTS. I have installed with all steps mentioned in https://johannesbuchner.github.io/PyMultiNest/install.html

I have installed it with 
$ pip install pymultinest
then with git clone as well, but the error it still shows is:
$ python3 -c 'import pymultinest'

ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

## I'm using anaconda3 python version which is installed in 
/home/jarvis-astro/software/anaconda3/

Attaching all the relevant screenshots for your reference.

Kindly help!!
![Screenshot from 2021-05-04 03-28-48](https://user-images.githubusercontent.com/71552919/116938753-e4dab400-ac88-11eb-846b-b9724432ccae.png)
![Screenshot from 2021-05-04 03-21-07](https://user-images.githubusercontent.com/71552919/116938761-e73d0e00-ac88-11eb-987e-383b4452df94.png)
![Screenshot from 2021-05-04 03-16-32](https://user-images.githubusercontent.com/71552919/116938767-e906d180-ac88-11eb-907c-242c9506da98.png)
![Screenshot from 2021-05-04 03-16-27](https://user-images.githubusercontent.com/71552919/116938773-ea37fe80-ac88-11eb-9c7c-79ec2ed7aa6d.png)
![Screenshot from 2021-05-04 03-16-22](https://user-images.githubusercontent.com/71552919/116938779-ec01c200-ac88-11eb-920b-9af8fb607b5e.png)

**Comment by JohannesBuchner** [comment]
Is libmultinest.so in the folder given in LD_LIBRARY_PATH?

**Comment by JohannesBuchner** [comment]
https://johannesbuchner.github.io/PyMultiNest/install.html#building-the-libraries

**Comment by QGravityGRGW** [comment]
Yes, libmultinest.so os in the folder given in LD_LIBRARY_PATH
![Screenshot from 2021-05-04 16-34-13](https://user-images.githubusercontent.com/71552919/116994633-9663fe80-acf6-11eb-8e63-2c8927296d11.png)

**Comment by QGravityGRGW** [comment]
> https://johannesbuchner.github.io/PyMultiNest/install.html#building-the-libraries

Yes I have followed this only, but still getting the error

**Comment by QGravityGRGW** [comment]
Hi, somehow just resolved the issue, I guess it's now working well
Attaching the screenshot if you can comment if it's working okay

Thanks for all the help Johannes.
