### ISSUE TITLE
Linux issue - no module pymultinest

### ISSUE THREAD

**Issue by astrogirl1** [JohannesBuchner/PyMultiNest#186]
Hi, 

I am having trouble running multinest/PyMultiNest using MontePython. I have followed the github tutorial on installation and also a few other github issues here. 
It compiles correctly and I export the paths to both LD_LIBRARY_PATH and PATH where needed. But when running with MontePython I get this error, 

```
Configuration Error:
 /|\   unrecognized arguments: --NS_importance_nested_sampling True
/_o_\  --NS_n_live_points 5000

```
I have tried deleting everything in the build/ folder and running cmake again but it hasnt worked. I must be missing somethign very trivial but I cannot put my finger on it, so any help will be greatly appreciated. 

I am on linux ubuntu 18.04.5 and python 2.7.17. 

Thank you, 
Meera

**Comment by JohannesBuchner** [comment]
This is not a PyMultiNest issue. Please open an issue with MontePython.
