### ISSUE TITLE
Paralle Job in HTCondor Cluster

### ISSUE THREAD

**Issue by ghoshtathagata** [JohannesBuchner/PyMultiNest#191]
I am able to run parallel pymultinest using "mpiexec ..." on my laptop as well HPC. However, I don't understand how to run in the HTCondor cluster. Any suggestion will be helpful.

HTCondor Ref: https://en.wikipedia.org/wiki/HTCondor

**Comment by JohannesBuchner** [comment]
I don't have experience with that system. Contact the cluster administrators how to submit MPI jobs.
