### ISSUE TITLE
Multinest not writing to post_equal_weights

### ISSUE THREAD

**Issue by nenasedk** [JohannesBuchner/PyMultiNest#192]
I'm running pymultinest on a cluster using slurm (multinest release 2017-12-07), and am having an issue with writing to the post equal weights file. 
My program has been running for several days, and all of the other standard files are regularly written, and the sampling still seems to be working:

```
Acceptance Rate:                        0.013408
Replacements:                             105300
Total Samples:                           7853459
Nested Sampling ln(Z):              -1315.185174
Importance Nested Sampling ln(Z):   -1320.391115 +/-  0.562458
```

However, the PEW file only has 16 lines written to it after nearly 8M samples, and was last written 10 days ago. 
Is there any reason why the write to this file should be so infrequent? Even if it usually only fills the file towards the end of the sampling, it usually still updates semi-regularly. I'm running PMN with resume=True, in constant efficiency mode (samp_eff=0.05), with 4000 live points, with about 20 free parameters.

If there's any information I can provide to help debug this problem, please let me know.

**Comment by JohannesBuchner** [comment]
The MultiNest documentation https://github.com/JohannesBuchner/MultiNest/ says:

```
Posterior Files:

These files are created after every updInt*10 iterations of the algorithm & at the end of sampling.
```

The corresponding pymultinest parameter is `n_iter_before_update` (100 by default).
