### ISSUE TITLE
Getting "ValueError: not enough values to unpack (expected 2, got 1)" error when running PyMultiNest

### ISSUE THREAD

**Issue by MoneSylvia** [JohannesBuchner/PyMultiNest#194]
Hello!

So I'm new to PyMultiNest and have just finished installing it. I tried to run the binary file in `/MultiNest/bin/` and encountered no problem. But, when I tried to run PyMultiNest (e.g. on [this code example](https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_demo.py), I encountered the following error

`ValueError: not enough values to unpack (expected 2, got 1)` when the code evaluates this line: `name, values = l.split('   ', 1)`

I also tried to run it on various codes using the package and encounter the same error. I'm pretty sure that the installation worked fine. All the prerequisites are also in the latest version. So, I really don't have any idea about what's going on here. Can somebody help me, please?

Thank you very much!

Best,
Mone

**Comment by MoneSylvia** [comment]
![Screenshot from 2021-08-28 15-35-31](https://user-images.githubusercontent.com/89698848/131223192-d3bf3532-d5c5-4acb-b50b-be80e08f880c.png)

The error looks like this by the way.

**Comment by JohannesBuchner** [comment]
Can you do the following:

```
git clone https://github.com/JohannesBuchner/MultiNest/
cd MultiNest
git checkout 4adff1db404f3c4e338c7c836abd0039fddda3d8
cd build
cmake ..
make
```
and try again?

I am wondering if a recent contributed patch that I merged last week caused this bug.

**Comment by MoneSylvia** [comment]
It works! Thank you so much! I wonder what's the problem..
