### ISSUE TITLE
making corner plots for different modes

### ISSUE THREAD

**Issue by svaverbe** [JohannesBuchner/PyMultiNest#196]
When the algorithm runs multimodel, is it possible to make cornerplots for the different modes ?  How can one access the samples for each mode ?

**Comment by JohannesBuchner** [comment]
Yes, I think the modes are in the marginals dictionary, available through the analyser.

`analyser.get_mode_stats()` or `analyser.get_stats()['marginals']`

https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/analyse.py#L173

If INS is turned on, multinest does not produce this information, IIRC.

**Comment by JohannesBuchner** [comment]
Oh, I think the samples are not available. I am not sure, maybe multinest writes a text file with them. Have a look at the README https://github.com/JohannesBuchner/MultiNest/#readme
