### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by am610** [JohannesBuchner/PyMultiNest#197]
Hi, while  submitting the following job with Multinest included, I get the error as shown below : 

`
Configuration Error:
 /|\   Nested Sampling with MultiNest is only possible for bound parameters. Set
/_o_\  reasonable bounds for them in the ".param"file.

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/run.py", line 32, in run
    custom_command)
  File "/global/cscratch1/sd/ayanmitr/montepython_V3/montepython/run.py", line 198, in safe_initialisation
    "The initialisation was not successful, resulting in a "
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.

`
-----------------------------------------

As a check, this input param runs ok when used without the `-m NS` option

My param file essentials are following: 
-----------------------------------------

`
data.experiments=['bao_boss_dr12', 'bao_smallz_2014','SNANA', 'Planck_lowl_TT','Planck_lowl_EE','Planck_lowl_BB','Planck_highl_TT_lite','Om']
data.parameters['omega_b'] = [ 2.2253, None, None, 0.028, 0.01, 'cosmo']
data.parameters['omega_cdm'] = [ 0.1120, None, None, 0.0016, 1, 'cosmo']

data.parameters['w0_fld'] = [ -0.995,-3.5, -1, 0.001, 1, 'cosmo']
data.parameters['w0wa'] = [ -1, -3.5,-1, 0.001, 1, 'cosmo']

### Nuisance
data.parameters['M']        = [-19.02, None, None, 0.004,  1, 'nuisance']
data.parameters['A_planck'] = [100.028,   90,  110,  0.25,  0.01,'nuisance']

### Derived parameter list

data.parameters['H0'] = [0, None, None, 0, 1, 'derived']
data.parameters['Omega_m'] = [0, None, None, 0, 1, 'derived']
data.parameters['Omega0_fld'] = [0, None, None, 0, 1, 'derived']

data.cosmo_arguments['N_ur'] = 2.0328
data.cosmo_arguments['N_ncdm'] = 1
data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = 0.71611

data.cosmo_arguments['Omega_Lambda'] = 0
data.cosmo_arguments['Omega_k'] = 0.

`
--------------------------------------
what is happening ?

**Comment by JohannesBuchner** [comment]
This is not a pymultinest bug. Please open an issue with the relevant software package, MontePython in this case.
