### ISSUE TITLE
Error caused by NumPy and Numba

### ISSUE THREAD

**Issue by priyashmistry** [JohannesBuchner/PyMultiNest#203]
I was trying to run VESPA in my device. But at the beginning it gave an error "numpy.core.multiarray failed to import". I found out that it was due to the outdated version of NumPy. So I updated it to the latest but at that time I got an error "Numba needs NumPy 1.21 or less" 

Both the errors are contradictory. Can you please look into it.

**Comment by JohannesBuchner** [comment]
numba is not used in pymultinest. I don't know what VESPA is. You probably need to clean your python installation, e.g., with a new (virtual or conda) environment. Make sure `import numba, numpy` succeeds. Then try using pymultinest.
