### ISSUE TITLE
Specifying "Linux" platform in run.py

### ISSUE THREAD

**Issue by hzarei4** [JohannesBuchner/PyMultiNest#206]
Hello,

I tried to install the package on linux platform (for days :D) but the error of `cannot open shared object file: No such file or directory libmultinest.so` did not solve. I tried to change the `LD_LIBRARY_PATH` environment variable both from python IDLE and terminal but it did not help.

So I changed parts of the source code and solved this issue. In the file `/usr/local/lib/python3.7/dist-packages/pymultinest/run.py` or in the package: `pymultinest/run.py` line 14 to 

`		if sys.platform == 'linux':
`

and the problem solved and imported in python 3.7.

I am using python 3.7 on Google Colaboratory (Linux platform). 

Could I add a new commit on this issue?

Thanks!

**Comment by JohannesBuchner** [comment]
When you ran from terminal, did you export the variable? That is:

`LD_LIBRARY_PATH=/path/to/multinest/lib python3 myscript.py`

or 

```
export LD_LIBRARY_PATH=/path/to/multinest/lib
python3 myscript.py
```

and verified that `ls $LD_LIBRARY_PATH/libmultinest.so` does not complain.

**Comment by hzarei4** [comment]
Oh, yes, that's true. My mistake.

When I run `export LD_LIBRARY_PATH=/path/to/multinest/lib` from Terminal, it works. But the same code, in Colaboratory did not run and the `libmultinest.so did not found`.

**Comment by JohannesBuchner** [comment]
did you set the environment variable with os.environ?

**Comment by hzarei4** [comment]
Yes, and then it did not import the package.

**Comment by JohannesBuchner** [comment]
I am not sure what the implications of switching to find_library by default are. Can you research this?

Can you test your proposed change on python 2.7, 3.4 and the latest python on linux?

**Comment by hzarei4** [comment]
Alright, I will try that and let you know about the results (in a few days).

**Comment by JohannesBuchner** [comment]
I am closing this. If the issue still persists, feel free to reopen.
