### ISSUE TITLE
local ln(Z) vs. strictly local ln(Z)

### ISSUE THREAD

**Issue by rpoleski** [JohannesBuchner/PyMultiNest#207]
With multimode function turned on, I'm getting the same values of `Strictly Local Log-Evidence` and `Local Log-Evidence`, but their errors are different. Does anybody know what is the difference between them?

**Comment by JohannesBuchner** [comment]
May have to do with Ztol https://github.com/JohannesBuchner/MultiNest/blob/master/README

**Comment by rpoleski** [comment]
I haven't found anything directly related to Ztol.
I've made some tests with toy models with known probability of each mode. I've calculated probabilities as `p_i = Z_i/np.sum(Z_i)` and its error: `sigma_p_i = p_i * sigma_ln_Z_i` (i.e., ignoring uncertainty of `np.sum(Z_i)`). The uncertainties of `Local Log-Evidence` are closer to the scatter of `p_i` around known values than for its strict version.

**Comment by JohannesBuchner** [comment]
I am closing this as it is not a PyMultiNest issue.
