### ISSUE TITLE
Odd values in the chain file (.txt file)

### ISSUE THREAD

**Issue by Andrei-EPFL** [JohannesBuchner/PyMultiNest#212]
Hello,
I am running PyMultinest in parallel on a cluster using 8 nodes and 8 tasks per node, thus 64 tasks in total. 
Moreover each tasks is using 8 threads (OpenMP) to compute some curves. 

I ran the code on an interactive node for even more tasks and I got reasonable results in the chain file, however when I launch it normally on the batch, the column of the chi2 in the chain file contains only this value "-0.592878775009495853-322". The "ev.dat" file has normal values. Moreover, I print at each step the value of the chi2, so  I have it in the standard output. None of the values of the chi2 are equal to something odd (like -0.592878775009495853-322). I am not sure if it is a problem of the parallelization, the cluster or a bug of mine.

Did anyone has observed this behaviour or this number?

I am working on NERSC cluster.

Thank you very much!
Kind regards,
Andrei

**Comment by JohannesBuchner** [comment]
That's a fortran "feature", and unrelated to the parallelisation.
