### ISSUE TITLE
issue with adding a JWST/MIRI photometric band when generating a model galaxy spectrum? 

### ISSUE THREAD

**Issue by Vladan1986** [JohannesBuchner/PyMultiNest#218]
Hello, 

I have an issue when I want to generate a model galaxy spectrum with predictions for photometric fluxes for an example galaxy with HST and JWST filters. 

When I add all the available filters for this galaxy, including the MIRI F770W filter (in the attachment) I obtain 1 data point that seems to be <1 in the x axis log space, so lambda seems to be negative (Fig. 2). If I remove the F770W filter, I obtain Fig. 1.

I tried removing the 0 and  < 10^{-11} flux values from the F770W throughput values, but that didn't solve the issue.
Any suggestion or help is welcome. 

Cheers,

![fig-2](https://user-images.githubusercontent.com/35525863/191787649-68cb8d9e-9218-4da6-ad12-6453e10b6098.png)
[F770W.csv](https://github.com/JohannesBuchner/PyMultiNest/files/9627229/F770W.csv)
![fig-1](https://user-images.githubusercontent.com/35525863/191787633-130df7b1-919a-479c-ac99-b4b8079c2e7f.png)

**Comment by JohannesBuchner** [comment]
This does not seem related to pymultinest at all. Try to simplify your problem.
