### ISSUE TITLE
CMake and MKL Fatal Error

### ISSUE THREAD

**Issue by Miklnl** [JohannesBuchner/PyMultiNest#22]
Hi Johannes,

I have an issue with running pymultinest on the local cluster at my institute (no root permission), where I have compiled MultiNest using the CMake version put on your site. 
When running the "cmake .." in the "build" folder there are no errors reported.
When afterwards running "make" everything except for "eggboxC" and "eggboxC++" also compiles with no errors. For the two above exceptions the error is something like:
""" 
Scanning dependencies of target eggboxC
[ 63%] Building C object src/example_eggbox_C/CMakeFiles/eggboxC.dir/eggbox.c.o
Linking C executable ../../../bin/eggboxC
CMakeFiles/eggboxC.dir/eggbox.c.o: In function `run':
eggbox.c:(.text+0x127): undefined reference to`__nested_MOD_nestrun'
collect2: ld returned 1 exit status
make[2]: **\* [../bin/eggboxC] Error 1
make[1]: **\* [src/example_eggbox_C/CMakeFiles/eggboxC.dir/all] Error 2
make: **\* [all] Error 2
"""

Anyway, after running the pymultinest setup I can import pymultinest without any errors.
When I then try to run e.g. the "pymultinest_demo" all goes well for a while, but every time it stops with the error:

"""
            .
            .
            .
Nested Sampling ln(Z):                 64.459124
Acceptance Rate:                        0.608211
Replacements:                               2400
Total Samples:                              3946
Nested Sampling ln(Z):                 67.875897

MKL FATAL ERROR: Cannot load neither libmkl_mc3.so nor libmkl_def.so
"""

I know that these .so files are in my LD_LIBRARY_PATH, so I'm guessing its a problem with the Makefile from cmake...

Do you have any suggestions for a solution?

Cheers,
   Mikkel

**Comment by kmanalo** [comment]
Sorry to open an old thread, but I would like to add that I encountered this exact problem and also found that adding -lmkl_mc3 worked.  Any chance this can be worked into the cmake configuration?  This is based on using GNU/4.8.4 with MKL/11.2.3 on RHEL6.7

**Comment by JohannesBuchner** [comment]
The right place to ask for Multinest changes is here http://ccpforge.cse.rl.ac.uk/gf/project/multinest/tracker/?action=TrackerItemBrowse&tracker_id=312.

**Comment by kmanalo** [comment]
Thanks, I'm not very familiar with authorship, and I was excited to have this work for a user on an HPC system that I work on.  BTW, the intent is to support a user of PyMultiNest, in which case the python script works with this flag fix.

**Comment by kmanalo** [comment]
@JohannesBuchner thanks for the link redirection, I'll file a report there.
