### ISSUE TITLE
Error: exception str() failed

### ISSUE THREAD

**Issue by ash2223** [JohannesBuchner/PyMultiNest#230]
Hi Johannes!

I'm attempting to run MontePython with PyMultiNest, and I seem to be running into an error when trying to analyze the Planck lite likelihood:

![Screen Shot 2023-04-04 at 1 01 41 PM](https://user-images.githubusercontent.com/61329093/229908013-9fc33785-3a1e-4072-9d31-dc10884a371c.png)

It seems that there is an "<exception str() failed>" error thrown by clik. I'm wondering if you've seen this issue before? If so, do you know how to address it? Thank you so much!

-Adam

**Comment by JohannesBuchner** [comment]
Report this to MontePython.
