### ISSUE TITLE
pypi version of Pymultinest breaks

### ISSUE THREAD

**Issue by pcubillos** [JohannesBuchner/PyMultiNest#237]
Hi,
Now that `inspect.getargspec` has been removed in Python 3.11, the pypi version of PyMultiNest breaks in these lines because it doesn't have the `if` statement that implements `inspect.getfullargspec()` from the current github version.
 https://github.com/JohannesBuchner/PyMultiNest/blob/c8eba95ecc9583c6662e868e74bbd9992b71a787/pymultinest/run.py#L211-L215

**Comment by JohannesBuchner** [comment]
So I just have to make a release?

**Comment by pcubillos** [comment]
Yup, exactly.
Thanks!

**Comment by JohannesBuchner** [comment]
In case you are wondering why I have not done this yet, I re-added continuous integration. PyMultiNest used to have travis, before they shut down open source repos. Now I added a github action: https://github.com/JohannesBuchner/PyMultiNest/actions

Open problems:
* cuba does not compile to a shared library anymore, so all the pycuba stuff is broken, cannot run those tests
  * This can be solved cleanly by ripping these components out of the repo, which I am not quite ready to do yet.
  * This can also be solved by `rm tests/pycuba_test.py` (very hacky)
* coveralls, coverage.py and coverage-lcov are incompatible in both pypi and conda installs with the error mentioned at https://github.com/TheKevJames/coveralls-python/pull/340
  * This can be solved by editing [coverage-lcov/convert.py](https://github.com/TheCleric/coverage-lcov/blob/master/coverage_lcov/converter.py) with  `sed --in-place -e 's,"report_include",,g' -e 's,"report_omit",,g' /usr/share/miniconda/envs/*/lib/python*/site-packages/coverage_lcov/converter.py` (very hacky)
  * This can also be solved by forking that project https://github.com/JohannesBuchner/coverage-lcov, cloning that, and installing from there.
  * but this solution has been hanging for 3 hours https://github.com/JohannesBuchner/PyMultiNest/actions/runs/5693082653/job/15431388036

**Comment by JohannesBuchner** [comment]
CI is green, can you believe it!

**Comment by pcubillos** [comment]
Great!
Yeah, I know how painful the move from travis to github actions can get

**Comment by JohannesBuchner** [comment]
2.12 is on pypi, please test it and let me know

**Comment by pcubillos** [comment]
Yeah, it's working. Tested on OS X 12.6 / M1 chip, with and without MPI.
Thanks for the quick fix!
