### ISSUE TITLE
cube.toList() or .toArray() ?

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyMultiNest#24]
Hi Johannes,

Various python functions don't recognise cube as being list-like/array-like, e.g. in my loglike I have to do something like:

    c=[]
    for i in range(ndim):
        c.append(cube[i])

    model=numpy.polynomial.polynomial.polyval(freqs,c)
    ...

I don't know (at all), but presumably the cube -> c conversion is slow.

Of course individual elements of cube can be addressed as cube[0] etc. List comprehension, i.e. [ci for ci in cube] doesn't seem to convert to a list either.

Is there any appetite for adding a method to the cube class to do the conversion (to a list or numpy array) at a lower level? Maybe it exists already or I'm just driving it wrongly...

**Comment by JohannesBuchner** [comment]
Hi @jtlz2,

I am experimenting with a more pythonic API which does the conversion to numpy arrays, perhaps you would like to take a look at the newest version:
https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_solve_demo.py
https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/solve.py
I would be grateful if you could test it and give some comments on how to make it most user-friendly.

Cheers, Johannes

**Comment by jtlz2** [comment]
Hi @JohannesBuchner, Fantastic! Great to see this. I can't quite decide which either.

It's a vast improvement that the prior function now returns cube, and that cube behaves like a numpy array.

The Solver class is neat but perhaps a bit too concise. I'm already starting to embed the prior and loglike functions inside a "model" class, so the standalone prior and loglike functions would be less of a headache.

It's cool to be able to get the solution directly within python.

On balance at the moment I prefer the solve route to the Solver route, but I can see eventually you'd probably want to end up at the latter.

What do other samplers e.g. emcee do? I've always liked cube. One can only hope for true plug-and-play samplers....

Thanks! Jon

**Comment by JohannesBuchner** [comment]
Ok, I might stick to solve, but please do not consider this part of a stable API yet.

>What do other samplers e.g. emcee do? 

emcee first sets up the sampler parameters in the initialiser. Then there is a run_mcmc command, which makes sense to call more than once for burn-in (if you believe burn-in is a good thing). For MultiNest that does not make sense, you just run it (and not running does not make sense).

>I've always liked cube. 

I did not understand this. Is there a project named cube?

>One can only hope for true plug-and-play/hot-switching....

Not sure I pointed this out to you already, but this project does exactly this: https://johannesbuchner.github.io/jbopt/doc.html 

Thank you for the feedback.
