### ISSUE TITLE
libcuba.so is not made

### ISSUE THREAD

**Issue by Joruis20** [JohannesBuchner/PyMultiNest#241]
Hello!
I tried to install pymultinest in virtual machine (linux).  But when I get to pycuba library creation, it does not make the libcuba.so in the directory when using ./makesharedlib.sh. And I guess that gives me the typical errors:

OSError: libcuba.so: cannot open shared object file: No such file or directory

I attach screenshots. 
![WhatsApp Image 2023-09-05 at 19 41 09](https://github.com/JohannesBuchner/PyMultiNest/assets/144056583/ff1ec560-2eec-4749-91d3-ad0b3212474d)
![WhatsApp Image 2023-09-05 at 19 41 09(1)](https://github.com/JohannesBuchner/PyMultiNest/assets/144056583/61462bb5-fc9a-4971-9c88-664ced958994)

On the other hand, I have confusion with the line: export LD_LIBRARY_PATH=$HOME/Downloads/MultiNest/lib:$HOME/Downloads/cuba/directory/:$LD_LIBRARY_PATH. Since I don't know if the $HOME/ should be replaced by the name given by the pwd command. I am using the following way:

export LD_LIBRARY_PATH=$HOME/user/pymultinestandcuba/MultiNest/lib:$HOME/user/pymultinestandcuba/cuba/:$LD_LIBRARY_PATH

Another attempt I used:

echo 'export LD_LIBRARY_PATH=$/home/user/pymultinestandcuba/MultiNest/lib:$/home/user/pymultinestandcuba/cuba/:$LD_LIBRARY_PATH' >>~/.bashrc

And it only worked with pymultinest but not with pycuba. I've been trying several times downloading and deleting the .git's to see if I'm wrong. 

Can you help me please?

**Comment by JohannesBuchner** [comment]
Yeah, this stopped working a while ago and I don't know why or how to fix it.

**Comment by JohannesBuchner** [comment]
Please comment/open an issue here: https://github.com/JohannesBuchner/cuba
