### ISSUE TITLE
Problem converging at the edge of the prior

### ISSUE THREAD

**Issue by sumitaghosh** [JohannesBuchner/PyMultiNest#252]
When I try to run on an asimov dataset with one parameter set to 0, PyMultiNest never seems to consider 0 as an option?

**Comment by JohannesBuchner** [comment]
Closing for now, not enough information provided. Please give a minimal code example that reproduces the issue.

**Comment by sumitaghosh** [comment]
I have done so! Please reopen this issue @JohannesBuchner and thank you for the instructions!

**Comment by JohannesBuchner** [comment]
Can you plot the posterior probability distribution? The results look like expected to me: Your prior on the first variable is forced to be non-negative. Keep in mind when working with probability distributions, the probability of any specific value (such as zero) is zero.

**Comment by sumitaghosh** [comment]
![testmarg](https://github.com/JohannesBuchner/PyMultiNest/assets/5379095/630b60b1-63a7-4aa5-bd04-258b31372567)

I expected the error to be equal to the mode so that the value was consistent with zero, so thanks for explaining why that's not correct!

**Comment by sumitaghosh** [comment]
I have an unrelated issue I haven't been able to solve with google. I ran another asimov dataset with more parameters, and it seems to be stuck in a loop (running 13+ hours so far). I think the problem is that the evidence keeps registering as something really large, so the following is repeating over and over:

```
Importance Nested Sampling ln(Z):            NaN +/-       NaN
Acceptance Rate:                        0.497320
Replacements:                             869800
Total Samples:                           1748975

```
I think this is happening because my second parameter has gotten stuck on the value -0.437431652236425247E+11 (when I check the .txt file, this is what I see in the second column), but I don't know how this is possible when my prior defines this parameter as `theta[1] = uniform[1] * 5000000`.

Do you know why this could be happening, and what I can do to fix it? What would cause a number that can't go below 0 or above 5e6 become -4e10? Thank you for your help!

**Comment by JohannesBuchner** [comment]
maybe put some prints in your likelihood to see what it is doing. Maybe some asserts too.
