### ISSUE TITLE
Proper log prior

### ISSUE THREAD

**Issue by nmearl** [JohannesBuchner/PyMultiNest#33]
I'm using pymultinest to explore a big parameter space (27 independent parameters). Some of the parameters can range from 10.0 to 1.0e-6. Generally, all I've done in the prior function is multiple e.g. cube[0] by 10.0, so that the parameter space is [0, 10.0]. But I'm thinking this might misrepresent the potential values, as really small values may never be explored. Do you recommend a better way to do this type of exploration? Thanks!

**Comment by JohannesBuchner** [comment]
Please re-open if you still have this problem.

**Comment by surgithub** [comment]
Hi, I am new to pymultinest, and quite confused with the priors. As I understand, for uniform prior in the range [0,2], the command is
cube[0] = cube[0]*2

What I need to use in case my prior range lies in some negative range? For instance, I wish to assign uniform prior in the range [-5,2].

Thanks.

**Comment by smfactor** [comment]
Cube is on the range [0,1] so to get [-5,2] expand the range to 7 and subtract 5

cube[0]=cube[0]*7 - 5

**Comment by JohannesBuchner** [comment]
Right. In general:

`cube[0] = cube[0] * (hi - lo) + lo`

**Comment by surgithub** [comment]
Thanks. 

One more doubt. I have a three parameters model where one parameter is likely to be very close to 0, it could be any real number from 10^-21 to 0.1. When I run pymultinest with the uniform prior range [0,10^-10], I get a constraint of the order 10^-15 with a warning that the convergence is towards the edge of the parameter prior range. When I reduce the prior range to [0,10^-14], I again get the constraint of the order 10^-15 but this time without any warning message. What should I infer from these results? Am I doing the correct thing to explore the parameter range? Do I need to use the log prior? If yes, please also write how to use the log prior to sample the full range [0,0.1] of the parameter. Thanks.

**Comment by JohannesBuchner** [comment]
Yes, use a log prior. What I typically do is to use a log parameter in the prior transform:

`cube[0] = cube[0] * 21 - 22`

in your likelihood function, you receive this parameter and transform it to linear space:

```
loga, b, c = params
a = 10**loga
```

Alternatively, you can directly use `cube[0] = 10**(cube[0] * 21 - 22)` in the prior transform, but the solution above also makes the output easier to read and marginal/corner plots prettier.
