### ISSUE TITLE
PEP8 Compliance

### ISSUE THREAD

**Issue by gns-ank** [JohannesBuchner/PyMultiNest#34]
I was wondering if there is any interest in making the code-base PEP8 compliant? PEP8 is the style guide for python programming:

http://legacy.python.org/dev/peps/pep-0008/

There are many tools, which check the code for errors and they highlight PEP8 compliance errors. For example for `vim` there is `syntastic` plugin, which can use `pylint` or `flakes8` tools which can check the code on the fly.

Of course PEP8 document is not a law, IMHO following established practices would be helpful in some cases (for example py3k porting)

If you would accept patches on making the code PEP8 compliant, I would be willing to contribute!

**Comment by JohannesBuchner** [comment]
I will close this now. If you have problems running with Python3, please open a new bug and I will fix it. Thank you.
