### ISSUE TITLE
Python 3 support and `file` builtins

### ISSUE THREAD

**Issue by aignas** [JohannesBuchner/PyMultiNest#35]
I saw, that in the progress watcher `file` builtins are used. However, they [were removed from Python 3](http://stackoverflow.com/questions/16736833/python-nameerror-name-file-is-not-defined).

I will send a PR once I have more time.

**Comment by JohannesBuchner** [comment]
I made a systematic search and I think I got all file() calls now in the latest version. Please open a new bug if you have problems with running with Python3.
