### ISSUE TITLE
Small MPI bug - Calling MPI_Init or MPI_Init_thread twice is erroneous.

### ISSUE THREAD

**Issue by innisfree** [JohannesBuchner/PyMultiNest#38]
Hello, I think I found a bug running PyMultiNest in MPI.  I use your cmake version of MuliNest. Without MPI, 

        python pymultinest_demo_minimal.py

the code runs as expected. But with MPI, 

	 mpirun -np 2 python pymultinest_demo_minimal.py 
	Error starting MPI. Terminating.
	--------------------------------------------------------------------------
	MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD 
	with errorcode 16.

	NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
	You may or may not see output from other processes, depending on
	exactly when Open MPI kills them.
	--------------------------------------------------------------------------
	--------------------------------------------------------------------------
	Calling MPI_Init or MPI_Init_thread twice is erroneous.
	--------------------------------------------------------------------------
	Error starting MPI. Terminating.
	--------------------------------------------------------------------------
	mpirun has exited due to process rank 1 with PID 9249 on
	node andrew-laptop exiting without calling "finalize". This may
	have caused other processes in the application to be
	terminated by signals sent by mpirun (as reported here).
	--------------------------------------------------------------------------
	[andrew-laptop:09247] 1 more process has sent help message help-mpi-api.txt / mpi-abort
	[andrew-laptop:09247] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

I suspect that the problem is in `run.py`

	libname = 'libmultinest.so'
	try: # detect if run through mpiexec/mpirun
		from mpi4py import MPI
		if MPI.COMM_WORLD.Get_size() > 1: # need parallel capabilities
			libname = 'libmultinest_mpi.so'
	except ImportError:
		pass

That code is attempting to initialise MPI twice. With simply, 

	libname = 'libmultinest_mpi.so'

I have no problems.

**Comment by JohannesBuchner** [comment]
Dear @innisfree,
I have just released an update to PyMultiNest, which includes a fix to this (setting init_MPI to False by default, and some documentation). If you can, please upgrade and test it.
Thank you, Johannes
