### ISSUE TITLE
Segfault in MULTINEST

### ISSUE THREAD

**Issue by drJfunk** [JohannesBuchner/PyMultiNest#41]
I have a class that wraps pymultinest so that I can build likelihoods on the fly:

------------------------------------------------------------------

class mnfit:

    def __init__(self,silent=False):

        self.silent = silent
        self.n_live_points = 10
        self.importance_nested_sampling = True
        self.resume = False
        self.verbose = True
        self.sampling_efficiency = 'model'
        

    def LoadData(self):

        pass

    def Explore(self):
        '''
        This member function invokes multinest.
        The data must be loaded and the likelihood set
        '''
        if not os.path.exists("chains"): os.mkdir("chains")
        
        # we want to see some output while it is running
        if not self.silent:
            print "SILENT"
            progress = pymultinest.ProgressPlotter(n_params = self.n_params); progress.start()
            threading.Timer(2, show, ["chains/1-phys_live.points.pdf"]).start() # delayed opening

        # run MultiNest
        pymultinest.run(self.likelihood, self.prior, self.n_params, importance_nested_sampling = self.importance_nested_sampling, resume = self.resume, verbose = self.verbose, sampling_efficiency = self.sampling_efficiency, n_live_points = self.n_live_points, init_MPI=False)

        # ok, done. Stop our progress watcher
        if not self.silent:
            progress.stop()

--------------------------------------------------

Since the run function expects a likelihood and prior with 3 arguments, I have a function that creates a call back:

----------------------------------------------------------------------------------------
    def ConstructLikelihood(self):
        '''
        Provides a likelihood function based off the data and
        model provided. This function is fed to MULTINEST.

        '''

        # The Likelihood function for MULTINEST
        def likelihood(params, ndim, nparams):

            
            logL = 0. # This will be -2. * log(L)
            for det,mod,lh in zip(self.detList,self.models,self.lhs):
                
                
                # Here the model's params are set and the
                # and the matrix is convolved to get
                # model counts
                
                mod.SetParams(params) #set params for the models
                modCnts = mod.GetModelCnts() # convolve the matrix and ret counts

                lh.SetModelCounts(modCnts[det.activeLoChan:det.activeHiChan+1]) #pass model counts to lh

                # Here the DataBin objects' source and background
                # counts are sent to the likelihood object

                lh.SetBackGround(det.bkg[det.activeLoChan:det.activeHiChan+1],det.berr[det.activeLoChan:det.activeHiChan+1])
                lh.SetCounts(det.source[det.activeLoChan:det.activeHiChan+1])

                #This is log(L) so the joint stat is an addition
    

                logL+=lh.ComputeLikelihood()
            #print "logL = %f"%logL
            jointLH = exp(-0.5*(logL))
                
            return jointLH
        
        # Because this is inside a class we want to create a
        # likelihood function that does not have an object ref
        # as an argument, so it is created here as a callback
        
        self.likelihood = likelihood
        self.prior = self.models[0].prior
---------------------------------------------------------------------

However, while running all the demos and examples results in success, I get the following output when I run the code:

 *****************************************************
 MultiNest v3.4
 Copyright Farhan Feroz & Mike Hobson
 Release Oct 2013

 no. of live points =   10
 dimensionality =    4
 *****************************************************
 Starting MultiNest
 generating live points
[pool12:30332] *** Process received signal ***
[pool12:30332] Signal: Segmentation fault: 11 (11)
[pool12:30332] Signal code: Address not mapped (1)
[pool12:30332] Failing at address: 0x7fee62c00000
[pool12:30332] [ 0] 0   libsystem_platform.dylib            0x00007fff8884a5aa _sigtramp + 26
[pool12:30332] [ 1] 0   ???                                 0x000000010154db90 0x0 + 4317305744
[pool12:30332] [ 2] 0   Python                              0x00000001004ba2c7 PyObject_Call + 99
[pool12:30332] [ 3] 0   Python                              0x0000000100502fdf slot_sq_item + 210
[pool12:30332] [ 4] 0   Python                              0x00000001004da78b iter_iternext + 33
[pool12:30332] [ 5] 0   Python                              0x00000001004b9d3c PyIter_Next + 16
[pool12:30332] [ 6] 0   Python                              0x00000001004b9bc6 PySequence_Tuple + 240
[pool12:30332] [ 7] 0   Python                              0x00000001004fb7ed tuple_new + 206
[pool12:30332] [ 8] 0   Python                              0x00000001004fc81b type_call + 50
[pool12:30332] [ 9] 0   Python                              0x00000001004ba2c7 PyObject_Call + 99
[pool12:30332] [10] 0   Python                              0x0000000100536951 PyEval_EvalFrameEx + 13138
[pool12:30332] [11] 0   Python                              0x0000000100539aa5 fast_function + 192
[pool12:30332] [12] 0   Python                              0x00000001005365bb PyEval_EvalFrameEx + 12220
[pool12:30332] [13] 0   Python                              0x0000000100539aa5 fast_function + 192
[pool12:30332] [14] 0   Python                              0x00000001005365bb PyEval_EvalFrameEx + 12220
[pool12:30332] [15] 0   Python                              0x0000000100539aa5 fast_function + 192
[pool12:30332] [16] 0   Python                              0x00000001005365bb PyEval_EvalFrameEx + 12220
[pool12:30332] [17] 0   Python                              0x000000010053346e PyEval_EvalCodeEx + 1612
[pool12:30332] [18] 0   Python                              0x00000001004d818f function_call + 349
[pool12:30332] [19] 0   Python                              0x00000001004ba2c7 PyObject_Call + 99
[pool12:30332] [20] 0   Python                              0x00000001005362bf PyEval_EvalFrameEx + 11456
[pool12:30332] [21] 0   Python                              0x000000010053346e PyEval_EvalCodeEx + 1612
[pool12:30332] [22] 0   Python                              0x00000001004d818f function_call + 349
[pool12:30332] [23] 0   Python                              0x00000001004ba2c7 PyObject_Call + 99
[pool12:30332] [24] 0   Python                              0x000000010053924b PyEval_CallObjectWithKeywords + 93
[pool12:30332] [25] 0   _ctypes.so                          0x000000010103c9f3 closure_fcn + 446
[pool12:30332] [26] 0   _ctypes.so                          0x00000001010422a0 ffi_closure_unix64_inner + 520
[pool12:30332] [27] 0   _ctypes.so                          0x0000000101041946 ffi_closure_unix64 + 70
[pool12:30332] [28] 0   libmultinest.so                     0x0000000101cc04e5 __nested_MOD_gen_initial_live + 6288
[pool12:30332] [29] 0   libmultinest.so                     0x0000000101cc1a81 __nested_MOD_nestsample + 3821
[pool12:30332] *** End of error message ***
Segmentation fault: 11

My thoughts are that this is some problem with referencing in the python objects. Thanks for any help you can provide!

**Comment by JohannesBuchner** [comment]
I am experimenting with a more pythonic API which does the conversion to numpy arrays, perhaps you would like to take a look at the newest version:
https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_solve_demo.py
https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/solve.py
