### ISSUE TITLE
Bug in _read_table?

### ISSUE THREAD

**Issue by jrka** [JohannesBuchner/PyMultiNest#44]
Hi, we encountered an issue in the analyse.py script.  Specifically, the problem was in:

mode['maximum'] = self._read_table(modelines[1])[:,1].tolist()

Looking at _read_table, the following text block:

Maximum Likelihood Parameters
Dim No.     Parameter 
1    123
2   123

(being approximate, obviously) is split up into title and table, but then the line:

header, table = txt.split("\n", 1)

splits the ORIGINAL txt input, not the new "table" that is now 3 lines.  Should this line read:

header, table = table.split("\n", 1)?

Interestingly I do not encounter this error with numpy 1.7.1, but my colleague does using 1.5.1.  The if statement in loadtxt2d does not seem to adequately fix the problem of trying to input the string line "Dim", as a conversion to float error results.

**Comment by JohannesBuchner** [comment]
Dear Julia,
Sorry it took so long. I have now released an update to PyMultiNest, which includes a fix to this problem. Could you please upgrade and test it?
Thank you, Johannes
