### ISSUE TITLE
Issue with likelihood function being a method

### ISSUE THREAD

**Issue by timothydmorton** [JohannesBuchner/PyMultiNest#47]
In run.py, there is some code that checks the number of arguments that the likelihood function takes, and decides whether or not to use the 'lnew' variable or not.  This doesn't have the desired behavior if the likelihood function is a method, in which case it "takes" one more argument by default (self).  I've hacked a quick solution using inspect.ismethod() for my current purposes, but a real solution would be desirable.

Thanks!

**Comment by JohannesBuchner** [comment]
Hey,
I just released an update to PyMultiNest, which includes a fix to this problem. Could you upgrade and test it?
Thank you, Johannes

**Comment by JohannesBuchner** [comment]
Closing, I think this is fixed.
