### ISSUE TITLE
Test script using mpi

### ISSUE THREAD

**Issue by suvenduat** [JohannesBuchner/PyMultiNest#49]
Hi Johannes,

I am having problem to run pymltinest using MPI. Without MPI, everything is perfect.
I got the same error like issues 6 using the same demo script:
https://github.com/JohannesBuchner/PyMultiNest/issues/6
I think MPI is correctly install in server. 
I could not get what modification I should make to run it properly.
Could you please help me to solve this problem? Thank you.

Regards,
Suvendu Rakshit

**Comment by JohannesBuchner** [comment]
Dear Suvendu,
I just released an update to PyMultiNest, which includes a fix to this problem. Could you upgrade and test it?
Thank you, Johannes

**Comment by suvenduat** [comment]
Dear Johannes,
I just installed and tested. It's working perfectly.

Cheers,
Suv
