### ISSUE TITLE
How to compile Cuba and APEMoST

### ISSUE THREAD

**Issue by zhaottcrystal** [JohannesBuchner/PyMultiNest#53]
I have a question when installing PyMultiNest, in the tutorial you mentioned that we should get and compile Cuba and APEMoST, after that we will get libcuba.so and libapemost.so.

However I am not sure if I compile them in the right way. I download both Cuba and APEMoST and then extract them from the tar.gz file. Is this what you mean by compiling it? 
The thing is that after I do this, I do not have a libcuba.so and libapemost.so, do you mind providing some help on this?  Thank you very much!

I am using a mac with Yosemite system 10.10.3.

**Comment by JohannesBuchner** [comment]
Hi @zhaott

If you want to use pycuba, you need to compile cuba. If you want to use pyapemost, you need to compile apemost. If you only want to use pymultinest, you only need to compile MultiNest. Each of the libraries has documentation on how to compile.

I think you are only interested in pymultinest, so compile MultiNest with cd build; cmake ..; make

**Comment by zhaottcrystal** [comment]
I see! Thanks for your quick reply! Yes, I am only interested in pymultinest for now.
