### ISSUE TITLE
Linux version of code produces infinities in likelihood evaluations

### ISSUE THREAD

**Issue by wkerzendorf** [JohannesBuchner/PyMultiNest#54]
This strangely enough works on Macs. The python function seemingly gives the same output. We use the newest version of the libraries. 

I think it's possibly related to this line of code that splits the model_param into a numpy array:

``` python
def multinest_evaluate(self, model_param, ndim, nparam):
    # returns the likelihood of observing the data given the model param_names
    model_param = np.array([model_param[i] for i in xrange(nparam)])
```

**Comment by JohannesBuchner** [comment]
In your likelihood function, print out the parameters and the likelihood. Probably you compute infinite likelihoods.

**Comment by wkerzendorf** [comment]
@JohannesBuchner Yes, I'm sure that is the case. However it is also exploring the model_space outside my uniform priors, which does not make sense. I believe under mac the way to unpack the `model_param` is like the way we I show, but I think this is might be different under linux. My question is - how to unpack -convert to an actual numpy array - the `model_param` in linux

**Comment by JohannesBuchner** [comment]
That should be of course platform independent.
Check what the conversion in your prior does what you think it should do and make sure you have compiled MultiNest on Mac with an empty build directory.

**Comment by wkerzendorf** [comment]
It works problem free on Mac. Linux is the issue. I'm wondering - how do you convert the parsed in parameters to list or arrays?

**Comment by JohannesBuchner** [comment]
The same way.

**Comment by JohannesBuchner** [comment]
Did you recompile on Linux?

**Comment by JohannesBuchner** [comment]
Can you post your prior function?

**Comment by wkerzendorf** [comment]
Of course - the binaries are incompatible.
