### ISSUE TITLE
Typo line 38 of analyse.py, "seperate" --> "separate"

### ISSUE THREAD

**Issue by jrka** [JohannesBuchner/PyMultiNest#60]
Super quick problem. Line 38 of analyse.py reads:

    self.post_file = "%spost_seperate.dat" % self.outputfiles_basename

But pretty sure it should be _separate.dat (an e should be an a).

**Comment by JohannesBuchner** [comment]
Thanks. Fixed in commit 8dace434c4e3fb818a6e760f59f3c254b1502334
