### ISSUE TITLE
Problem with mpi and pypolychoord

### ISSUE THREAD

**Issue by bsafdi** [JohannesBuchner/PyMultiNest#62]
First, thanks a lot for pypolychord--I have it running on my personal computer (OSX 10.10.4), and it seems to work great--even when using mpi.  I am now trying to run pypolychord on a remote (Linux) cluster, and I am running into some difficulties with the installation.  Here are the steps I followed. 
1.  I installed PolyChord from your github page.  On the cluster, we have gcc 4.4.7, so in the makefile I changed the flag -OFast to -O3 (which I think should be ok?).  Then, I compiled via repeated use of `make COMPILER_TYPE=gnu --keep-going` and `make libchord.so`.  Then, inside of the `src/` directory I see the file `libchord.so`.  I added the path to the `src/` directory to my `$LD_LIBRARY_PATH` (which also contains the path to `openmpi-1.8.4/lib`.  I should say that I do use pymultinest on this cluster with mpi regularly without issue.
2.  I pull a fresh version of pymultinest from github and run `python setup.py install`.  Everything seems to work ok and I verify that I can still run pymultinest with mpi.  Then, I try running the example `pypolychord_demo.py` and I get the error `problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_`. 
3.  When I compile PolyChord without mpi, this example does seem to run.  However, the reason I am trying to run PolyChord on this cluster is precisely so that I can use mpi.  

Do you have any ideas what might be causing this problem?  Thanks a lot.

**Comment by JohannesBuchner** [comment]
Do you run the example with mpiexec?

**Comment by bsafdi** [comment]
I have tried running the example multiple ways.  For example, I have tried `python pypolychord_demo.py ` and `mpiexec -np 2 python pypolychord_demo.py`.  Each time, I get the same error about `undefined symbol: mpi_comm_split_`.

**Comment by smsharma** [comment]
We are having the same issue on a different Linux cluster. The steps for installation were similar to what @bsafdi used, except for using a later version of gcc (`gcc version 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC)`).

We compile repeatedly with `make --keep-going` and `make --keep-going libchord.so` (`COMPILER_TYPE=gnu` and `MPI=1` in the `Makefile`). Then, trying the pypolychord demo `pypolychord_demo.py` we get 
```bash
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
```
Using mpirun or mpiexec gives the same error. With mpirun: 
```bash
11:30:11 pypolychord_test/# mpirun -np 3 python pypolychord_demo.py
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
problem:  /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
```
With mpiexec:
```
mpiexec -np 3 python pypolychord_demo.py
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
problem: /path/to/PolyChord/src/libchord.so: undefined symbol: mpi_comm_split_
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58865,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```
The demo runs fine if the `MPI` flag is left blank, but we are also trying to parallelize using MPI (expecting performance gain over MultiNest). Thanks!

**Comment by JohannesBuchner** [comment]
It seems like something is different in your environment/libraries between compiling in MPI (compiler libraries) and running the compiled program (mpiexec libraries). If you search the web for the error message (undefined symbol: mpi_comm_split_), you can find many examples where this occurs -- perhaps this helps you track it down.

**Comment by smsharma** [comment]
As suggested on googling the error, we tried compiling a local version of OpenMPI (`openmpi-1.8.8`) with `./configure CC=icc CXX=icpc FC=ifort`. 

Then, using this OpenMPI and same Intel compilers to make PolyChord as before. Compilation goes as previously, but trying the polychord demo as above gives
```
problem: /group/hepheno/heptools/PolyChord/src/libchord.so: undefined symbol: for_random_seed_put
```
So it does seem like a problem with compiler support or mismatch. Maybe a particular compiler configuration for MPI as well as compiling PolyChord is necessary?

**Comment by JohannesBuchner** [comment]
Maybe try the upstream polychord version, they have some python wrapper now.
