### ISSUE TITLE
Differing results when using MPI and when not using MPI

### ISSUE THREAD

**Issue by timothyb0912** [JohannesBuchner/PyMultiNest#63]
Hi Johannes, thanks a lot for all your work in creating pyMultiNest. I am having two problems when using MPI with pyMultiNest. 

First, I get different results when running a script with "python myscript.py" versus "mpiexec -np 4 python myscript.py"

When using multiple runs of "python myscript.py", the obtained values for the Nested Importance Sampling Global Log-Evidence remains constant within the stated uncertainty levels. For instance, in two consecutive runs of the program I got Nested Importance Sampling Global Log-Evidence values of -0.235946993850485569E+03  +/-    0.509516822040398474E-02 and
-0.235958914421485247E+03  +/-    0.521426870205363244E-02.

However, when I execute the same model with "mpiexec -np 4 python myscript.py" I obtain the following Nested Importance Sampling Global Log-Evidence results in two consecutive runs:
-0.405465108108165329E+00  +/-    0.182574185835054983E-01 and
0.878422046894200300+248  +/-    0.999874992186523315E+00
Both of these results are quite wrong. The results obtained with "python myscript.py" are much more likely to be correct.

Do you have any advice about what I can do to figure out why the given results differ and how to make the results remain consistent across execution methods? I would like to be able to use MPI to speed up the run time for the evidence estimation with MultiNest and PolyChord.

Secondly, when using "python myscript.py", the command line is always "freed" once MultiNest finishes its execution and exits. When using "mpiexec -np 4 python myscript.py", the command line is not released for further use, even when MultiNest prints "Sampling Finished. Exiting MultiNest." Do you have any idea what might be causing this behavior?

Let me know if there are any outputs of logs that you would like me to post, if that will help solve the MPI/MultiNest issues.

Thanks for your help,
Timothy

**Comment by JohannesBuchner** [comment]
When you run "mpiexec -np 4", four individual python processes are launched. Each of them enter MultiNest, and at the end leave MultiNest, and continue executing until the end of the script.
You can use py4mpi to find out the rank of your MPI process and terminate the ones that are not 0.
Alternatively (and this is what I usually do) move postprocessing to another script (or give myscript.py command line options, e.g. "run", "analyse").

Regarding your first question you will have to hunt down what your likelihood calls return to MultiNest. the ".txt" file stores many of them. I assume they have 1e300 values. Perhaps you have some python code that can not deal with the parallelisation? 
Try to run the demo code with MPI to see if you have trouble there as well.

**Comment by timothyb0912** [comment]
Thanks for the very quick reply! 

I am getting the impression that my issues may just be because I have never used MPI before. When I saw on the documentation page that "PyMultiNest detects that it is run with multiple cores and will load the “libmultinest_mpi” library instead. No further modifications are necessary," I thought that this meant I could take my script that runs with "python myscript.py" and simply put "mpiexec -np 4" in front of it when executing it from the command line.

I didn't realize that I would actually have to modify my code to explicitly handle the fact that 4 processes would be, for instance, trying to access the same array in memory. This, in hindsight, was probably very silly. The code that I was using is attached below.  You are right, I do have values in the range of 1e300.

Would it be possible for you to post an example of a code that uses MPI with MultiNest and handles communication between the processes? It's okay if that is too much work to dig up such an example.

The code I was using is below:
=============================================================
import os
import time
import json
import mpi4py
import numpy as np
import pandas as pd
import pymultinest as pmn             # Used to access the MultiNest software


# Specify the path to the output folder
relative_output_folder = "mpi_binary_logit_for_comparison/"

# Try to make the output folder
try:
    os.makedirs(relative_output_folder)
except OSError:
    # but if it exists, then just keep going
    # If the folder does not exist and we cannot make it, raise an error
    if not os.path.isdir(relative_output_folder):
        raise

# Define boundary values for the calculations
max_comp_value = 1e300
min_comp_value = 1e-300

# If we are going to use a uniform distribution, assign the upper and lower
# limits of the distribution
upper_uniform_limit = 20
lower_uniform_limit = -20

# Read in the necessary data for the model
path_to_pkl_of_data = "expanded_hybrid_specification_df.pkl"
raw_data = pd.read_pickle(path_to_pkl_of_data)

# Specify a choice column
choice_col = "bike_choice"

# Make sure the choice column is in the data
assert choice_col in raw_data.columns.tolist()

# Make sure the data has an intercept column
raw_data['intercept'] = 1.0

# Specify the explanatory variables, i.e. the number of dimensions to estimate
explanatory_vars = ['intercept',
                    'bike_time',
                    'num_bikes',
                    'num_cars',
                    'age',
                    'gender',
                    'education_status_2',
                    'education_status_3',
                    'education_status_4',
                    'education_status_5',
                    'education_status_6',
                    'standardized_income']

# Make sure all the explanatory variables are in the dataframe                    
assert all([x in raw_data.columns.tolist() for x in explanatory_vars])
                    
# Create a numpy array of the data for which we want estimated coefficients
model_data = np.array(raw_data[explanatory_vars])

# Create a numpy array containing the individual outcomes
choice_vector = raw_data[choice_col].values

# Record the number of parameters/dimensions being estimated in this model
num_dimensions = len(explanatory_vars)

# Define the number of live points to be used
num_live_points = 1000

# Define the sampling efficiency that is desired
desired_sampling_efficiency = 0.5

# Create function that converts the prior cube into the parameter cube
def uniform_prior(cube, n_dim, n_params):
    # Note that we are using a uniform distribution over all parameters    
    for i in range(n_dim):
        cube[i] = ((upper_uniform_limit - lower_uniform_limit) * cube[i]) +\
                  lower_uniform_limit
        
    return None
        

# Create a function that estimates the log likelihood
def binary_logit_log_likelihood(cube, n_dim, n_params):
    # Create an array of the coefficients
    betas = np.array([float(cube[i]) for i in range(n_dim)])
    
    # Calculate the systematic utility of choice y = 1
    # Resulting array should be of shape (n_obs,)
    sys_utility = model_data.dot(betas)
    
    # Calculate the total log-likelihood
    log_likelihood = (choice_vector * sys_utility -
                      np.log(1.0 + np.exp(sys_utility))).sum()
                      
    return log_likelihood
    

# Create a main function so that the script can be run
# from the command line as well as from within other
# scripts or from an ipython notebook
def main():
    # Begin timing the estimation process
    start_time = time.time()
    
    # Run the MultiNest software
    pmn.run(binary_logit_log_likelihood, uniform_prior, num_dimensions,
            outputfiles_basename=relative_output_folder,
            n_live_points=num_live_points,
            sampling_efficiency=desired_sampling_efficiency,
            log_zero=-1e200,
            mode_tolerance=-1e180,
            null_log_evidence=-1e180,
            resume=False, verbose=True, init_MPI=False)
            
    # Record the ending time of the estimation process
    end_time = time.time()
    tot_minutes = (end_time - start_time) / 60.0
            
    # Save the parameter names
    with open(relative_output_folder + "parameter_names.json", 'wb') as f:
        json.dump(explanatory_vars, f)
        
    # Save the number of live points used as the total estimation time
    model_run_params = {"n_live_points": num_live_points,
                        "sampling_efficiency": desired_sampling_efficiency,
                        "estimation_minutes": tot_minutes}
    with open(relative_output_folder + "model_run_parameters.json", "wb") as f:
        json.dump(model_run_params, f)
        
    # Print a report on how long the estimation process took
    print "Estimation process took {:.2f} minutes".format(tot_minutes)

if __name__ == "__main__":
    main()

**Comment by timothyb0912** [comment]
An update: When I use "mpiexec -np 2 python pymultinest_demo_minimal.py"
I get the following output:
MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 Starting MultiNest
 generating live points

The program then remains at that point. It seems that my issue of not being able to use multinest includes the demo file as well.

**Comment by JohannesBuchner** [comment]
No, no you should not need to modify your code, MPI should work automagically when you use mpiexec.

I just thought maybe you do something strange in your likelihood function, such as read/write files and then the various processes might confuse each other.

**Comment by JohannesBuchner** [comment]
Can you put some print statements in the likelihood function of pymultinest_demo_minimal.py?

**Comment by timothyb0912** [comment]
Hey Johannes,
Sorry I haven't responded sooner! I'll be out for most of this week and away from my work computer, but I'll totally come back to investigating the MPI issues as soon as I return on the weekend.

Thanks again for your help,
Timothy

**Comment by vlas-sokolov** [comment]
In case it helps anyone, I can reproduce a similar behavior, although I'm not a 100% sure this is what happened to the OP. MultiNest output below is stuck in a [race condition](http://stackoverflow.com/questions/34510/what-is-a-race-condition), where both processes passed the `os.path.exists` check but one was late to the mkdir party.

```
(0)user@server:/tmp/tests$ mpiexec -n 2 python pymultinest_demo_minimal.py
Traceback (most recent call last):
  File "pymultinest_demo_minimal.py", line 5, in <module>
    os.mkdir("chains")
OSError: [Errno 17] File exists: 'chains'
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    2
 *****************************************************
 Starting MultiNest
```
This then freezes at 100% CPU usage. I added an extra try-except-pass block to bypass this.

**Comment by jtlz2** [comment]
@JohannesBuchner Somewhat related: I've been getting very different evidence values depending on the number of MPI processors used. Have you ever seen this? Any idea what might cause it?

**Comment by JohannesBuchner** [comment]
@vlas-sokolov : Yes, that means one process dies and the other is waiting for it. In principle you would need to make sure it is rank 0 that checks&creates the directory (and also afterwards, does the post-processing analysis). In practice you can kill it and run it again.

@jtlz2, no I haven't. Are you using random numbers in your likelihood? or do you have any I/O in it? Would be interesting if you can reproduce with a minimal C/Fortran program and report upstream.

**Comment by jtlz2** [comment]
@JohannesBuchner Here you go - in python - the only randomness is from the sampler seed, so do you think it is just that? Run as:

mpirun -n 4 ./straightline.py


#!/usr/bin/env python

"""
This is straightline.py
Jonathan Zwart
September 2017
"""

from mpi4py import MPI
import os,sys
import importlib
import numpy
from math import pi,exp,log,sqrt,log
import pymultinest
from scipy.special import erf

# Constants
sqrtTwo=sqrt(2.0)

if __name__ == '__main__' and len(sys.argv) < 1:
    print 'usage:'
    print
    print 'with MPI [NB mpiEXEC on some machines]:'
    print '       mpiexec -n NPROC ./straightline.py'
    print
    sys.exit(0)

#-------------------------------------------------------------------------------

# Inputs
outdir='chains'
# Set some MultiNEST parameters here
#n_live_points=1000
multimodal=False
max_modes=1
seed=1234 # [-1 for clock]

# Switch to INS
do_INS=False
n_live_points=500
#n_live_points=1000
outstem='1-'

max_iter=0
evidence_tolerance=0.5

#-------------------------------------------------------------------------------

def myprior(cube, ndim, nparams):
    for i in range(ndim):
        cube[i] = 0.0 + cube[i] * 2.0
    return

#-------------------------------------------------------------------------------


def myloglike(cube, ndim, nparams):
    #global x,y
    # Simple likelihood for straight-line fit (m=1,c=1)
    x  = [0.0487,0.4123,0.3239,0.6892,0.1484,0.2590,0.1030,0.4891,0.3327,0.2881]
    y  = [1.0590,1.3907,1.3730,1.7392,1.0507,1.2138,1.0182,1.4802,1.3847,1.4582]
    sigma=0.1

    loglike=0.0
    for idatum in range(len(x)):
        data=y[idatum]
        model = cube[0]*x[idatum]+cube[1]#+cube[2]*x**2
        chisq = 0.5*((data-model)/sigma)**2.0
        prefactor=0.5*log(2.0*pi*sigma**2.0)
        loglike -= prefactor + chisq

    return loglike

#-------------------------------------------------------------------------------

def main():

    """
    """

    if not os.path.exists(outdir): os.mkdir(outdir)

    n_params=2
    pymultinest.run(myloglike,myprior,n_params,resume=False,verbose=True,\
                multimodal=multimodal,max_modes=max_modes,write_output=True,\
                n_live_points=n_live_points,\
                evidence_tolerance=evidence_tolerance,\
                mode_tolerance=-1e90,seed=seed,max_iter=max_iter,\
                importance_nested_sampling=do_INS,\
                outputfiles_basename=os.path.join(outdir,outstem),init_MPI=False)

    return 0

#-------------------------------------------------------------------------------

if __name__ == '__main__':

    ret=main()
    sys.exit(ret)

**Comment by JohannesBuchner** [comment]
The MultiNest MPI processes are (or should be) seeded internally with different numbers for each different rank. So you will not get the same answer as a single run. What are you observing? That the answers are radically different (far outside the uncertainties)?

**Comment by jtlz2** [comment]
@JohannesBuchner I've run some more tests:

1. My likelihood is independent of the number of cores.
2. Given a fixed number of cores and and sampler seed, runs are exactly repeatable, even across machines (cluster vs laptop).
3. For a simple (straightline-fitting) problem, the scatter in Z as a function of the number of cores is comparable to the estimated sigma_lnZ.
4. For my much more complicated, slower problem, for a fixed number of cores, the scatter in Z as a function of the sampler seed slightly exceeds the estimated sigma_lnZ. Alarmingly, in a single case the inferred Z was (repeatedly) catastrophically different to the consensus - 30 sigma. Do you think this points to a bug in the likelihood, or at one of the lower levels?

I do wonder if there is a communication issue when using so many cores - is there a clear MPI barrier?

**Comment by JohannesBuchner** [comment]
Hi @jtlz2, 

Regarding the MPI issue, I  would not expect that the run behaves the same when the number of processes is varied. If processes are seeded with, say, process_seed=seed*1000 + processnr, for a given seed the run is reproducable, but when the number of processes is increased, it changes.

With your script I get:
no MPI:
 ln(ev)=   6.5300234242781992      +/-   8.8288407568605939E-002
 Total Likelihood Evaluations:         4024
 ln(ev)=   6.5300234242781992      +/-   8.8288407568605939E-002
 Total Likelihood Evaluations:         4024
 ln(ev)=   6.5300234242781992      +/-   8.8288407568605939E-002
 Total Likelihood Evaluations:         4024
MPI -np 4
 ln(ev)=   6.4657832829672541      +/-   8.8042509991895862E-002
 Total Likelihood Evaluations:         3923
 ln(ev)=   6.4657832829672541      +/-   8.8042509991895862E-002
 Total Likelihood Evaluations:         3923
 ln(ev)=   6.4657832829672541      +/-   8.8042509991895862E-002
 Total Likelihood Evaluations:         3923
MPI -np 2 
 ln(ev)=   6.6040541932014056      +/-   8.6929839887863306E-002
 Total Likelihood Evaluations:         4082
 ln(ev)=   6.6040541932014056      +/-   8.6929839887863306E-002
 Total Likelihood Evaluations:         4082
 ln(ev)=   6.6040541932014056      +/-   8.6929839887863306E-002
 Total Likelihood Evaluations:         4082

I think this is normal behaviour.

Regarding the scatter in Z for different seeds:

We too are seeing catastrophic outliers in multinest runs in a test problem we are analysing. I think it has to do with sometimes seeing the small maximum or not. In the write-up we will probably recommend running MultiNest multiple times and not trusting the errors and individual runs so much.

I think this is a limitation of any algorithm, in some problems it can not find the peak if small enough. Drastically increasing nlive may help, Farhan Feroz uses >20000 in some papers.
