### ISSUE TITLE
Cannot import pymultinest with mpi

### ISSUE THREAD

**Issue by kgullikson88** [JohannesBuchner/PyMultiNest#64]
I have been using pymultinest for a few things, and thought I would try it out with mpi. So I installed mpi4py, but now I get this error whenever I try to import pymultinest:

    --------------------------------------------------------------------------
    Sorry!  You were supposed to get help about:
        opal_init:startup:internal-failure
    But I couldn't open the help file:
        /opt/anaconda1anaconda2anaconda3/share/openmpi/help-opal-runtime.txt: No such file or     directory.  Sorry!
    --------------------------------------------------------------------------
    [jayhawk.as.utexas.edu:92856] [[INVALID],INVALID] ORTE_ERROR_LOG: Error in file     runtime/orte_init.c at line 79
    --------------------------------------------------------------------------
    Sorry!  You were supposed to get help about:
        mpi_init:startup:internal-failure
    But I couldn't open the help file:
        /opt/anaconda1anaconda2anaconda3/share/openmpi/help-mpi-runtime: No such file or directory.      Sorry!
    --------------------------------------------------------------------------
    *** An error occurred in MPI_Init_thread
    *** on a NULL communicator
    *** MPI_ERRORS_ARE_FATAL: your MPI job will now abort
    [jayhawk.as.utexas.edu:92856] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

Do you think that means my libmultinest_mpi.so is somehow bad? I am trying to do this on Mac OSX Yosemite.

**Comment by timothyb0912** [comment]
I had the same error and had to do the following:
Uninstall the current version of mpi4py.
Use the commands conda install --channel mpi4py openmpi mpi4py

Anaconda doesn't work well with mpi4py yet, see here:
https://groups.google.com/forum/#!topic/mpi4py/ULMq-bC1oQA 
https://groups.google.com/a/continuum.io/forum/#!msg/anaconda/15F1cVPGRnM/Id0C6naVQHkJ

**Comment by kgullikson88** [comment]
Great, that worked! Unfortunately now I am getting a different MPI error. I'll just open a new issue since your fix gets pymultinest to import and run on a single core again.
