### ISSUE TITLE
Demo script fails with MPI

### ISSUE THREAD

**Issue by kgullikson88** [JohannesBuchner/PyMultiNest#65]
I am trying to get pymultinest going with MPI, but am getting some errors relating to the initialization. The same errors occur when I run the demo script (note that I added a print statement to pymultinest/run.py to print the name of the library it is loading)

    (telfit)kevingullikson: ~/Applications/PyMultiNest $ mpirun -np 2 python pymultinest_demo_minimal.py 
    Using library libmultinest_mpi.dylib
    Using library libmultinest_mpi.dylib
    *** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
    *** This is disallowed by the MPI standard.
    *** Your MPI job will now abort.
    [jayhawk.as.utexas.edu:12914] Local abort before MPI_INIT completed successfully; not able to     aggregate error messages, and not able to guarantee that all other processes were killed!
    *** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
    *** This is disallowed by the MPI standard.
    *** Your MPI job will now abort.
    [jayhawk.as.utexas.edu:12915] Local abort before MPI_INIT completed successfully; not able to     aggregate error messages, and not able to guarantee that all other processes were killed!
    -------------------------------------------------------
    Primary job  terminated normally, but 1 process returned
    a non-zero exit code.. Per user-direction, the job has been aborted.
    -------------------------------------------------------
    --------------------------------------------------------------------------
    mpirun detected that one or more processes exited with non-zero status, thus causing
    the job to be terminated. The first process to do so was:

      Process name: [[595,1],1]
      Exit code:    1
    --------------------------------------------------------------------------

Any ideas what is happening? The script runs fine if I run it without mpi (or with

```
mpirun -np 1 python pymultinest_demo_minimal.py
```

**Comment by JohannesBuchner** [comment]
Strange...

**Comment by JohannesBuchner** [comment]
This seems to be a gcc/gfortran bug that was fixed. Try updating your compiler to 4.8 or later.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59678

**Comment by kgullikson88** [comment]
I have gcc 4.8.1 already on the machine. For good measure, I went ahead and installed openmpi from source instead of through anaconda (in case that version was compiled with an earlier version). Same error.

**Comment by JohannesBuchner** [comment]
Can you go to gcc 4.9?

**Comment by kgullikson88** [comment]
I'll try. It is not my computer, so I will have to get an admin to do it.

**Comment by kgullikson88** [comment]
So after messing around with a bunch of things, I got it working. The main issue was that I installed MultiNest with the system openmpi (in /usr/local/bin), but was using mpi4py from anaconda (which ships with its own openmpi). I went ahead and installed mpi4py with pip so that it links against the same openmpi and now everything works!
