### ISSUE TITLE
How can I compile APEMoST

### ISSUE THREAD

**Issue by neuronphysics** [JohannesBuchner/PyMultiNest#66]
Hi 
I am trying to compile APEMoST but I didn't find enough documentation how it should be done. I just ran 'make all' and got couple of error messages. I will appreciate for an instruction.

**Comment by JohannesBuchner** [comment]
Do you really need APEMoST? There are better mcmc algorithms out there. If you just want the Python interface to MultiNest, you do not need APEMoST.

**Comment by neuronphysics** [comment]
I just want to use the python interface of MultiNest. So I would not need it because in the installation document it is one of the requirement.

**Comment by JohannesBuchner** [comment]
Then you don't need to compile APEMoST. It is only a requirement for PyApemost. You can continue the installation instructions.
