### ISSUE TITLE
Analyse and root data file

### ISSUE THREAD

**Issue by tjgalvin** [JohannesBuchner/PyMultiNest#67]
Hi all,

I really hate posting what is likely a user error, but I am sure it will be quickly pointed out to me what exactly I am doing wrong. 

I'm playing around with pyMultiNest trying to constrain some parameters of some gaussian functions. The code is running and it appears to be converging towards values obtained in other styles of fits (ie. MPFIT). 

When it comes to using the analyze functionality however, it always crashes, whether I use the solver function or the individual run/analyzer functions. The top root file ('chains/1-.txt') contains a single line:

```
    0.100000000000000000E+01    0.492214511874979520E+18    0.112536026884518048E+01    0.125663346855252933E+00    0.282578909402873979E+01    0.229983373121262957E+01   -0.747051388231056990E-01    0.711221314022469286E+01   -0.763428712603578585E+00    0.923789630057448574E-01    0.281137720118304202E+01
```

and nothing more. 

Because the file is a dump of a single array, the analyzing routines fail during the get_stats() function on line 100:

``` python
        for i in range(2, posterior.shape[1]):
```

as posterior only has a shape of (11,) there is nothing to loop through. 

I've tried to trace the code but I don't seem to see where the file gets created (and hence don't know the meaning of these 11 numbers)!

Any hints you could give would be much appreciated.

**Comment by JohannesBuchner** [comment]
That file is created by MultiNest, not PyMultiNest. You can find its meaning in the README file of MultiNest (a copy is here: https://github.com/JohannesBuchner/MultiNest) 
I should put a numpy.atleast_2d around numpy.loadtxt.
Not sure why you only get 1 point out, post your transform and likelihood function.

**Comment by tjgalvin** [comment]
First, big thanks for reply. 
Thanks for pointing me towards the README for multinest, I see now what it should contain. 
As request, my transform function
```python
def return_prior(parinfo):
    def prior(cube):
        min_val = -100
        max_val =  100
        for pos, (val, info) in enumerate(zip(cube, parinfo)):
            if 'limits' in info.keys():
                lim = info['limits']
                if lim[0] is None and lim[1] is None:
                    cube[pos] = (max_val - min_val)*cube[pos] + min_val
                elif lim[0] is not None and lim[1] is not None:
                    cube[pos] = (lim[1] - lim[0])*cube[pos] + lim[0]
                elif lim[0] is None and lim[1] is not None:
                    cube[pos] = (lim[1] - min_val)*cube[pos] + min_val
                elif lim[0] is not None and lim[1] is None:
                    cube[pos] = (max_val - lim[0])*cube[pos] + lim[0]

        return cube
    return prior
```

and my likelihood function
```python
def return_liklihood(x, y, yerr, poly_coeff, model,nparams):
    poly_nomial = np.poly1d(poly_coeff)
    def lnlike(cube):
        temp_spec   = spectraa(lines=model['lines'], redshift=model['redshift'], source=model['name'])
        #http://stats.stackexchange.com/questions/112451/maximum-likelihood-estimation-mle-in-layman-terms
        #Remember the variance/yerrors are already var**2
        cube_list = []
        for i in range(nparams):
            cube_list.append(cube[i])
        to_return = np.sum(
                    -(len(x)/2.0)*np.log(2*np.pi) -
                    (len(x)/2.0)*np.log(yerr) -
                    (1/(2*yerr))*np.power(y - ( temp_spec.return_yvals(line_range=x, params=cube_list) + poly_nomial(x)), 2.0)
                    )

        return to_return
    return lnlike
```

A few words.
-  Rather then trying to pass through additional arguments into the likelihood and transform functions as items in the cube, I instead perform a closure with each. I found that easier to handle. 
- Parinfo is a list of dictionaries, where each dictionary has a key called 'limits'. The limits key has a 2 element list, such that [minimum, maximum]. If there is no set limit for either, then None will be used.
- The spectraa object is a class I wrote to help me manage which parameters go with which peak shape function (often they are merely gaussians, although I can also specify others). I merely pass through a list of the parameters for all shapes as defined in my model, and the spectraa class distributes them out accordingly. When I call the return_yvals(), it returns a single 1D numpy array with each of the peaks summed. 
- The poly_nomial represents structure outside the peak shape functions and is not being included in this fit.

**Comment by JohannesBuchner** [comment]
The analyzer bug should be fixed in the latest version.

I am not sure why your run returns only a single point, that has to do with the other sampled points having extremely low weights, for example because there is only a single tiny peak. Put some print statements to debug, and sample around that posterior point to see what is going on.
