### ISSUE TITLE
Problem installing PyMultiNest with MPI on OSX Yosemite. 

### ISSUE THREAD

**Issue by abhijithrajan** [JohannesBuchner/PyMultiNest#70]
I am trying to install MultiNest on OSX 10.10.5, as part of the larger PyMultiNest installation following the instruction provided in - http://johannesbuchner.github.io/pymultinest-tutorial/install.html. The installation appears to have succeeded. However it does this without installing the MPI libraries. 

I get the following errors when running MAKE - 
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
-- Could NOT find MPI_Fortran (missing:  MPI_Fortran_LIBRARIES MPI_Fortran_INCLUDE_PATH) 
-- MPI not found, only non-MPI MultiNest libraries will be built.

I have installed OPENMPI via macports on the machine.

**Comment by JohannesBuchner** [comment]
Please ask in the Multinest forums at http://ccpforge.cse.rl.ac.uk/gf/project/multinest/forum/
This issue is not related to PyMultiNest.
