### ISSUE TITLE
version `GFORTRAN_1.4' not found error with anaconda

### ISSUE THREAD

**Issue by MichelleLochner** [JohannesBuchner/PyMultiNest#71]
I have the exact same problem as issue #48, but this time with anaconda. Is there a workaround to (for example) compile multinest with the same compiler anaconda uses? Quite a lot of people are using anaconda these days, it'd be great if there's a straight-forward way to get around this.

**Comment by JohannesBuchner** [comment]
Try setting cmake variables. 

e.g.

```
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
```

You can also set CMAKE_PREFIX_PATH if all your libraries are from anaconda. A list of environment variables is here: https://cmake.org/Wiki/CMake_Useful_Variables

**Comment by MichelleLochner** [comment]
Thanks Johannes. That didn't help but I just updated anaconda and it worked. Go figure.
