### ISSUE TITLE
Issue with the handling of n_dims between pyMultiNest and MultiNest

### ISSUE THREAD

**Issue by DeannaCH** [JohannesBuchner/PyMultiNest#72]
Hi,
There seems to be a compiler-dependent issue with the handling of the n_dims variable between pyMultiNest and MultiNest when passed to run() as part of a keyword dictionary. 
The value of n_dims is correctly initialised, but becomes random when it is passed later as an argument of the functions prior() and loglike()

As an example, I attach a small modification of pymultinest_demo_minimal.py. When I run this demo, the printed value of n_dims is very different than the initialization value (usually a huge negative integer).
This happens when MultiNest has been compiled with ifort and nagfor, but does not happen when compiled with gfortran.
I suspect that the problem is related to the way in which the integer is coded (number of bytes, signed/unsigned): when using ifort and nagfor, there must be a wrong conversion somewhere in the python-fortran interfacing.

[pymultinest_demo_minimal_break.txt](https://github.com/JohannesBuchner/PyMultiNest/files/187623/pymultinest_demo_minimal_break.txt)

**Comment by JohannesBuchner** [comment]
This is strange. I suspect the python garbage collector removes n_params or n_dims while it is still in use by C. However that should not happen because integers are passed as values, not pointers.

Did you try printing in the fortran interface what values are received, so we can narrow it down?

**Comment by JohannesBuchner** [comment]
Please reopen if this problem still occurs with the latest version.
