### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by joro123** [JohannesBuchner/PyMultiNest#74]
Hello,
I followed the installaton instruction on http://johannesbuchner.github.io/pymultinest-tutorial/install.html# and it seemed that everthing worked fine. But when I tried to run example 1 from the tutorial, python gave me the error message:

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

but I used to commands:

$ cd MultiNest/build/
$ cmake .. && make
$ export LD_LIBRARY_PATH=/my/directory/MultiNest/lib/:$LD_LIBRARY_PATH

any ideas ?

Jonas

**Comment by JohannesBuchner** [comment]
You have to use your MultiNest directory instead of /my/directory/MultiNest/lib/ , so that PyMultiNest can find libmultinest.so :)

**Comment by joro123** [comment]
great thanks :)
I'm new to Linux and just copy-and-pasted it

**Comment by Albertmatt** [comment]
Hi @JohannesBuchner 

I've been having the same error and even after setting my path I still get the same error

ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory

Please help

**Comment by JohannesBuchner** [comment]
@Albertmatt, which operating system do you use and what did you set LD_LIBRARY_PATH to?

**Comment by Vladan1986** [comment]
Hi Johannes, 

I have a similar issue. 

The commands I used: 

$ cd MultiNest/build/
$ cmake .. && make
$ export LD_LIBRARY_PATH=/home/Vladan/MultiNest/lib/:$LD_LIBRARY_PATH

The error I get when I run the code (e.g. import bagpipes as pipes) on Jupyter Notebook is:


ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory
Bagpipes: PyMultiNest import failed, fitting will be unavailable.

If I go to the /home/Vladan/MultiNest/lib/ directory the libmultinest.so is there.

echo $LD_LIBRARY_PATH  returns:

/home/vladan/MultiNest/lib/:/home/vladan/MultiNest/lib/:/home/vladan/MultiNest/lib/:/my/directory/MultiNest/lib/:/home/vladan/Programs/gildas-exe-dec21a/x86_64-ubuntu20.04-gfortran/lib::/home/vladan/Programs/gildas-exe-dec21a/x86_64-ubuntu20.04-gfortran/lib:

My os is Ubuntu 20.04.5 LTS


Any advice or suggestion is welcome. 
Cheers,

**Comment by JohannesBuchner** [comment]
the obvious question: is libmultinest.so in /home/vladan/MultiNest/lib/ ? what does ldd say about the file?

**Comment by JohannesBuchner** [comment]
can you check the environ variable from the jupyter notebook as well?

**Comment by Vladan1986** [comment]
ldd libmultinest.so returns:

	linux-vdso.so.1 (0x00007ffc931bc000)
	liblapack.so.3 => /lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f9261a60000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f9261798000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9261649000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f926162e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f926143c000)
	libblas.so.3 => /lib/x86_64-linux-gnu/libblas.so.3 (0x00007f92613cd000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f9261383000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f92621ce000)

Actually, the problem has been solved simply by restarting the computer... Thank you in any case.

Cheers,
