### ISSUE TITLE
Progress Plotter issue

### ISSUE THREAD

**Issue by TimothyADavis** [JohannesBuchner/PyMultiNest#75]
On Python 3.5.1, Numpy 1.11.0, Matplotlib 1.5.1 the progress plotter code as distributed does not work because it seems the subplots seem to be one indexed, not zero?

In watch.py changing

`plt.subplot(self.n_params, 1, i)` to `plt.subplot(self.n_params, 1, i+1)` solves the issue. A similar change also has to be made in the pymultiplot demo file.

**Comment by JohannesBuchner** [comment]
Hi Timothy,

thank you for spotting this! I will fix it. What has to be changed in
the pymultiplot demo file?

**Comment by TimothyADavis** [comment]
Hi Johannes,

Apologies- I was misremembering. The only change in the demo file was that for some reason on my Mac, os.name returns 'posix'. I thus had to change 'xdg-open' to 'open'. 
So thats an unrelated issue!

Cheers,
Tim

**Comment by JohannesBuchner** [comment]
Ok, I pushed the changed and released a new version. Please test it.
