### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by madanh** [JohannesBuchner/PyMultiNest#78]
Hello again:)

It might not really be a deficiency of software but I decided to ask here for the benefit of public.

I get a memory leak somewhere. I suspect that this might be because I'm casting to numpy array from ctypes  in my loglikelihood function. Disclaimer: no prior experience with ctypes. Doing this because some of the parameters are elements of a correlation matrix and I do Cholesky decomposition and other linear algebra on the reconstructed matrix.

There are three questions:

1. Does casting from ctypes to numpy arrays cause memory leaks?
2. If so, what is the proper way to go if I want to use linear algebra on the (ctypes) input supplied by pymultinest?
3. Is returning -np.inf appropriate or some other constant should be used?

Here is the gist of the loglikelihood function:

https://gist.github.com/madanh/a3e9a7e621f7fc5c50d7513de37f7ab8

**Comment by JohannesBuchner** [comment]
np.array calls always allocate new memory, and they tend to stick around.
Try the new solve API, it passes a numpy array into your likelihood function, then you do not need to call numpy.array.

At the most extreme, you could declare all your arrays outside the likelihood function, and inside only assign values.

-np.inf is bad. below -1e90 values have a special meaning. Check the MultiNest manual.

Also, as every numerical programmer will tell you -- never invert matrices, even when the formulae tell you to do so. There is usually a better, numerically stable way to not explicitly invert matrices.

**Comment by JohannesBuchner** [comment]
I sometimes use -1e300 if a value is very unlikely but can not be calculated. 

In general it is better to define the prior so that these values can not occur.

**Comment by madanh** [comment]
Replacing `-np.inf` with `sys.float_info.min` has got things running. Now it at least completes with 4400 points.
This however raises another issue, most likely in MultiNest (without Py), which is that the last item in _equal_weights.dat file is written literally as `0.222507385850720138-307`. Which is the actual value of `sys.float_info.min` but with the mantissa-exponent separating "E" missing. This leads to exceptions in Analyzer when numpy is trying to read that file. It is straightforward to work around with some post-processing though.

**Comment by madanh** [comment]
Oh, posted the above before updating so didn't notice your reply. Thanks for the hints. Will check the MultiNest manual next.

**Comment by JohannesBuchner** [comment]
Using the lowest float(double) may not sit well with MultiNest, because it still needs to compute with that likelihood, e.g. add the volume shrinkage factor, which further decreases the value. 
Nevertheless, a missing"E" in the output is a bug, and you might want to report it with a minimalistic C or fortran example.

**Comment by madanh** [comment]
For historical record:
I was unable to find a proper manual for MultiNest. But from README file it is clear that impossible configurations can be encoded using a value lower than the `logZero` parameter in Fortran , which apparently translates to `log_zero` in `pymultynest.run` with a default value of `-1e100`.
