### ISSUE TITLE
Discontinuity in lnEv

### ISSUE THREAD

**Issue by DouglasBoubert** [JohannesBuchner/PyMultiNest#79]
I have an issue in a very basic usage of PyMultiNest. When I run the code below with null_val below the minimum threshold for the likelihood to be set to -infinity, ie. null_val = -1.0e250, this returns a lnEv of zero. But if null_val is greater than this threshold but still tiny, ie. null_val = -1.0e50, this returns a InEv of -0.5. If I vary this parameter around I get exactly the same answer, which I would expect since this small a likelihood should be contributing a negligible amount to the answer. There are two things I don't understand about this behaviour:

1) Why should the difference between an extremely negative null_val and negative infinity cause a discontinuity in the answer?
2) Why is each case giving the lnEv values they are?

I expect this is probably just me misunderstanding how MultiNest works, rather than a bug.

Thanks for any help you can give!

```python
from __future__ import absolute_import, unicode_literals, print_function
import pymultinest
import math, os
import numpy as np
if not os.path.exists("chains"): os.mkdir("chains")

# our probability functions
xmin=0.
xmax=2.
ymin=0.
ymax=2.

null_val = -1.0e50

def myprior(cube, ndim, nparams):
    cube[0]=xmin+(xmax-xmin)*cube[0]
    cube[1]=ymin+(ymax-ymin)*cube[1]

def myloglike(cube, ndim, nparams):
    x=cube[0]
    y=cube[1]
    if x>1.0:
        return null_val
    else:
        return 0

# number of dimensions our problem has
parameters = ["x", "y"]
n_params = len(parameters)

# run MultiNest
pymultinest.run(myloglike, myprior, n_params, resume = False, n_live_points = 2000, verbose = True, importance_nested_sampling=False, evidence_tolerance=0.000001, sampling_efficiency = 'model')'''

**Comment by JohannesBuchner** [comment]
If the likelihood function returns a value lower than -1e100, that part of the parameter space is taken to be invalid and not counted for the integration. 
log_zero = -1e100 controls this in pymultinest, and corresponds to logZero. See the Multinest README, a copy of which you can find here: https://github.com/JohannesBuchner/MultiNest

**Comment by DouglasBoubert** [comment]
Thanks for the quick reply. I am a bit confused by that behaviour, as I don't believe that is what MultiNest should be doing. It means you are throwing away parts of the parameter space and re-normalising the prior, which makes the evidence calculated by MultiNest different from the true evidence.

It approximately works if there are only small regions of the parameter space where the likelihood is small, but there are certainly problems where most of the parameter space can return a tiny likelihood and thus the evidence returned by MultiNest is then arbitrarily different from the true evidence.

**Comment by JohannesBuchner** [comment]
It is an additional way to specify complex prior information, where in the likelihood function you realise that this parameter space is actually impossible (without looking at the data). So it is the true evidence if these regions are cut out.
If you do not want this feature, set log_zero to a lower value (e.g. -1e300), or add a small value to the likelihood values returned.
