### ISSUE TITLE
Issue with the arguments of the dump_callback function

### ISSUE THREAD

**Issue by bthoven** [JohannesBuchner/PyMultiNest#80]
Hi,

I'm trying to use the following callback function to watch the progress of `pymultinest.run` (I got it from the issue #18):

```python
def progress(nsamples, nlive, n, *args):
    print 'python dumper callback called!'
    sys.stdout.flush()
    print nsamples, nlive, n
    sys.stdout.flush()
```

However, when I try to run the code I get this error:

```python
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/thoven/Programs/miniconda2/lib/python2.7/site-packages/pymultinest/run.py", line 225, in dumper
    (pc[0,:],pc[1,:],pc[2,:],pc[3,:]), # (mean,std,bestfit,map)
IndexError: index 2 is out of bounds for axis 0 with size 2
```

The code snippet in _run.py_ referenced by the error message above is:

```python
220             pc =  as_array(paramConstr,shape=(nPar,4))
221
222             dump_callback(nSamples,nlive,nPar,
223                 as_array(physLive,shape=(nPar+1,nlive)).T,
224                 as_array(posterior,shape=(nPar+2,nSamples)).T,
225                 (pc[0,:],pc[1,:],pc[2,:],pc[3,:]), # (mean,std,bestfit,map)
226                 maxLogLike,logZ,logZerr)
```

If I understood it correctly, `pc` is an array of shape `(number of params, 4)`, but line 225 attempts to access it as if it were its transpose. Is this a bug in the code? Or I'm missing something?

Thanks.

PS: The version of PyMultiNest is 2.1.

**Comment by JohannesBuchner** [comment]
Hi @bthoven,

it is quite possible that this functionality has bugs. It is largely untested. If you put in some print statements you can explore what is actually being passed.

Johannes

**Comment by JohannesBuchner** [comment]
Please reopen if you still have issues.

**Comment by JohannesBuchner** [comment]
see also #18
