### ISSUE TITLE
Windows DLL, pymultinest and lapack link issue (maybe it's minor)

### ISSUE THREAD

**Issue by ajamyajax** [JohannesBuchner/PyMultiNest#81]
Hi Johannes,

I'm trying to create the Windows DLL and can't seem to get the lapack library to link. Any ideas would be appreciated. All source compiled with GNU Fortran (GCC) 5.3.0.

gfortran -shared -o libmultinest.dll utils.o utils1.o priors.o kmeans_clstr.o xmeans_clstr.o posterior.o nested.o -llapack.a

With the above I get the following reference errors.. (Including those object files just produced a long list of missing lapack references.)

utils1.o:utils1.f90:(.text+0x1a5): undefined reference to 'dpotrf_'
 utils1.o:utils1.f90:(.text+0x37b1): undefined reference to 'dsyevr_'
 utils1.o:utils1.f90:(.text+0x3974): undefined reference to 'dsyevr_'
 xmean_clstr.o:xmeans_clstr.f90:(.text+0x11adc): undefined reference to 'dlasrt_'
 nested.o:nested.F90:(.text+0x270c): undefined reference to 'dgeev_'
 collect2.exe: error ld returned 1 exit status

Thanks, Mark

**Comment by JohannesBuchner** [comment]
This question is about the Multinest project, you can find their forum here: https://ccpforge.cse.rl.ac.uk/gf/project/multinest/ 
I am not sure if Multinest is tested on windows. You might have some success with cygwin?

**Comment by ajamyajax** [comment]
The question is about PyMultiNest linking in some of the fortran code from
MultiNest, I presume.

There is a Windows DLL reference in your python package, so I thought you
might like to finish that up. ???
Compatibility might be close too, I just can't figure out how to link in
those lapack referenced functions.

Also maybe you know this, but there are a number of python package setups
that install and run just fine on Linux and Windows platforms -- without
needing Cygwin.
I can help with the Windows beta testing here and provide you with a
libmultinest.DLL when it's working, if you like.

That means I'll do most of the work, I could just use any linking ideas you
might have to try.

Best Regards, Mark

**Comment by JohannesBuchner** [comment]
Your error message shows that you can not build libmultinest.dll

To use pymultinest with the library (once you have it), should work automatically.
