### ISSUE TITLE
Call function on exit

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PyMultiNest#82]
@JohannesBuchner Tricky question: In python, on the first call of my loglike I can initialize as follows:

```
init=False
my_loglike(cube,....):
    global init
    if not inited:
        # init here
        # Do stuff here; then:
        init=True
    # On each iteration:
    # Do stuff here
    return
```

BUT, any idea how to call a function (in my case a C library free call, but could be anything) on exit/termination of multinest run?

**Comment by JohannesBuchner** [comment]
Why don't you call these functions before and after multinest.run?
