### ISSUE TITLE
"cube" and prior

### ISSUE THREAD

**Issue by raphaelshirley** [JohannesBuchner/PyMultiNest#83]
Hello,

I am attempting to use pymultinest to calculate the evidence for some models of galaxy luminosity profiles. I want to use a multivariate gaussian as a prior on all my parameters.

I see in the example that the myprior() function takes in an object called cube. Is this an array of functions with uniform priors on all the parameters? If so how would I modify it from within a prior function? Can you specify the form the cube object takes and how could I specify a more complicated prior. Am I right in thinking that pymultinest feeds in a N-dimensional cube of unit length and expects myprior to modify it? Because it appears that cube is merely an array of unit lengths which are multiplied by a number to increase the size of the top hat. I'm interested as to why you didn't require a prior function which took a specific parameter vector and output a normalised probability distribution function.

Sorry if this is explained somewhere else already. If so could you point me to the relevant documentation.

Many thanks,

Raphael Shirley.

Daphne Jackson Research Fellow
Astronomy Centre
University of Sussex

**Comment by JohannesBuchner** [comment]
> I see in the example that the myprior() function takes in an object called cube. Is this an array of functions with uniform priors on all the parameters? If so how would I modify it from within a prior function? Can you specify the form the cube object takes and how could I specify a more complicated prior. Am I right in thinking that pymultinest feeds in a N-dimensional cube of unit length and expects myprior to modify it? Because it appears that cube is merely an array of unit lengths which are multiplied by a number to increase the size of the top hat. I'm interested as to why you didn't require a prior function which took a specific parameter vector and output a normalised probability distribution function.

Exactly, the prior is prescribed by the stretching of the unit cube. This is a general approach; all you need is the cumulative of an arbitrary distribution and inverse it.
scipy.stats.norm(mu, std).ppf would do the appropriate thing for a 1d gaussian prior.

For a multi-variate gaussian (lets say 2d for example) the approach is similar.
You compute the cumulative across the first dimension, choose the appropriate point for 0-1. Then go to the second dimension. Given the choice in the first dimension, there is a conditional cumulative distribution. This allows you to choose the (dependent) point for the second dimension.

Hope that helps.

**Comment by raphaelshirley** [comment]
Yes, thank you very much for getting back to me. I think I understand how to implement a general prior now.

Many thanks,

Raphael.
