### ISSUE TITLE
Strange Output in stats, live.points and summary files

### ISSUE THREAD

**Issue by 3rico** [JohannesBuchner/PyMultiNest#88]
The 1-stats.dat file below shows standard deviation as 0.
[1-stats.dat.txt](https://github.com/JohannesBuchner/PyMultiNest/files/1102203/1-stats.dat.txt)

The 1-summary.txt file shows a strange number as the likelihood: 0.210669196134190853-315
[1-summary.txt](https://github.com/JohannesBuchner/PyMultiNest/files/1102210/1-summary.txt)

Why do these anomalies occur? especially with the second anomaly, how can that number be interpreted?

**Comment by JohannesBuchner** [comment]
Hi @3rico, sorry for not seeing this earlier. There seems to be a problem with your likelihood function, returning a extremely small number of a non-number. Print the values before they are returned.
