### ISSUE TITLE
problem: dlopen(libmultinest.dylib, 6): image not found

### ISSUE THREAD

**Issue by Yoffeg** [JohannesBuchner/PyMultiNest#89]
Hi Johannes,

I'm trying to install PyMultiNest on Mac and have followed all your instructions part the last one, regarding Mac installation (using DYLD..... instead of LD Library path). I can't seem to grasp how to do it and when I execute the "export LD_LIBRARY_PATH=/my/multinest/directory/lib:/my/cuba/directory/:/my/apemost/directory/:$LD_LIBRARY_PATH" command while being in the PyMultiNest directory, I receive a "File already exists" response.

That said, when I attempt to run a code in which Pymultinest is incorporated (using PyCharm, Python 3.6) I receive problem: dlopen(libmultinest.dylib, 6): image not found".

I'm a beginning Linux and Python user and would appreciate any piece of wisdom you could throw at me.

Thanks in advance,

Gidi.

**Comment by JohannesBuchner** [comment]
PyMultiNest will try to load the library libmultinest.dylib (on Mac, libmultinest.so on Linux) in the dynamic library search path (usually /usr/lib/, etc.). Because we have it in some download directory, we have to tell pymultinest where to find that library. The environment variables LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH) allow us to point it to a custom folder. It should be sufficient to set DYLD_LIBRARY_PATH to the path where that file is on your computer.

**Comment by Yoffeg** [comment]
Thank you very much for your advice!

I resolved the issue by placing the libraries in the PyCharm (the IDE I'm using) project directory.

I have two additional queries regarding which I'd greatly appreciate your advice:

1. When setting a specifically wide prior range, the output Chi-square is a sequence of numbers ending with (...-323). 
This does not occur when the prior range is narrowed to values proximal to those of a reference paper which studied the same data. Then, reasonable Chi-square values are received.

2. When setting max_iter to a certain number, I expect the amount of runs (data points) equal that number, but the received amount is usually far less than that. For a certain value of max_iter, I observed that the amount of data points converge to a certain value (for example - for max_iter of 10k, each run yields approximately 2800 data points)
Additionally, the algorithm finishes its run even when max_iter is not defined. I assume there is a certain condition of Chi-square converges that terminates it, but I couldn't find it.

Thanks a lot in advance,

Gidi

**Comment by JohannesBuchner** [comment]
re: 1) not sure, maybe the samples did not find the tiny peak in the space. Use prints to see where it goes (or look into the output samples).

re: 2) you can find the termination criterion in the paper, it is based on Lmax*V and the tolerance parameter, the highest live point likelihood multiplied by the remainder volume. I never set max_iter. Should also be described somewhere in the MultiNest README file.

**Comment by JohannesBuchner** [comment]
re: 1) not sure, maybe the samples did not find the tiny peak in the space. Use prints to see where it goes (or look into the output samples).

re: 2) you can find the termination criterion in the paper, it is based on Lmax*V and the tolerance parameter, the highest live point likelihood multiplied by the remainder volume. I never set max_iter. Should also be described somewhere in the MultiNest README file.

**Comment by Yoffeg** [comment]
Hello Johannes and thanks for your reply.

I've been running PyMutiNest a while and seems that I got a hang over the issue now.
However, I have an additional issue I'd appreciate your advice about:

I'm able to open the .points file with Matlab and transform the cube values to the prior parameter values, as well as the likelihood values to chi-squared. There seem to be much more points there than in the .txt file and even higher likelihood fits. Considering there is no reference of this file in the README, I'd appreciate if you clarify as to what this file represents, how does it differ from the .txt file and whether can this data be analyzed in stead of the .txt file.

Thanks a lot again,

Gidi

**Comment by JohannesBuchner** [comment]
Hi @Yoffeg, you would have to contact the multinest authors about that question. https://ccpforge.cse.rl.ac.uk/gf/project/multinest/ -- Johannes
