### ISSUE TITLE
Can not find libmultinest.dylib on Mac

### ISSUE THREAD

**Issue by hereiskaye** [JohannesBuchner/PyMultiNest#90]
Hi. I am using MacOS 10.12. I just installed MultiNest and PyMultiNest on the computer following the instructions [install-on-mac](http://johannesbuchner.github.io/PyMultiNest/install.html#install-on-mac) , both installation showed no error. but when i tried 
`python -c "import pymultinest"`
, it shows:
`problem: dlopen(libmultinest.dylib, 6): image not found`

My libmultinest.3.10.dylib and libmultinest.dylib are in /usr/local/lib, I tried setting this path to DYLD_LIBRARY_PATH or LD_LIBRARY_PATH in ~/.bash_profile (and source it), but none of them worked. But if I import the pymultinest under this directory, i.e.:

```
cd /usr/local/lib
python -c "import pymultinest"
```
it works, and running the pymultinest_demo.py showed no error as well. So the problem is that PyMultiNest cannot find the dylib properly.  I wonder how can I fix this? Thank you so much!

**Comment by ricphy** [comment]
Hey, I'm also a mac user, same OS version,
I followed the instruction strictly, and it works :-)
Have you renamed your .dylib files to .so files?
Just check the installation list and make sure every step has been carried
out,
Good Luck!

Jiaxin Wang
--------------
AstroParticle Phys,
SISSA

**Comment by JohannesBuchner** [comment]
If indeed /usr/local/lib/libmultinest.dylib exists (and is not a broken symlink, check with ldd), `DYLD_LIBRARY_PATH=/usr/local/lib python -c "import pymultinest"` should work.

**Comment by JohannesBuchner** [comment]
See issue https://github.com/JohannesBuchner/PyMultiNest/issues/68#issuecomment-173569687
