### ISSUE TITLE
 problem: dlopen(libmultinest.dylib, 6): image not found

### ISSUE THREAD

**Issue by husnedereli** [JohannesBuchner/PyMultiNest#91]
Hi, 
I am trying to settle 3ML but I got error related with libmultinest.dylib. 
#############################################################################
Hs-MacBook-Pro:lib husnedereli$ sudo -H pip install git+https://github.com/giacomov/3ML.git
Collecting git+https://github.com/giacomov/3ML.git
  Cloning https://github.com/giacomov/3ML.git to /private/tmp/pip-2ecGtD-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/threeML.egg-info
    writing requirements to pip-egg-info/threeML.egg-info/requires.txt
    writing pip-egg-info/threeML.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/threeML.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/threeML.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/threeML.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/threeML.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/threeML.egg-info/SOURCES.txt'
    problem: dlopen(libmultinest.dylib, 6): image not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-2ecGtD-build/
Hs-MacBook-Pro:lib husnedereli$ 
#############################################################################

I tried to use the solutions that you suggested in the other issue but it doesn't work even giving path like that : export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/multinest/lib
 or copying dylib file in anaconda lib. Is there any mistake in my path?

###################################################
Hs-MacBook-Pro:~ $ cd /usr/local/multinest/lib
Hs-MacBook-Pro:lib $ ls
libmultinest.3.10.dylib	libmultinest.a		libmultinest.dylib
####################################################
Thank you in advance, 
Husne

**Comment by JohannesBuchner** [comment]
Hi @husnedereli, 

First of all, I am not sure your path goes into pip. It might set up a protected environment and control its variables. Also not sure your path survives sudo.
Best to print out the library path in python to be sure.

Also, see https://github.com/JohannesBuchner/PyMultiNest/issues/68#issuecomment-173569687 

Cheers, 
             Johannes

**Comment by JohannesBuchner** [comment]
I updated the installation instructions on MacOS: http://johannesbuchner.github.com/PyMultiNest/install.html If you have any suggestions for improvements, they would be welcome (I don't use it).
