### ISSUE TITLE
Prior Convergence Warning

### ISSUE THREAD

**Issue by antolonappan** [JohannesBuchner/PyMultiNest#92]
With certain combinations of Chi-Square, I am getting a MultiNest warning that parameter is converging to the edge of the prior. I using the prior definition with which emcee-MCMC hammer giving fine likelihood. Even though MultiNest throws this warning it also gives the log evidence. So could you please explain why it's showing this error, also can I consider those results with the warning.

**Comment by JohannesBuchner** [comment]
Have a look at the marginal posterior distributions. The warning means that they go towards an edge.

**Comment by antolonappan** [comment]
What about the result with this warning, can I consider it as log evidence

**Comment by JohannesBuchner** [comment]
Yes

**Comment by antolonappan** [comment]
Thank you very much
