### ISSUE TITLE
ERROR: Could not load MultiNest library: libmultinest.so

### ISSUE THREAD

**Issue by rrhavia** [JohannesBuchner/PyMultiNest#93]
I have used the tutorial (http://johannesbuchner.github.io/pymultinest-tutorial/install.html#on-your-own-computer) to install MULTINEST and PyMultinest except that I installed pymultinest for all users. I get this error:
ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory
 

How can i solve this problem?

Thanks.

**Comment by JohannesBuchner** [comment]
Hi @rrhavia , sorry that I did not see this earlier. Were you able to solve it with the  manual: http://johannesbuchner.github.com/PyMultiNest/install.html ? You need to build MultiNest!

**Comment by JohannesBuchner** [comment]
Please reopen if you still have this issue.
