### ISSUE TITLE
Are there instructions for Windows?

### ISSUE THREAD

**Issue by luiswel** [JohannesBuchner/PyMultiNest#95]
I am fairly new to these installations. I successfully installed and used pymultinest in Ubuntu and a Red Hat distribution. Now I am trying to install it in Windows. Do you have a set of instructions for that? I am having problems creating the libraries as there seems to be a problem with the compilers. I am using anaconda with python3. 
Thank you.

**Comment by JohannesBuchner** [comment]
You have to ask in the multinest forums how to install multinest on Windows. I am not sure it is supported at all. pymultinest can be installed as usual with pip.

Using a virtual machine may be easier.
