### ISSUE TITLE
Memory grows proportional to sample count

### ISSUE THREAD

**Issue by adamjermyn** [JohannesBuchner/PyMultiNest#98]
For long pymultinest runs it looks like the memory usage grows proportional to the number of samples used. At any given time the memory use seems to be ~2-3x greater than the space taken by the IS.points file. I understand that to analyse the posterior distribution the full set of samples is needed, but I had thought that the actual multinest run could be done only keeping the live samples in memory. This has become a problem for me because I'm interested in drawing a large number of samples for problems in many (>30) dimensions. Is there a way to prevent the memory usage from growing?

For context a minimum working example is given by modifying the demo script to run with many live points and in many dimensions, as below:

`
from __future__ import absolute_import, unicode_literals, print_function
import numpy
from numpy import pi, cos
from pymultinest.solve import solve
import os
if not os.path.exists("chains"): os.mkdir("chains")

def myprior(cube):
	return cube * 10 * pi

def myloglike(cube):
	chi = (cos(cube / 2.)).prod()
	return (2. + chi)**5

dim = 20
parameters = ['p' for _ in range(dim)]
n_params = len(parameters)

prefix = "chains/3-"

result = solve(LogLikelihood=myloglike, Prior=myprior, 
	n_dims=n_params, outputfiles_basename=prefix, verbose=True, n_live_points=1000, resume=False)

print()
print('evidence: %(logZ).1f +- %(logZerr).1f' % result)
print()
print('parameter values:')
for name, col in zip(parameters, result['samples'].transpose()):
	print('%15s : %.3f +- %.3f' % (name, col.mean(), col.std()))
`

**Comment by JohannesBuchner** [comment]
This is a "issue" with multinest, not pymultinest (unless you have a memory leak in your python code).  Importance nested sampling (INS) needs to keep all points in memory (and stores also on the disk), which can make up hundreds of megabytes.
So I suggest you turn off INS (importance_nested_sampling = False).

**Comment by adamjermyn** [comment]
That works, thank you!
